### ISSUE TITLE
Android backButton doesn't generate any event

### ISSUE THREAD

**Issue by Mactub07** [plaid/react-native-plaid-link-sdk#103]
Platform: Android;
"react-native-plaid-link-sdk": "^3.0.1",

Description:
I'm using event listener like it's described in documentation;

const emitter = new NativeEventEmitter(Platform.OS === 'ios' ? NativeModules.RNLinksdk : NativeModules.PlaidAndroid);
    this._listener = emitter.addListener('onEvent', (e) => console.log(e));

ISSUE:
Steps:
- open plaid widget on Android device
- widget is opened
- click android back button
- widget is closed but there is no any event about it

Expected behavior:
 when widget is closed with using back button android, event should be generated , event type 'EXIT'

**Comment by amytang0** [comment]
Hi, cancellation events are structured slightly differently than normal events.
For example, I see:
`Exit:  {"link_session_id": "b461e4ec-228f-4efc-94ca-a39a982b4f6d"}` in the logs, when pressing back an exiting.
Can you let me know if you see this event instead?

**Comment by Mactub07** [comment]
@amytang0 , I also receive 'exit' event when I use 'callback approach' like you have

onExit={data => console.log('exit: ', data)} (like in documentation)

When I do the same with eventListener approach I can see events like Plaid describes https://plaid.com/docs/#onevent-callback (for example HANDOFF, 'OPEN',)  but BackButton doesn't generate 'any' event

**Comment by amytang0** [comment]
I believe you actually want the `onCancelled` listener, `onExit` is for non-user initiated exits.
