### ISSUE TITLE
Android: StatusBar style don't changing according to Plaid Connection Screen;

### ISSUE THREAD

**Issue by pilotocheg** [plaid/react-native-plaid-link-sdk#104]
![Screenshot_1585825773](https://user-images.githubusercontent.com/38259170/78243983-6b085200-74ed-11ea-94b6-f60aee2ff951.png)
If StatusBar was with custom styling before plaid linking opened then it looks like on screenshoot. I tried to imperatively change status bar styles via ```StatusBar.setBarStyle('dark-style')``` But nothing happens

**Comment by zsweigart** [comment]
Hi @pilotocheg thanks for the feedback.  Unfortunately we do not currently support changing the color of the status bar.
