### ISSUE TITLE
"Balance" product seems to be unsupported

### ISSUE THREAD

**Issue by suriarte-orangeloops** [plaid/react-native-plaid-link-sdk#11]
As seen [here](https://github.com/plaid/react-native-plaid-link-sdk/blob/58874b05a9ffbb0cf33a035e8ebda685f32cbb7c/PlaidLink.js#L93), the "Balance" product seems to be unsupported. When `onSuccess` method is called with a `data` object, balances are missing from accounts returned.

**Comment by zsweigart** [comment]
The balance as an initial product is not valid it can only be used through API call on an existing item.  Please use the Auth product to link your users then you can get the balance.  See here plaid.com/docs/quickstart/#auth-data
