### ISSUE TITLE
Request for hooks

### ISSUE THREAD

**Issue by alexandrasmith00** [plaid/react-native-plaid-link-sdk#110]
I'm wondering if there's any intention to add a hook for the plaid link in this library. I can see that [react-plaid-link](https://github.com/plaid/react-plaid-link) has both component and hook based implementations. Is there any roadmap for adding that functionality to react native?

**Comment by zsweigart** [comment]
Hi @alexandrasmith00 can you check with version 6.0.3?

**Comment by pladaub** [comment]
Hey @alexandrasmith00 we export imperative APIs that can make functional components work with the SDK. Are there specific hooks we don't have that would make the SDK better suited for your use case?
