### ISSUE TITLE
`dismissLink` doesn't work on android. 

### ISSUE THREAD

**Issue by rajeshdongre** [plaid/react-native-plaid-link-sdk#112]
Hi,
We have integrated `react-native-plaid-link-sdk` to use Plaid capabilities. We are using `openLink` to integrate component and it works perfectly both on iOS and Android. 
But for one of our use case we need to dismiss the Plaid Link Component. To solve this use case, we are using `dismissLink`. But we figured out that `dismissLink` doesn't work on android as there is no implementation done for the method. Secondly, `PlaidLink` component doesn't have any such method to dismiss the Plaid Link Component.
Can you guys help us out to resolve this use case and add support for `dismissLink` on Android?

Thanks & Regards,
Rajesh Dongre

Tech Stack:
react-native: 0.61.5
react: 16.9.0
react-native-plaid-link-sdk: 3.1.2

**Comment by amytang0** [comment]
Hi Rajesh, we currently do not support `dismissLink` on Android, would you mind me asking what your use-case for this would be?

**Comment by rajeshdongre** [comment]
Hi Amy,
First of all thanks for your quick response. So in our use case whenever user selects a specific Bank either from list or from top list, we need to dismiss the Component and start a new UI flow. The reason behind this that the bank is currently not supported by Plaid and it's one of our top most used Bank.
Hope this explains the use case that we are trying to solve for.

Thanks & Regards,
Rajesh Dongre

**Comment by amytang0** [comment]
Hi Rajesh,

`dismissLink` exists on iOS and Web for legacy reasons to address issues related to browser behavior, but those issues do not exist on the new Android SDK. I would suggest you to reach out to support@plaid.com about the bank you need supported, as Plaid does not support switching flows mid-way.

Sorry and good luck!
