### ISSUE TITLE
Linking Plaid link sdk with CocoaPods

### ISSUE THREAD

**Issue by ashanjayasundara** [plaid/react-native-plaid-link-sdk#113]
I am trying to integrate plaid link sdk with cocoapod (react-native:0.62.0) i am confusing on **Run Script** adding step because i have follow the step but widget is crashing seem i haven't properly integrate Run script step so can i have an advance support for this 
![Screen Shot 2020-04-24 at 7 55 04 PM](https://user-images.githubusercontent.com/16848987/80224310-2775b380-8667-11ea-8e7e-04609442ab31.png)

**Comment by rajeshdongre** [comment]
@ashanjayasundara 
This script is required to strip Simulator binary symbols from framework but as of Xcode 11.x it's not required. So you can skip this step.
