### ISSUE TITLE
Search text color is white

### ISSUE THREAD

**Issue by jake-long-game** [plaid/react-native-plaid-link-sdk#115]
Is there a way to change the search text color? currently it's white and it's quite hard to read
![Screen Shot 2020-04-30 at 1 34 43 AM](https://user-images.githubusercontent.com/45996516/80689948-ef190f80-8a82-11ea-89fd-0407e5e2cd01.png)

**Comment by JeroenMols** [comment]
Hi @jake-long-game , thanks for filing a bug report.

Could you share some more information about your set up?

- Platform: Android/iOS/both
- OS version
- Link version
- Steps to reproduce

**Comment by JeroenMols** [comment]
Closing this issue as we haven't heard back in more than 30 days. Please feel free to reopen/file a new issue if your problem still persists.
