### ISSUE TITLE
Update Readme, add openLink dismissLink API, add Run Script doc from here: plaid.com/docs/link/ios/#manual

### ISSUE THREAD

**Issue by origamih** [plaid/react-native-plaid-link-sdk#128]
I can see the `openLink` and `dismissLink` by viewing the `index.js` file, but Readme has no where that talks about it.

Another thing is I got rejected when submit app to AppStore. Turns out there's a step needed during archiving app. And yet, Readme does not mention it.
plaid.com/docs/link/ios/#manual

**Comment by pladaub** [comment]
Hi, at the time this was posted there was a build phase script required (`prepare_for_distribution.sh`) mentioned in our documentation. New versions of the underlying LinkKit SDK (v2+) require the removal of this script.

I'll file an internal ticket to track the documentation improvement work, thank you for the suggestion!
