### ISSUE TITLE
Dark mode Link

### ISSUE THREAD

**Issue by alexandrasmith00** [plaid/react-native-plaid-link-sdk#131]
It would be helpful to have a configuration option to open the Link in dark mode, instead of the default (bright) white bg/color scheme.

**Comment by zsweigart** [comment]
Hi @alexandrasmith00 Thanks for the feedback.  Dark mode is not currently on our roadmap but  we will  take it into consideration

**Comment by mlyongardiner** [comment]
I would also love this!!

**Comment by alexwohlbruck** [comment]
^^ Dark mode option would be great. It is very jarring to go into the bright white screen from a previously all dark app.

**Comment by mayfairr** [comment]
++ (any update?)
