### ISSUE TITLE
Lexical or Preprocessor Issue - React/RCTDefines.h files not found

### ISSUE THREAD

**Issue by jayhxmo** [plaid/react-native-plaid-link-sdk#132]
Hi,
I'm using Plaid as part of my React Native project and ran across this issue while building.

![image](https://user-images.githubusercontent.com/14072008/82504254-e8514b80-9ac8-11ea-8be0-a6b13f27dcc1.png)

It seems that there's something wrong with the reference. I've followed manual linking instructions written on README.md to add RNLinksdk to Xcode, but I'm not sure where to approach from here.

Has anyone come across this issue for react-native-plaid-link-sdk?

**Comment by t4dek** [comment]
@jayhxmo have you fixed this one somehow?

**Comment by pladaub** [comment]
Does this issue still occur? If it does, please re-open with the following additional context:

1. What version of the `react-native-plaid-link-sdk` are you using?
2. What version of the `Plaid` cocoapod are you using?
3. What version of Xcode are you using?

Thanks!

**Comment by andrewheekin** [comment]
Still seeing this error in
1.  "react-native-plaid-link-sdk": "^7.0.6",
2.   pod 'Plaid', '~> 2.1.2'
3. XCode 12.5

@jayhxmo Were you able to find a fix for this?

**Comment by jayhxmo** [comment]
Nope, don't think so :(

**Comment by Dgdevesh** [comment]
@jayhxmo have you solved this issue. If yes so please share the solution here

**Comment by JJ810** [comment]
getting the same issue! @Dgdevesh were you able to resolve this issue?
