### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by chrisfisher** [plaid/react-native-plaid-link-sdk#14]
After following the readme instructions, I get the following error when running `pod install`:

```
[!] CocoaPods could not find compatible versions for pod "Plaid":
  In snapshot (Podfile.lock):
    Plaid (= 1.1.23)

  In Podfile:
    Plaid (~> 1.1.25)

    react-native-plaid-link-sdk (from `../node_modules/react-native-plaid-link-sdk`) was resolved to 1.0.2, which depends on
      Plaid

None of your spec sources contain a spec satisfying the dependencies: `Plaid (~> 1.1.25), Plaid (= 1.1.23), Plaid`.
```

My versions:
```
react-native: 0.61.4
cocoapods: 1.7.5
```

**Comment by JeffKGabriel** [comment]
I include both imports in my podfile to ensure plaid dependency is installed
```
pod 'Plaid', '~> 1.1.24'
pod 'react-native-plaid-link-sdk', :path => '../node_modules/react-native-plaid-link-sdk'
```

**Comment by chrisfisher** [comment]
@JeffKGabriel I still get the same error as above even if I include both imports.

**Comment by JeffKGabriel** [comment]
if you are still getting the podfile.lock error as `1.1.23`, have you tried deleting your podfile.lock and and updating your pod versions with `pod install --repo-update`

I am assuming here still the error is still being caused by having version `1.1.23`

**Comment by afh** [comment]
@JeffKGabriel Any chance you could use the current version of cocoapods, i.e. 1.8.4 and retry?
I was able to successfully follow the instructions in the README using cocapods 1.8.4 and react-native 0.61.5.

**Comment by chrisfisher** [comment]
@JeffKGabriel `pod install --repo-update` did the trick, thanks. Closing this issue.
