### ISSUE TITLE
Plaid doesn't return 'request_id' for Android, however it returns for iOS

### ISSUE THREAD

**Issue by ujjwalsayami** [plaid/react-native-plaid-link-sdk#140]
As we know the response for android and ios differ.
I'm not able to get/ find 'request_id for android. Is there
a way to get 'request_id' for android.
Any help would be appreciated

**Data for Android:**
{
  "link_connection_metadata": {
    "accounts": [[Object]],
    "institution_id": "ins_6",
    "institution_name": "US Bank",
    "link_session_id": "<link session ID>",
    "raw_data": {
      "account_id": "<account ID>",
      "account_mask": "0000",
      "account_name": "Plaid Checking",
      "account_subtype": "checking",
      "account_type": "depository",
      "accounts": "[{\"_id\":\"<account ID>\",\"balance\":{\"available\":100,\"currency\":\"USD\",\"current\":110,\"localized\":{\"available\":\"$100.00\",\"current\":\"$110.00\"}},\"meta\":{\"name\":\"Plaid Checking\",\"number\":\"0000\"},\"type\":\"depository\",\"subtype\":\"checking\"}]",
      "institution_id": "ins_6",
      "institution_name": "US Bank",
      "link_session_id": "<link session ID>",
      "public_token": "<public token>"
    }
  },
  "public_token": "<public token>"
}

**Data for iOS:**
{
  "account": {
    "id": "<account ID>",
    "mask": "0000",
    "name": "Plaid Checking",
    "subtype": "checking",
    "type": "depository"
  },
  "account_id": "<account ID>",
  "accounts": [
    {
      "id": "<account ID>",
      "mask": "0000",
      "name": "Plaid Checking",
      "subtype": "checking",
      "type": "depository"
    }
  ],
  "institution": {
    "institution_id": "ins_6",
    "name": "US Bank"
  },
  "link_session_id": "<link session ID>",
  "public_token": "<public token>",
  "**request_id**": "<request ID>",
  "**status**": "connected"
}

**Comment by zsweigart** [comment]
Hi @ujjwalsayami thanks for the feedback.  We noticed that the android side is returning the request id for exits but not for success.  We will update this in the next version.

**Comment by zsweigart** [comment]
hi @ujjwalsayami we have reviewed the api further and were wondering what your use case was for needing the request id in `onSuccess`?

**Comment by JeroenMols** [comment]
@ujjwalsayami could you please elaborate on your use case? That will enable us to make the right decision in our API design. Thank you

**Comment by ujjwalsayami** [comment]
yeah sure, I needed request_id param in Android side because `request_id` param is used to create support ticket but since android provides `link_session_id` I don't think we need to have request_id param for android. 
As Plaid doc says `link_session_id` says it can be used to create support ticket.

**Comment by JeroenMols** [comment]
Awesome, thanks for your update! Closing this ticket as no longer relevant.
