### ISSUE TITLE
Android crash onSuccess

### ISSUE THREAD

**Issue by Rick2003** [plaid/react-native-plaid-link-sdk#144]
SDK version 4.0.0
Android Core: 2.0.0

![image](https://user-images.githubusercontent.com/6007020/84791492-ae3c7200-afc0-11ea-904c-365d6ffaaaf6.png)

Crash after selected the bank account and try to link.  Crashed onSuccess,  React Native app would crash and restart it self.

**Comment by amytang0** [comment]
Hi Rick,

Thanks for the bug report, this has been patched in 4.0.1
