### ISSUE TITLE
Do not call destroy() when Link is open

### ISSUE THREAD

**Issue by Mperhats** [plaid/react-native-plaid-link-sdk#147]
I successfully integrated Link in my React app. Everything works as expected in the sandbox. When migrating into production, I entered my credentials and received the following error at the same time as onSuccess() callback. 

> 

link-initialize.js:1 Uncaught Error: Do not call destroy() when Link is open
    at Object.destroy (link-initialize.js:1)
    at Object.destroy (index.umd.js?5794:298)
    at Object.eval [as onExitCallback] (index.umd.js?5794:379)
    at Object.onExit (index.umd.js?5794:265)
    at Object.exit (link-initialize.js:1)
    at link-initialize.js:1

The code blocks that these messages correspond with are as such:
`    var destroy = function destroy() {
      if (!state.plaid) {
        return;
      }

      state.plaid.destroy(); //LINE 298 of index.umd.js
      state.plaid = null;
    };`

`   var config = renameKeyInObject(options, 'publicKey', 'key');
    state.plaid = window.Plaid.create(_objectSpread2({}, config, {
      onExit: function onExit() {
        config.onExit && config.onExit.apply(config, arguments);
        state.onExitCallback && state.onExitCallback(); // LINE 265 of  index.umd.js
      }
    }));`

and,

`      return function () {
        return next.exit({
          force: true
        }, function () {
          return next.destroy(); // LINKE 379 of index.umd.js
        });
      };`

I am using react-plaid-link@2.2.3 and saw the same issue with react-plaid-link@2.3.0-alpha.0. I have not seen these issues with Link integration on iOS so am wondering if this is a bug.

**Comment by zsweigart** [comment]
Hi @Mperhats This issue seems to be with the React Library and not the React Native Library.  If so, you can post an issue there https://github.com/plaid/react-plaid-link/issues.  If not could you provide the version of the React Native Library you are using and what OS you are seeing the crash on?
