### ISSUE TITLE
App crashes when onExit is not defined

### ISSUE THREAD

**Issue by steelbrain** [plaid/react-native-plaid-link-sdk#151]
The SDK never checks if `onExit` is undefined for the Android codepath: [link](https://github.com/plaid/react-native-plaid-link-sdk/blob/a868b4f7a3b4e6759e9757221e293b5437f708d1/PlaidLink.js#L11)

It does so for iOS: [link](https://github.com/plaid/react-native-plaid-link-sdk/blob/a868b4f7a3b4e6759e9757221e293b5437f708d1/PlaidLink.js#L17)

**Comment by JeroenMols** [comment]
Thanks for reporting, we've addressed this issue and will make this available in a new release in the coming 1 to 2 weeks.
