### ISSUE TITLE
Invalid Signature error after upgrading to React Native 0.62 / 0.63

### ISSUE THREAD

**Issue by eduardborges** [plaid/react-native-plaid-link-sdk#157]
When I try to validate the app for distribution with a newer React Native version than 0.61.5 I get the following error:

Invalid Signature. Code object is not signed at all. The file at path [{appName}.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

**Comment by afh** [comment]
Thanks for reporting @eduardborges it seems the following step as mentioned in the README.md is missing in your integration:

> Add a Run Script build phase (after the [CP] Embed Pods Frameworks step) to your target as described in [Plaid Link for iOS documentation](https://plaid.com/docs/link/ios/#add-run-script). This strips simulator symbols from App Store release builds.

Can you verify that you have setup the **Prepare for Distribution** Build Phase correctly?

**Comment by eduardborges** [comment]
That solved the problem. Thanks

**Comment by afh** [comment]
Glad to hear that this solved the issue for you; thanks for using Plaid!
