### ISSUE TITLE
PlaidLink component not displaying

### ISSUE THREAD

**Issue by alexlod** [plaid/react-native-plaid-link-sdk#16]
I've followed the documentation and have an iOS simulator running with Expo. The `PlaidLink` component is not displaying despite other components on the same screen being displayed.

I see no errors or warnings. Using `react-devtools`, I see the `PlaidLink` component in the hierarchy along with its various child components, eg `TouchableOpacity`.

I'm using version `2.0.0`.

Any ideas why nothing is being displayed? Thanks!

**Comment by alexlod** [comment]
Some progress:

With version `1.0.2`, the initial button is displayed. However, upon clicking it, I get the following error:

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNLinksdk.create')]
- node_modules/react-native-plaid-link-sdk/PlaidLink.js:28:28 in openLink$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- ... 35 more stack frames from framework internals
```

**Comment by alexlod** [comment]
I submitted a PR to address the errors in `README.md`. However, the PR doesn't fix all my issues. Now, when I click the button, nothing happens. Looking at `PlaidLink.js`, `openLink` should be getting called... I don't know enough about iOS to debug this thoroughly but I'm doing my best.

**Comment by kanji-keraliya** [comment]
Does anyone find solution. Nothing showing for me. I tried to add component as button but onPress nothing happen.

**Comment by alexlod** [comment]
@kanji-keraliya after experimenting a lot and trying older versions also with no success, I started using https://github.com/catalinmiron/react-native-plaid-link instead.

**Comment by wkiefer** [comment]
I'm sorry you're having trouble @alexlod and @kanji-keraliya — what version of react-native are you using?

Is there any log output from when you tap the open button?

**Comment by wkiefer** [comment]
Oh, and I realized that the docs don't have a child `Text` element for the default `TouchableOpacity` component. I'll comment in your PR to fix that, but it is likely why you didn't see anything earlier.

**Comment by mkimsing** [comment]
I've been experiencing the same issue, testing on android. Our project is using react-native 0.61.2 but I also made a fresh react-native project as a sanity check which had version 0.61.5. Had the issue on both the projects.

I passed a button in as a prop as suggested in the PR which displays the button. When I tap the button in the JS console there is no output, in the LogCat there is just:
```
D/ViewRootImpl@5e4496e[MainActivity]: ViewPostIme pointer 0
D/ViewRootImpl@5e4496e[MainActivity]: ViewPostIme pointer 1
```

**Comment by alexlod** [comment]
@wkiefer: thanks for responding and helping us with this!

I'm using Expo's fork of React, version 35.0.0. My `package.json` file uses `https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz`.

I'm new to React Native, so I went with Expo per the [official getting started guide](https://facebook.github.io/react-native/docs/getting-started).

When I click the `Button` I created in the `component` prop, nothing happens. It's as though the `onPress` prop in `PlaidLink.js` does nothing. As such, I experimented with a fork... I modified `PlaidLink.js` to include a `Button`, see https://github.com/alexlod/react-native-plaid-link-sdk/commit/c1a0d5f0533258bdcb5928720580b63dbf2aa8f2. Then when I clicked the `Button`, I got an Objective C error from `RNLinksdk.m`'s `create` method... something about null not being a valid value. I could reproduce it to get you an exact error if you'd like. Right now I don't have time to get it, though.

Finally, I'll respond to the PR as well. Thanks again @wkiefer!

**Comment by kanji-keraliya** [comment]
@wkiefer  Can anyone share a working example or update readme file, Its help us a lots

**Comment by osikes** [comment]
Running into same issue, the v1.0.2 worked fine. But 2.0.0 + nothing displays as link for iOS.....

**Comment by zachrnolan** [comment]
Also experiencing this. Can't seem to get Plaid Link to open anymore.

**Comment by osikes** [comment]
Okay... so what does work. Is create your own button/touchableopacity,etc and pass into the PlaidLink as 'component' prop.

<PlaidLink
component = {()=><TouchableOpacity onPress={yourCustomCallback}>...</TouchableOpacity>}
.../>

Then for the onPress make a call to 'openLink' (passing in all your props as json object) from 'react-native-plaid-link-sdk' . That seems to work.. but documentation is lacking there.

const yourCustomCallback = useCallback(()=> { openLink({env, product, etc }) ....

**Comment by wkiefer** [comment]
Apologies for the trouble — we have a fix incoming for this very shortly.

**Comment by wkiefer** [comment]
Thanks everyone! v2.0.3 is now available on NPM and fixes this issue.

I've also updated the readme to show using the default `TouchableOpacity` as well as using a custom component with custom props:
https://www.npmjs.com/package/react-native-plaid-link-sdk

**Comment by devika7** [comment]
> Okay... so what does work. Is create your own button/touchableopacity,etc and pass into the PlaidLink as 'component' prop.
> 
> ```
> <PlaidLink
> component = {()=><TouchableOpacity onPress={yourCustomCallback}>...</TouchableOpacity>}
> .../>
> ```
> 
> Then for the onPress make a call to 'openLink' (passing in all your props as json object) from 'react-native-plaid-link-sdk' . That seems to work.. but documentation is lacking there.
> 
> const yourCustomCallback = useCallback(()=> { openLink({env, product, etc }) ....

Hi, could you please elaborate on how to go about it? I am facing the same issue and somehow can't display the Plaidlink component at all.

**Comment by wkiefer** [comment]
There is an example here @devika7 👍 https://github.com/plaid/react-native-plaid-link-sdk#customizing-the-plaidlink-component
