### ISSUE TITLE
In Android, There is an issue while app become foreground from background

### ISSUE THREAD

**Issue by FoundersApproach** [plaid/react-native-plaid-link-sdk#167]
Hello, I am facing an issue in Android.

Plaid view automatically dismissed once user put app background and come back to foreground. 
Please see attached video.

Thank you.
[Plaid_Android_background_forground_issue.mov.zip](https://github.com/plaid/react-native-plaid-link-sdk/files/5028825/Plaid_Android_background_forground_issue.mov.zip)

**Comment by amytang0** [comment]
Hi, to double-check, are you using Do Not Keep Activities mode?

**Comment by FoundersApproach** [comment]
Hello Thanks for your replay. 

I am not sure about Do Not Keep Activities mode. Would you please guide me about how to disable it to keep Plaid active even if user go background and come again foreground.

Thank you.

**Comment by FoundersApproach** [comment]
Hello @amytang0 Would please help me ?
Thank you.

**Comment by FoundersApproach** [comment]
I fix issue by adding `android:launchMode="singleTop"` to my main Activity in android manifest file.
Thank you.
