### ISSUE TITLE
iOS is working but in Android, I am getting network error.

### ISSUE THREAD

**Issue by superhero2007** [plaid/react-native-plaid-link-sdk#168]
- package.json
"react-native": "0.61.4",
"react-native-plaid-link-sdk": "3.1.2",

- app/build.gradle
implementation project(':react-native-plaid-link-sdk')
implementation 'com.plaid.link:sdk-core:1.0.0'

- Error
 {"display_message": "Internal exception occurred", "error_code": "499", "error_message": "[com.plaid.link.networking.NetworkLostWorker.a(SourceFile:3), com.plaid.link.networking.NetworkLostWorker.doWork(SourceFile:2), androidx.work.Worker$1.run(Worker.java:85), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607), java.lang.Thread.run(Thread.java:761)]", "error_type": "No network is available.  Network connection is required to use Link.", "link_exit_metadata": {}}

**Comment by superhero2007** [comment]
- android/settings.gradle
include ':react-native-plaid-link-sdk'
project(':react-native-plaid-link-sdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-plaid-link-sdk/android')

-MainApplication.java

import com.plaid.PlaidPackage;

 @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          packages.add(new PlaidPackage());
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

<PlaidLink
              clientName="Pocket Planner"
              publicKey={PLAID_PUBLIC_KEY}
              env={SANDBOX}
              onSuccess={handlePlaidSuccess}
              onExit={handleExit}
              product={['transactions']}
              language="en"
              countryCodes={['US']}>
              <View>
                <Text>Add account</Text>
              </View>
            </PlaidLink>

**Comment by zsweigart** [comment]
Hi @superhero2007 
This error is returned if your device does not have internet connection when opening link.  Can you please check that your device has network connectivity? Also can you check in your AndroidManifest that you have an internet permission line
```
    <uses-permission android:name="android.permission.INTERNET" />
```

Finally, it looks like you're on an old version, we recommend that you update to `"react-native-plaid-link-sdk": "5.0.0"` and `implementation 'com.plaid.link:sdk-core:2.0.0'`

**Comment by zsweigart** [comment]
Closing this as it seems to be resolved.  Please reopen if the issue persists.
