### ISSUE TITLE
Android: android package name must be configured in the developer dashboard

### ISSUE THREAD

**Issue by venkat-waran** [plaid/react-native-plaid-link-sdk#169]
Hi,

I am getting an error in the Android Platform but react-native-plaid-link-sdk is working fine in IOS

Error:

**{"metadata":{},"error":{"error_type":"INVALID_REQUEST","error_message":"Android package name must be configured in the developer dashboard. See https://plaid.com/docs/link/android/#register-app-id","error_code":"INVALID_FIELD","display_message":""}}**

**But I have configured the android package name in the Plaid dashboard**.

 <PlaidLink
        env="sandbox"
        clientName="App Name"
        token={plaidLinkToken}
        onSuccess={(data) => handlePlaidSuccess(data)}
        onExit={(data) => console.log(JSON.stringify(data))}
        product={['auth', 'transactions']}
   />

**Package Versions**

 "react-native": "0.62.2",
 "react-native-plaid-link-sdk": "^5.0.0",

**android/app/build.gradle**
implementation project(':react-native-plaid-link-sdk')
implementation "com.plaid.link:sdk-core:2.1.2"
implementation "com.squareup.okhttp3:okhttp-urlconnection:4.+"

**ios/Podfile**
pod 'Plaid', '~> 1.1.34'

**Comment by zsweigart** [comment]
Hi @venkat-waran 
Your package name is found in your AndroidManifest file
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="<YOUR PACKAGE NAME>">
```

Then you'll want to follow these instructions to set that value on your dashboard
https://plaid.com/docs/link/android/#register-app-id

It'll look something like this
<img width="1072" alt="Screen Shot 2020-08-17 at 3 22 12 PM" src="https://user-images.githubusercontent.com/1391816/90449994-3537c480-e0ae-11ea-8cec-c3bc05f0c47b.png">

**Comment by zsweigart** [comment]
Closing this as it seems to be resolved.  Please reopen if the issue persists.

**Comment by SravanthiGujjula** [comment]
Hi, 
I added the package name in Plaid dashboard. I am still getting this error in android. 

 {"error": {"displayMessage": "", "errorCode": "INVALID_FIELD", "errorMessage": "Android package name must be configured in the developer dashboard. See https://plaid.com/docs/link/android/#register-your-app-id"}, "metadata": {}}

**Comment by amytang0** [comment]
Are you sure you are creating the link token with the correct client_id and secret? Many companies have multiple Plaid accounts and don't necessarily add the package name to the correct clients
