### ISSUE TITLE
Plaid link doesn't open on Android

### ISSUE THREAD

**Issue by tmaciej** [plaid/react-native-plaid-link-sdk#172]
Hello,

I have trouble with integrating this library on Android. I followed all steps from the README (edited all necessary files, added package id in Plaid dashboard) yet nothing happens when I press the link, no errors or other messages are shown either in logcat or React Native debugger. When I've added `onPress` callback to the component props I can see that the event / callback is called. The same setup works fine for me on iOS.

Here are library / sdk versions I am using:

```json
// package.json
{
  "dependencies": {
    "react-native-plaid-link-sdk": "^5.0.0",
  }
}
```

```gradle
dependencies {
    implementation project(':react-native-plaid-link-sdk')
    implementation 'com.plaid.link:sdk-core:2.2.0'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.8.1'
}
```

Am i missing something?

**Comment by zsweigart** [comment]
Hi @tmaciej could you please post your `MainApplication`'s `getPackages()` method and your `PlaidLink` configuration (don't forget to omit your keys).  Thanks

**Comment by tmaciej** [comment]
@zsweigart 

Here is `getPackages` method:

```java
    @Override
    protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new PlaidPackage());
      return packages;
    }
```

and here's my `PlaidLink` configuration:

```tsx
<PlaidLink
  env="sandbox"
  onSuccess={handleSuccess}
  product={['transactions']}
  publicKey={data.public_key}
  webhook={data.webhook}
>
  {children}
</PlaidLink>
```

`webhook` and `publicKey` values comes from our API but are valid (work in case of iOS)

**Comment by zsweigart** [comment]
Hi @tmaciej it looks like you  are missing `clientName` which is a required property https://github.com/plaid/react-native-plaid-link-sdk/blob/master/PlaidLink.js#L79-L123

**Comment by tmaciej** [comment]
@zsweigart That fixed it. Thank you.

I was confused because I was looking exactly at the piece of code you pasted and at this line 86 it says https://github.com/plaid/react-native-plaid-link-sdk/blob/5f842f92dda605648e2a52bbd51dbf77810a500d/PlaidLink.js#L86

and prop `clientName` is below that line. Also it's not marked as required.

I noticed that using `publicKey`  instead of link token is deprecated but I believe adding an example of using `publicKey` to README could be a good idea to help with issues like mine.

Anyway thank you once again for the help!
