### ISSUE TITLE
Upgrade notes from 4.x to 5.x

### ISSUE THREAD

**Issue by nchase** [plaid/react-native-plaid-link-sdk#175]
Looks like the [upgrade notes](https://github.com/plaid/react-native-plaid-link-sdk/tree/master/upgrade_notes) for major versions don't include any path from 4.x to 5.x – are we missing something?

**Comment by amytang0** [comment]
Hi nchase, thanks for the flag! 
We are working on those docs now, but in the meantime, the main difference between 4.x to 5.x is the one-time [Link token](https://plaid.com/docs/upgrade-to-link-tokens/) support.

**Comment by zsweigart** [comment]
PR up for adding a note https://github.com/plaid/react-native-plaid-link-sdk/pull/180/files
