### ISSUE TITLE
Updating Items via Plaid Link

### ISSUE THREAD

**Issue by gb9box** [plaid/react-native-plaid-link-sdk#176]
Hello, I think there is an issue for the [Updating Items via Plaid Link](https://support.plaid.com/hc/en-us/articles/360010529653-Updating-Items-via-Plaid-Link) in [update mode](https://plaid.com/docs/#updating-items-via-link).

They require `token` field only for either create or update mode in `Plaid.create` function. Your code is working as well for the create Plaid link. But there is an issue in update mode.

I found an issue in your code for iOS version as following:
```
// line 104 in RNLinksdk.m file

BOOL isUsingLinkToken = [linkTokenInput length] > 0 && [linkTokenInput hasPrefix:kRNLinkKitLinkTokenPrefix];
```

I think it doesn't need to check the link token prefix in your code(it allows link token only to create one like as "link-xxx").
BTW, In order to follow the guide "Updating Items via Plaid link", they return a new temporary public_token for the update mode on the server-side. and this public_token(like as "public_production_xxx) will use as a `token` to the open Plaid link view on the client-side.
(Same issue in the Android version too)

Does make sense what I mean?

There are 2 solutions that I'd like to recommend:
1. remove the link token prefix checking:
```
BOOL isUsingLinkToken = [linkTokenInput length] > 0;
```

2. add another one for the public_token to the update mode:
```
BOOL isUsingLinkToken = [linkTokenInput length] > 0 && ([linkTokenInput hasPrefix:kRNLinkKitLinkTokenPrefix] || [linkTokenInput hasPrefix:kRNLinkKitPublicTokenPrefix]);
// hasPrefix:kRNLinkKitPublicTokenPrefix = "public-"; 
```

Hopefully, this would help you in the next release and fix it as soon as possible.
Thank you.

**Comment by amytang0** [comment]
Hi, what issue are you running into with update mode?
[Link Token](https://plaid.com/docs/#create-link-token) is our new one-time key that will replace `public_key`, which will specifically have the prefix `link`.
The public_token you mentioned is distinct from link_token.

**Comment by gb9box** [comment]
Hi @amytang0 
They require `token` value as a `public_token` instead of `link_token` for the `update mode`. 
Check this one [update mode](https://plaid.com/docs/#updating-items-via-link).

So, for the update mode, the `token` value would be `public-xxx-xxx`.

**Comment by amytang0** [comment]
Yes, is the behavior not working as expected though? On my end, I am able to update items as usual by passing `token = "public-sandbox-<X>"`

**Comment by gb9box** [comment]
No, it's not working as expected with the current codebase now.
And the `public_token` value would be one of three values 
`public-sandbox-XXX`, `public-development-XXX`, `public-production-XXX`.

**Comment by amytang0** [comment]
What is the behavior you are seeing? (Video would be appreciated)

**Comment by gb9box** [comment]
Your codebase is working as well for the `create-link-token`.
But, there is an issue when I trying to take `update mode` as I mentioned.

```
// this is the open link codebase for the update mode.
const params = {
      token: data.public_token, // public-production-xxx comes from the server
      onSuccess: this.onSuccessPlaidUpdateAuth,
      onExit: this.onExitPlaidUpdateAuth,
    }
    openLink(params)
```
In this case, it gives me an error as following:
![IMG_0111](https://user-images.githubusercontent.com/48032825/92516084-53ac5e00-f21d-11ea-80d0-44c8160f196c.png)

In my debugging your code, I found the issue in the line 104 from `RNLinksdk.m` file. (Same as Android version too).

So, I just would like to recommend fixing this issue with 2 ways as above.

**Comment by amytang0** [comment]
Hi, thanks for the flag. v5.0.2 should support update mode, let me know if you have any issues!

**Comment by gb9box** [comment]
Looks good. I'm going to close this issue.
Thank you!
