### ISSUE TITLE
Showing blank screen on iOS 14

### ISSUE THREAD

**Issue by SubhashisPK** [plaid/react-native-plaid-link-sdk#186]
# The problem

Plaid SDK for React Native iOS is working fine for below iOS 14, but on iOS 14 it's showing blank screen.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 5.0.2                |
| ReactNative Version     |  0.61.5                |
| Occurs on Android             | no                |
| Occurs on iOS     | yes                |
| iOS Version           | 14               |
| iOS Device              | Iphone 11 Pro Max     |

Need help urgent.

**Comment by SubhashisPK** [comment]
The issue was not related to iOS 14.

**Comment by EQuimper** [comment]
@SubhashisPK what was the issue ? I have the same problem right now
