### ISSUE TITLE
When I try to make a release build i get an error

### ISSUE THREAD

**Issue by skheirandish** [plaid/react-native-plaid-link-sdk#187]
I have setup this library for a react-native project. I used Cocoapods to install this library and I added the [script](https://plaid.com/docs/link/ios/#add-run-script) to my build scripts. The script runs because when Fastlane fails I can go in the logs and see the logs from script there.

This is the error I get. Any help is appreciated:
```
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -o /var/folders/3j/xvdr39x53xnbh60r_3p_z6l40000gp/T/ipatool20200925-17531-vslzu1/thinned-out/arm64/Payload/app.app/Frameworks/LinkKit.framework/LinkKit --generate-dsym /var/folders/3j/xvdr39x53xnbh60r_3p_z6l40000gp/T/ipatool20200925-17531-vslzu1/thinned-out/arm64/Payload/app.app/Frameworks/LinkKit.framework/LinkKit.dSYM --strip-swift-symbols /var/folders/3j/xvdr39x53xnbh60r_3p_z6l40000gp/T/ipatool20200925-17531-vslzu1/thinned-in/arm64/Payload/app.app/Frameworks/LinkKit.framework/LinkKit
Status: pid 19077 exit 1
Stdout:
    Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/
```

Also I needed to change the path in your docs to this:

```
LINK_ROOT=${PODS_ROOT:+$PODS_ROOT/Plaid}
```

because the ios subfolder didnt exist.

**Comment by afh** [comment]
Hello @skheirandish, thanks for using Plaid Link and reaching out.
With the latest version of Plaid Link SDK the custom Build Phase script is no longer necessary, since we switched to XCFramework for binary distribution, making the need to strip iOS Simulator symbols prior to distribution unnecessary.

Please revisit the [updated documentation](https://plaid.com/docs/link/ios/#add-run-script) and especially the [migration guide](https://plaid.com/docs/link/ios/ios-v2-migration/).

**Comment by skheirandish** [comment]
Hi @afh I did follow the guide but the problem still remains. Our React Native app `v.62.2` uses Autolinking and I followed the steps in here: https://plaid.com/docs/link/react-native/ios-setup/#ios-setup simply added the latest version of "react-native-plaid-link-sdk": "6.0.2" and on my pod file i added pod 'Plaid', '~> 2.0.3' made sure all old packages are removed and reinstalled for npm and pod. Simply archived the app and noticed if i follow [this advice](https://stackoverflow.com/questions/56748389/ipatool-failed-with-an-exception-xcode-10-1) on stackoverflow i can get passed the error im getting 

![error-after-archive](https://user-images.githubusercontent.com/66039460/96192386-c8e51000-0efa-11eb-9d7e-a6ef936ea4bb.jpg)

Also noticed that Linkit framework doesnt need a profile which was interesting to me:
![no-profile](https://user-images.githubusercontent.com/66039460/96192383-c71b4c80-0efa-11eb-80af-dec8309ed2ad.jpg)

So for our release build using Fastlane I tried to change my **gym** file and added the tag `include_bitcode: false` but it didnt work. However i dont think turning off bitcode is the correct approach anyway.

You you kindly let me know what have I missed? Thanks

**Comment by afh** [comment]
Hi @skheirandish,
unfortunately I have not been able to reproduce the issue that you are observing with our internal test application, maybe you can help me understand your setup better.

Can you double check that LinkKit 2.x is actually being used, e.g. by running the following commands in your project's top-level directory:
```
% find . -path '*LinkKit.framework/Info.plist'|pbcopy; pbpaste; pbpaste|xargs -n1 /usr/libexec/PlistBuddy  -c 'Print CFBundleSupportedPlatforms' -c 'Print CFBundleShortVersionString' -c 'Print CFBundleVersion'
./ios/Pods/Plaid/LinkKit.xcframework/ios-x86_64-simulator/LinkKit.framework/Info.plist
./ios/Pods/Plaid/LinkKit.xcframework/ios-arm64/LinkKit.framework/Info.plist
Array {
    iPhoneSimulator
}
2.0.3
1073.1
Array {
    iPhoneOS
}
2.0.3
1073.1
```


FYI: I took the liberty edit your comment and redact the application name from the second screenshot.

**Comment by skheirandish** [comment]
Thank you!! Yeah, the output I get is as exactly the same as yours
```
./ios/Pods/Plaid/LinkKit.xcframework/ios-x86_64-simulator/LinkKit.framework/Info.plist
./ios/Pods/Plaid/LinkKit.xcframework/ios-arm64/LinkKit.framework/Info.plist
Array {
    iPhoneSimulator
}
2.0.3
1073.1
Array {
    iPhoneOS
}
2.0.3
1073.1
```

**Comment by skheirandish** [comment]
Ok so I updated my Xcode to 11.7 and the problem disappeared.
