### ISSUE TITLE
iOS - Running Pod install removes build step "[CP] Embed Pods Frameworks"

### ISSUE THREAD

**Issue by Raymond-Cox** [plaid/react-native-plaid-link-sdk#190]
# The problem
Similar problem to https://github.com/plaid/react-native-plaid-link-sdk/issues/4
I read through and tried every suggestion from that issue, seems somewhat unrelated.
I've used this library for months now without any problem or changes. Randomly now I'm running into the `LinkKit/LinkKit.h file not found` issue.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 3.1.2               |
| ReactNative Version     |  0.61.5                |
| Occurs on Android             | N/A               |
| Android OS Version                    | N/A                |
| Android Devices/Emulators    | N/A               |
| Occurs on iOS     | Yes                |
| iOS Version           | 11-14               |
| iOS Devices/Emulators               | iPhone X                |

# Steps to Reproduce

I've encountered this same issue across the same project even after upgrading to React-Native 0.63.3. I've also upgraded the `react-native-plaid-link-sdk` to version 5.0.2. Same issue persists. 

In the past I've always used the following in my pods:
`pod 'Plaid'`
I've also tried the following as suggested in the installation guide, to the same result:
`pod 'Plaid', '~> 2.0.0'`

# Code To Reproduce Issue 
Here's my entire podfile:
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'vaultzap57' do
  # Pods for vaultzap57
  # Default standard RN pods
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Additional pods we've added

  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'
  pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true
  pod 'Plaid', '~> 2.0.0'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  use_native_modules!
end
```

Here's sourcetree outlining the xcode.proj file. Notice the Embed frameworks change after running Pod Install:

<img width="857" alt="Screen Shot 2020-09-30 at 10 15 09 AM" src="https://user-images.githubusercontent.com/33842042/94697232-f2e8e080-0305-11eb-8ed0-9a490525a31e.png">

**Comment by all9lives** [comment]
The same thing is happening for us. 

We're upgrading Plaid Link to support link tokens, and running into the `LinkKit/LinkKit.h` file not found issue too. 

- Plaid Pod: `2.0.1`
- react-native-plaid-link-sdk: `^6.0.2-rc2`,

I've tried downgrading to `2.0.1` and `1.1.37` without any luck and tried `react-native-plaid-link-sdk`: `6.0.0`. 

Interestingly, our `project.pbxproj` diff doesn't remove `[CP] Embed Pods Frameworks` but does explicitly remove the LinkKit Framework. But putting those lines back in make no difference because those files aren't there. 
 
![Image 2020-10-05 20-37-05](https://user-images.githubusercontent.com/1470953/95063793-8bd68c00-074a-11eb-9a00-d0f5524ce37c.jpg)

**Comment by jake-long-game** [comment]
I made a comment for the other PR, but it's closed, so I'll move it here

https://github.com/plaid/react-native-plaid-link-sdk/issues/4#issuecomment-704581105

**Comment by ealmiladi** [comment]
@all9lives @jake-long-game Are you on Xcode 12? Ran into this until I upgraded to xcode 12.

**Comment by all9lives** [comment]
@ealmiladi I'm running xcode `12.0.1`. 

> @all9lives @jake-long-game Are you on Xcode 12? Ran into this until I upgraded to xcode 12.


I'm making some progress after upgrading cocoa pods from `1.8.4` to `1.9.3`but was still getting issues. 

### Related LinkKit Error

```
cp: /Users/jeremy/MEGA/git/jointly/jtly-react-native/ios/Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
/Users/jeremy/Library/Developer/Xcode/DerivedData/awesomeapp-arvtrqksqbodxfbxpxokkavwtldz/Build/Intermediates.noindex/awesomeapp.build/Debug-iphonesimulator/awesomeapp.build/Script-3FCCCF8E24B43A6E00774838.sh: line 5: /Users/jeremy/Library/Developer/Xcode/DerivedData/awesomeapp-arvtrqksqbodxfbxpxokkavwtldz/Build/Products/Debug-iphonesimulator/awesomeapp.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

This is coming from the **Prepare for distribution** build phase.
![jtlyapp xcodeproj 2020-10-08 11-36-10](https://user-images.githubusercontent.com/1470953/95402167-bbf47980-095a-11eb-8a06-38969d32784e.jpg)

### Some success
I was at least able to get it to build for the simulator by **Checking the `For install builds only` Box**

![jtlyapp xcodeproj 2020-10-08 12-05-26](https://user-images.githubusercontent.com/1470953/95403661-94071500-095e-11eb-8049-456b5d457570.jpg)

**Comment by ealmiladi** [comment]
> @ealmiladi I'm running xcode `12.0.1`.
> 
> > @all9lives @jake-long-game Are you on Xcode 12? Ran into this until I upgraded to xcode 12.
> 
> I'm making some progress after upgrading cocoa pods from `1.8.4` to `1.9.3`but was still getting issues.
> 
> ### Related LinkKit Error
> ```
> cp: /Users/jeremy/MEGA/git/jointly/jtly-react-native/ios/Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
> /Users/jeremy/Library/Developer/Xcode/DerivedData/awesomeapp-arvtrqksqbodxfbxpxokkavwtldz/Build/Intermediates.noindex/awesomeapp.build/Debug-iphonesimulator/awesomeapp.build/Script-3FCCCF8E24B43A6E00774838.sh: line 5: /Users/jeremy/Library/Developer/Xcode/DerivedData/awesomeapp-arvtrqksqbodxfbxpxokkavwtldz/Build/Products/Debug-iphonesimulator/awesomeapp.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> This is coming from the **Prepare for distribution** build phase.
> ![jtlyapp xcodeproj 2020-10-08 11-36-10](https://user-images.githubusercontent.com/1470953/95402167-bbf47980-095a-11eb-8a06-38969d32784e.jpg)
> 
> ### Some success
> I was at least able to get it to build for the simulator by **Checking the `For install builds only` Box**
> 
> ![jtlyapp xcodeproj 2020-10-08 12-05-26](https://user-images.githubusercontent.com/1470953/95403661-94071500-095e-11eb-8049-456b5d457570.jpg)

So, I'm unsure as to whether Xcode version has any bearing on this, but I can absolutely confirm that upgrading CocoaPods resolved this LinkKit issue for me. Thank you so much for that suggestion, I spent all day yesterday trying to get this to work.

**Comment by mcgaryes** [comment]
I am also seeing this issue. But following the 1.x to 2.x migration steps the "Prepare for Distribution" is no longer needed due to the move to an .xcframework over a .framework.

**Comment by satish24787** [comment]
@ealmiladi - I tried embedding the .xcframework that is contained within the pod. However, I am still finding the LinkKit/LinkKit.h file not found issue.

**Comment by ealmiladi** [comment]
> @ealmiladi - I tried embedding the .xcframework that is contained within the pod. However, I am still finding the LinkKit/LinkKit.h file not found issue.

Have you tried upgrading CocoaPods? Make sure you're on the latest version of Xcode as well.

**Comment by satish24787** [comment]
> > @ealmiladi - I tried embedding the .xcframework that is contained within the pod. However, I am still finding the LinkKit/LinkKit.h file not found issue.
> 
> Have you tried upgrading CocoaPods? Make sure you're on the latest version of Xcode as well.

We have tried with the latest version as mentioned below,

Xcode Version: 12.1
react-native: 0.62.0

Followed the auto-linking steps as mentioned at https://plaid.com/docs/link/react-native/ios-setup/

pod 'Plaid', '~> 2.0.1'
(cd ios && pod install)

Its still throwing the error "LinkKit/LinkKit.h file not found".

**Comment by ealmiladi** [comment]
> > > @ealmiladi - I tried embedding the .xcframework that is contained within the pod. However, I am still finding the LinkKit/LinkKit.h file not found issue.
> > 
> > 
> > Have you tried upgrading CocoaPods? Make sure you're on the latest version of Xcode as well.
> 
> We have tried with the latest version as mentioned below,
> 
> Xcode Version: 12.1
> react-native: 0.62.0
> 
> Followed the auto-linking steps as mentioned at https://plaid.com/docs/link/react-native/ios-setup/
> 
> pod 'Plaid', '~> 2.0.1'
> (cd ios && pod install)
> 
> Its still throwing the error "LinkKit/LinkKit.h file not found".

Again, upgrading CocoaPods resolved the issue for me. What version of CocoaPods are you on?

**Comment by satish24787** [comment]
> > > > @ealmiladi - I tried embedding the .xcframework that is contained within the pod. However, I am still finding the LinkKit/LinkKit.h file not found issue.
> > > 
> > > 
> > > Have you tried upgrading CocoaPods? Make sure you're on the latest version of Xcode as well.
> > 
> > 
> > We have tried with the latest version as mentioned below,
> > Xcode Version: 12.1
> > react-native: 0.62.0
> > Followed the auto-linking steps as mentioned at https://plaid.com/docs/link/react-native/ios-setup/
> > pod 'Plaid', '~> 2.0.1'
> > (cd ios && pod install)
> > Its still throwing the error "LinkKit/LinkKit.h file not found".
> 
> Did you try upgrading to the latest version of CocoaPods as well?

Thank you @ealmiladi. It worked with the latest version of CocoaPods. However, when I am opening the PlaidLink in iOS, getting the below error,

Unbalanced calls to begin/end appearance transitions for <LinkKit.InProcessWebviewFallbackController: 0x7ffd32c2e7a0>.

We have configured redirect_uri on the portal and added while creating link-token. 

May i know have you come across this issue anytime before.

**Comment by remlostime** [comment]
![image](https://user-images.githubusercontent.com/3702498/100524133-6d997500-316a-11eb-9be9-49d2145271bc.png)

@ealmiladi I have the latest pod and Xcode. I also `import LinkKit` in the file, but still get this error. Any thoughts?

**Comment by ShaharyarMaroof** [comment]
I'm also getting the following error `/Pods/Plaid/LinkKit.framework/prepare_for_distribution.sh: No such file or directory`. I've enabled the check for `run for install builds only` but now the plaid link does not open in the simulator. Any ideas what the actual issue is?
```
react-native: 0.63.4
react-native-plaid-link-sdk: 6.0.4
ios-plaid-sdk: 2.0.9
```

**Comment by Zestpond** [comment]
Same issue,

**Comment by pladaub** [comment]
Hi,

> I'm also getting the following error `/Pods/Plaid/LinkKit.framework/prepare_for_distribution.sh: No such file or directory`. I've enabled the check for `run for install builds only` but now the plaid link does not open in the simulator or real device. Any ideas what the actual issue is?
> 
> ```
> react-native: 0.63.4
> react-native-plaid-link-sdk: 6.0.4
> ios-plaid-sdk: 2.0.9
> XCode 12.2
> ```

The `prepare_for_distribution.sh` build phase must be removed for LinkKit iOS v2 or higher

**Comment by pladaub** [comment]
There are several issues at play in this thread:

1. In September 2020 we released LinkKit v2, which is incompatible with RN v5. In order to use RN v6, or LinkKit v2, you have to use both. Using RN v5 with LinkKit v2 is not possible.

2. The `prepare_for_distribution.sh` is a requirement from how LinkKit v1 was distributed, and has to be removed for LinkKit v2 integrations (i.e. for RN v6 or higher).

If I missed another issue in this thread, feel free to reopen with more context. Thanks!
