### ISSUE TITLE
Request to update peer package's peer dependency indications

### ISSUE THREAD

**Issue by prometheas** [plaid/react-native-plaid-link-sdk#192]
I've just installed the package to my project that builds against `react-native@0.63.2` and received the following npm warning:

```
npm WARN react-native-plaid-link-sdk@5.0.2 requires a peer of react-native@^0.61.3 but none is installed. You must install peer dependencies yourself.
```

I may be able to carve out bandwidth in the next week or two to attempt a PR, but I wanted to call your attention to it, as `react-native` has advanced by two releases since this package's peer dependencies have been set.

**Comment by JeroenMols** [comment]
Thanks for bringing this to our attention!

We've updated the peer dependency of RN in our latest RN SDK version `7.0.0-rc2` and higher.
https://github.com/plaid/react-native-plaid-link-sdk/blob/3ad36fedb79cab6ffaaf89cbc720b4485c95bf7e/package.json#L54
