### ISSUE TITLE
Problem with RNLinksdk.o when compiling on iOS

### ISSUE THREAD

**Issue by juanvargasagama** [plaid/react-native-plaid-link-sdk#193]
Hi there,

We are trying to implement Plaid using the React Native SDK on iOS but we are having several troubles. We followed the instructions, modified the Podfile, saw different threads in here and we could not find any clue. 

This is the content of my Podfile:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'micc' do
  config = use_native_modules!

  pod 'Plaid', '~> 2.0.0'
  use_react_native!(:path => config["reactNativePath"])

  target 'miccTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'micc-tvOS' do
  # Pods for micc-tvOS

  target 'micc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
```

And after digging and resolving previous issues, I am getting this error:

_CompileC /Users/juanvargas/Library/Developer/Xcode/DerivedData/micc-azlttvmgrvrutoeuofixvosifoxk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-plaid-link-sdk.build/Objects-normal/x86_64/RNLinksdk.o /Users/juanvargas/Documents/Desarrollo/Agama/micc/micc-app/node_modules/react-native-plaid-link-sdk/ios/RNLinksdk.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)_

Any help will be really appreciated!

Thanks,
Juan

**Comment by amytang0** [comment]
Hi, if you're using RN 6.0.1+, you'll need to [update to at least 11.0](https://plaid.com/docs/link/react-native/react-native-v6-migration/#update-ios-versions)
`platform :ios, '11.0'`
