### ISSUE TITLE
property 'linkCustomizationName' not found on object of type 'PLKConfiguration *

### ISSUE THREAD

**Issue by zachrnolan** [plaid/react-native-plaid-link-sdk#20]
react-native-plaid-link-sdk: `2.0.1`
react-native: `0.61.4`

Receiving the following error when building iOS:

`node_modules/react-native-plaid-link-sdk/ios/RNLinksdk.m:116:27: property 'linkCustomizationName' not found on object of type 'PLKConfiguration *'`

**Comment by zachrnolan** [comment]
It looks like `PLKConfiguration.h` is missing the `linkCustomizationName` property.

**Comment by wkiefer** [comment]
Are you using Plaid Link for iOS `1.1.25`? Check your cocoapods file.

The property is defined here:
https://github.com/plaid/plaid-link-ios/blob/master/LinkKit.framework/Headers/PLKConfiguration.h#L148

**Comment by zachrnolan** [comment]
That was it! I didn't catch that update to the readme. Thanks!
