### ISSUE TITLE
Android: Link button click results in consent screen flashing open then closed

### ISSUE THREAD

**Issue by a613** [plaid/react-native-plaid-link-sdk#200]
# The problem

Our team is working on migration to React Native Plaid SDK and we're experiencing a problem on Android. When we launch the plaid flow from Android, there is a brief flash and then the screen closes.

I have modified our files as described in Getting Started at https://github.com/plaid/react-native-plaid-link-sdk. On iOS 14 the Plaid SDK integration is functioning fine. On Android, the behavior I'm seeing when tapping the link button (which does render by the way, because it displays and logs the "The public_key is being deprecated. Learn how to upgrade to link_tokens" message) is a very brief flash of the Plaid consent screen opening, followed by it closing. Even when I am watching the logs in React Native Debugger, there are no logs that could indicate what's going wrong.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 5.0.1, 5.0.0                |
| Plaid pod          | 1.1.37, 2.0.0                |
| com.plaid.link:sdk-core          | 2.2.0, 3.0.0, 3.0.1                |
| com.squareup.okhttp3:okhttp-urlconnection          | 4.9.0, 4.8.1                |
| ReactNative Version     |  0.63.3                |
| Occurs on Android             |  yes                |
| Android OS Version                    |  10 (API 30)                |
| Android Devices/Emulators    | Pixel 3a XL emulator                |
| Occurs on iOS     | no                |
| iOS Version           |  14                |
| iOS Devices/Emulators               |  iPhone 11 Simulator                |

# Steps to Reproduce

Tap the Plaid Link button. Brief flash of a new screen opening, then it's gone.

# Expected Result

Plaid consent screen launched.

# Screenshots

N/A

# Logs

No logs in React Native Debugger

# Code To Reproduce Issue 

```jsx
<PlaidLink
  token={token}
  onSuccess={(data: PlaidData) => onSuccess(data)}
  onExit={onExit}
  clientName={appConfiguration.PLAID_CLIENT_NAME}
  env={appConfiguration.PLAID_ENV}
  product={['transactions']}
  account
>
  <WideButton>{STRINGS.COMMON.CONTINUE.toUpperCase()}</WideButton>
</PlaidLink>
```

**Comment by amytang0** [comment]
I see you are using `com.plaid.link:sdk-core | 2.2.0, 3.0.0, 3.0.1`

React Native 5.x does not work with `sdk-core 3.x`
https://plaid.com/docs/link/react-native/#version-compatibiltiy

**Comment by a613** [comment]
> React Native 5.x does not work with `sdk-core 3.x`

I've also used 2.x.

**Comment by amytang0** [comment]
I see you've added an `account` prop, could you remove that?
All parameters except for `token`, `onSuccess`, and `onExit` will be ignored if you're using a `link-token`

**Comment by a613** [comment]
> I see you've added an `account` prop, could you remove that?

removed. consent screen still crashes on Android

> All parameters except for `token`, `onSuccess`, and `onExit` will be ignored if you're using a `link-token` (since those should've been encoded on the link/token/create call)

interesting, done. But `env` is not a valid param on the call to `link/token/create`, so that one is still needed on the frontend? Anyhow, tried with and without `env`, and no luck - screen still crashes.

Same info as in ticket description but with actual code:

```
```

```
```

**Comment by amytang0** [comment]
Is your Android package name configured in the developer dashboard? See https://plaid.com/docs/link/android/#register-your-app-id"
I also want to check that you're looking at the exit object returned in `onExit`, we often return server errors through that object rather than throwing the error.

env is encoded in your client_secret in the link/token/create call .

**Comment by a613** [comment]
> Is your Android package name configured in the developer dashboard?

yep, all 3 of our package names (dev, qa, and release) are listed in the dashboard:

![Image from iOS](https://user-images.githubusercontent.com/5733420/95369734-cdc81500-08a5-11eb-8812-bc2743a194ed.png)

> want to check that you're looking at the exit object returned in `onExit`

We weren't, no. Will try logging that function's argument and edit this comment with the results.

> env is encoded in your client_secret in the link/token/create call .

awesome, then I'll remove it entirely

**Comment by amytang0** [comment]
If possible, could you add the parameters you are adding to your link/token/create call?
```
curl -i -X POST https://sandbox.plaid.com/link/token/create  --header "Content-Type: application/json" -d '{"client_id":"<CLIENT_ID>","secret":"<SANDBOX_SECRET>","user": {"client_user_id": "123456-unique", "legal_name": "LEGAL NAME" }, "client_name": "CLIENT_NAME",  "products": ["transactions"],  "country_codes":["US"],  "language":"en",   "android_package_name":"com.plaid.linksdksample"}'
```

Can I check that you're passing `android_package_name` as a query parameter?

**Comment by a613** [comment]
> Can I check that you're passing android_package_name as a query parameter?

No we aren't. How is our backend supposed to know the package name? That's irrelevant for a backend. That's a bit excessive if it turns out to be the issue - are there plans to drop that param as it's not important?

**Comment by amytang0** [comment]
So we generate the `redirectUri` from the `android_package_name` for OAuth institutions. To keep things secure (and not returning sensitive bank credentials to an arbitrary app), we require this `android_package_name`. 

Assuming that you're calling the backend from the client, you could pass the caller's package_name to the backend, which could then pass it to the LTC call.

**Comment by a613** [comment]
Setting `android_package_name` on the call to create a link token results in an error saying that the package name has to be added to the dashboard.

It is most certainly added in our dashboard. We have checked half a dozen times, and even tried removing and re-adding it.

**Comment by amytang0** [comment]
First of all, thanks for taking the time to debug and go through the steps!

This definitely sounds like something is happening with our backend. I'll check in with our team, but in the meantime, if this is a blocker, I would suggest using the deprecated public_key implementation. Sorry about that, and I will keep you posted

**Comment by amytang0** [comment]
Sanity-checking: I just want to double-check that you pressed "Save changes" on the Android package names?

**Comment by a613** [comment]
> pressed "Save changes" on the Android package names

I didn't do it personally but I assume yes because the package names are displayed when we load that page in the dashboard.

> The client_id in the request you posted doesn't have any Android package names associated with it

bet that's the issue. what did we miss?

**Comment by amytang0** [comment]
Can you share one of the Android package names? We can find the client_id that is actually associated with them

**Comment by a613** [comment]
I grabbed the latest client_id from the dashboard and now the /link/token/create call is successful! 👍 

Now to test that the Android crash is also resolved...

**Comment by amytang0** [comment]
Woohoo, hopefully the client_id also fixes the https://github.com/plaid/react-native-plaid-link-sdk/issues/201 issue. I also didn't see customizations associated with the other client_id

**Comment by a613** [comment]
Well, lots to report.

Using the new client_id:

* android works, no crash, regardless of whether we include `android_package_name` in the link token call (very surprising)
* iOS works IF `android_package_name` NOT specified
* iOS crashes IF `android_package_name` IS specified

So it looks like

1. our client_id was somehow very very broken and/or old
1. iOS is too sensitive to a link token generated with `android_package_name`
    * however, if Android works without it, then we can just omit it and things are good

**Comment by amytang0** [comment]
Nice, thanks for the thorough report! We will keep an eye out on the `android_package_name` parameter breaking iOS (I personally haven't seen issues while developing RN 6.0+ but will update the docs if 5.x displays this issue consistently)

I am closing this out and will address if this fixes your customization issue as well on the other Github issue.
