### ISSUE TITLE
Recommend adding react-native-plaid-linkkit as peer (or primary) dependency

### ISSUE THREAD

**Issue by prometheas** [plaid/react-native-plaid-link-sdk#208]
Given that it's necessary to install [`react-native-plaid-linkkit`](https://www.npmjs.com/package/react-native-plaid-linkkit) for this package to work (according to support conversation in case ID [#221857](https://dashboard.plaid.com/support/case/221857)), I would recommend adding it either as a direct dependency of this project (in `package.json`), or at least a peer dependency.

Thoughts?

**Comment by all9lives** [comment]
This seems like a no-brainer and a simple way to include `LinkKit` as part of a project. At the very least the docs should be updated to specify that another dependency needs to be added.

**Comment by amytang0** [comment]
Hi, sorry our support team pointed you to that dependency! That dependency is not needed.

**Comment by prometheas** [comment]
Thanks for clarifying, @amytang0. No worries; I’ll go ahead and remove it from my project.
