### ISSUE TITLE
Plaid is stuck with loading screen

### ISSUE THREAD

**Issue by proIT324** [plaid/react-native-plaid-link-sdk#212]
I wrote a script that successfully generates link_token. Using this link_token, I'm gonna open a link in react native app. However, Plaid doesn't open a link and it stays stuck with loading screen. My code is as below:

```
<PlaidLink token={linkToken} oauthNonce={oauthNonce} oauthRedirectUri={oauthRedirectUri} oauthStateId={oauthStateId} onSuccess={onSuccess} onError={onError}>
  <Text>Link</Text>
</PlaidLink>
```

Logs in Xcode:
![Screen Shot 2020-10-06 at 9 10 08 AM](https://user-images.githubusercontent.com/39212059/95205972-c560d300-07ee-11eb-9a2a-172c4cb75e97.png)

How can I resolve this problem so that Plaid redirects to the app?

**Comment by amytang0** [comment]
Hi, I'm just going to double-check some base assumptions. What version are you on? What parameters are on your link/token/create call (e.g. what products/redirectUri are you providing)? Are you trying to open an external European bank's website?

Thanks,
Amy

**Comment by proIT324** [comment]
react-native-plaid-link-sdk@6.0.2-rc2

link/token/create call
{
  user: {
    client_user_id
  },
  client_name,
  products,
  country_codes,
  webhook,
  language
}

I don't try to open any external EU bank website.

**Comment by amytang0** [comment]
So based on the events you sent me, it looks like you are trying to encounter an EU bank.

You'll also need to provide a redirectUri in the link/token/create call https://plaid.com/docs/link/oauth/#redirect-uri-configuration

**Comment by proIT324** [comment]
It must be a universal uri for ios app, isn't it?

**Comment by amytang0** [comment]
"Your redirect URI must be also registered as an app link to enable app2app authentication flows. You will need to configure an Apple App Association File. "
https://plaid.com/docs/link/oauth/#redirect-uri-configuration

**Comment by proIT324** [comment]
Thank you! @amytang0
