### ISSUE TITLE
Android crashes on launch

### ISSUE THREAD

**Issue by osikes** [plaid/react-native-plaid-link-sdk#22]
Currently attempting to use release 2.0.1. On iOS is working fine. I have followed the readme instructions for android, including adding the activity tags and meta-data to the AndroidManifest.xml file.. However app crashes at launch. With logcat, I see fatal error is related to 

**'java.lang.IllegalStateException: Please provide the public key in either Plaid.create() or in a manifest metadata tag with the android:name="com.plaid.link.public_key".** 

I'm confused because I am providing
 `  <meta-data
            android:name="com.plaid.link.public_key"
            android:value="xxxxxxxxxxxx" />` 
 in AndroidManifest.xml. Any help would be appreciated.

**Comment by zsweigart** [comment]
Hi @osikes, thanks for the report.  What version of the Android sdk are you using in your build.gradle file?

**Comment by osikes** [comment]
Appreciate response, I was able to find solution. It was a typo in my AndroidManifest.
