### ISSUE TITLE
Events and/or Event names missing in onEvent callback

### ISSUE THREAD

**Issue by nchase** [plaid/react-native-plaid-link-sdk#222]
# The problem

Events and/or Event names are missing after registering the `onEvent` callback. After upgrading from 4.x.x to 6.0.2 we aren't getting `OPEN` or `EXIT` events, etc. 

The events that we _are_ getting do not have event names. See example below in Logs section.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.2                |
| ReactNative Version     | 0.62.2                |
| Occurs on Android             | untested                |
| Android OS Version                    | untested                |
| Android Devices/Emulators    | untested                |
| Occurs on iOS     |  yes                |
| iOS Version           | 14                |
| iOS Devices/Emulators               | iPhone 11 Pro                |

# Logs
This is the only event that was triggered in the exit process. It's unclear if this is actually the EXIT event, or just some subsequent event, because there's no name:

```
{
  "event": "", // note: we would expect to see an `"event": "EXIT"` in the logs at some point, but instead this field seems to be blank for all events.
  "metadata": {
    "error_code": "",
    "error_message": "",
    "error_type": "",
    "exit_status": "",
    "institution_id": "ins_1",
    "institution_name": "redacted",
    "institution_search_query": "",
    "link_session_id": "2bfa1d75-193e-4b25-9fae-b66c18196493",
    "metadata_json": "",
    "mfa_type": "",
    "request_id": "",
    "timestamp": "2020-10-16T14:45:45Z",
    "view_name": "EXIT"
  }
}
```

**Comment by nchase** [comment]
I upgraded to the final 6.0.2 release and it looks like this is still happening, FWIW.

**Comment by amytang0** [comment]
Hi, can I check what version of iOS Link-kit is in your Podfile? We recommend using iOS Link-kit 2.0.3

**Comment by nchase** [comment]
hi @amytang0 – I observed this issue with iOS Link-kit 2.0.1 and 2.0.3. Can you reproduce?

**Comment by amytang0** [comment]
Unfortunately I can't seem to reproduce this on our sample app. 
This is the open event I see:
`{"event": "OPEN", "metadata": {"error_code": "", "error_message": "", "error_type": "", "exit_status": "", "institution_id": "", "institution_name": "", "institution_search_query": "", "link_session_id": "25c9148a-b889-4ddf-a2f8-8eca065a78c1", "metadata_json": "", "mfa_type": "", "request_id": "", "timestamp": "2020-10-16T17:48:51Z", "view_name": "CONSENT"}}`
And I don't get an exit event (which is expected) but I do get an exit object:
`{"error": {"display_message": "", "error_code": "", "error_message": "", "error_type": ""}, "metadata": {"institution": {"institution_id": "", "name": ""}, "link_session_id": "25c9148a-b889-4ddf-a2f8-8eca065a78c1", "metadata_json": "", "request_id": "", "status": "institution_not_found"}}`

**Comment by nchase** [comment]
> Unfortunately I can't seem to reproduce this on our sample app.
> This is the open event I see:
> `[...]`

our open event is very similar to yours, with the exception that the event name is just an empty string:

```
{
  "event": "",
  "metadata": {
    "error_code": "",
    "error_message": "",
    "error_type": "",
    "exit_status": "",
    "institution_id": "redacted",
    "institution_name": "redacted",
    "institution_search_query": "",
    "link_session_id": "8f8f843e-1f0f-4f71-b0e7-41a328905cd6",
    "metadata_json": "",
    "mfa_type": "",
    "request_id": "",
    "timestamp": "2020-10-16T18:42:12Z",
    "view_name": "CONSENT"
  }
}
```

**Comment by nchase** [comment]
When we log the `eventName.value` in `RNLinksdk.m`, the value that gets returned is `-10`. Any idea what that means?

**Comment by vafada** [comment]
My guess `PLKEventNameValueNone` based on this switch statement:

https://github.com/plaid/react-native-plaid-link-sdk/blob/4122d3661915e2bf4740410e60776eb2ea2a2c8a/ios/RNLinksdk.m#L739-L740

question is.. why the `event.value` has `PLKEventNameValueNone` ?

**Comment by nchase** [comment]
@amytang0 FYI this seems to work fine on Android with the same version – hopefully that's useful information

**Comment by nchase** [comment]
@amytang0 some more information after trying a few different versions

in 5.0.1, the payload is fine, the event name is as expected. it looks like this:

```
{
  "event": "OPEN",
  "metadata": {
    "error_code": null,
    "error_message": null,
    "error_type": null,
    "exit_status": null,
    "institution_id": "ins_3",
    "institution_name": "Chase",
    "institution_search_query": null,
    "link_session_id": "153c5223-e3b1-47ad-a85a-509a2dd20a91",
    "mfa_type": null,
    "request_id": null,
    "timestamp": "2020-10-21T13:27:07.277Z",
    "view_name": null
  }
}
```

In 6.0.0 the payload includes `"event": null` instead of `"event": ""` (the latter is how it appears in 6.0.2).

**Comment by nchase** [comment]
I can reproduce the `"event": null`  situation mentioned above in 6.0.1 in a minimal example project. Was that already a known issue with version 6.0.1?

**Comment by nchase** [comment]
We started with 6.0.2-rc3, which took a dependency on iOS Link-kit 2.0.3 – this no longer happens for happen for us in 6.0.2 final with iOS Link-kit 2.0.5.

Was that just a bad combination of dependencies?

**Comment by amytang0** [comment]
Hey thanks for taking the time to debug this so thoroughly. Speaking for
our iOS team, this may have been a bad combo of SDK's, and we'll document
that as soon as we're sure.

Sounds like the issue was resolved?

Thanks!
Amy

**Comment by nchase** [comment]
Yeah, the issue is resolved @amytang0 – will close.
