### ISSUE TITLE
Console error messages for each key stroke: "currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput"

### ISSUE THREAD

**Issue by prometheas** [plaid/react-native-plaid-link-sdk#223]
# The problem

The console displays the following ERROR level message, with each key stroke event when typing into both the username and password fields of bank login forms:

```
[Fri Oct 16 2020 13:10:52.600]  ERROR    currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput
```

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.2                |
| ReactNative Version     | 0.63.2                |
| Occurs on Android             | didn't test               |
| Android OS Version                    | n/a                |
| Android Devices/Emulators    | n/a                |
| Occurs on iOS     | yes                |
| iOS Version           | 14               |
| iOS Devices/Emulators               | iPhone 11 device + all simulators available in XCode 12    |

# Steps to Reproduce

Bring up the overlay and keep an eye on a console as you enter text into either field.

# Expected Result
What did you expect to happen?

I expect no such error is reported. Also, I would argue this is a `WARN` level message, but I haven't confirmed whether it's coming from the PlaidLink library code, or from a deeper framework layer.

# Screenshots

It's not technically a visual bug, but a screenshot is easy enough to include:

![image](https://user-images.githubusercontent.com/185966/96288932-2f793500-0fb2-11eb-9643-e670f1394209.png)

# Logs

Sadly, the only stack trace I can offer is from a screen shot of my simulator (you can see that the actual console output in the screenshot above only has the message, without a stack trace):

![image](https://user-images.githubusercontent.com/185966/96289138-8121bf80-0fb2-11eb-9b9e-cb3a63cb3247.png)

# Code To Reproduce Issue 

Given that this is almost certainly an API deprecation issue, I don't believe sample code is really all that useful. Happy to whip something up if you guys are unable to reproduce with the version info above, though—lmk.

**Comment by pladaub** [comment]
This is part of react-native itself, not the react-native-plaid-link-sdk
