### ISSUE TITLE
UI Problems after solving reCaptcha

### ISSUE THREAD

**Issue by bpander** [plaid/react-native-plaid-link-sdk#224]
# The problem

After triggering the reCaptcha flow and verifying you're not a robot, there are visual issues and missing information on the following screen where you select your account.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 5.0.1                |
| ReactNative Version     | 0.61.5                |
| Occurs on Android             | yes                |
| Android OS Version                    | 9 (28)                |
| Android Devices/Emulators    | Galaxy S9 Emulator                |
| Occurs on iOS     | yes                |
| iOS Version           | 13.3                |
| iOS Devices/Emulators               | iPhone 11                |

# Steps to Reproduce

1. Open plaid link
2. Select any bank
3. Trigger the reCaptcha flow by entering credentials:
    a. Username: user_custom
    b. Password: {"recaptcha":"good"}
4. Solve reCaptcha
5. Observe missing information on "Select your account" screen

```
{
   "client_id":"OMITTED",
   "secret":"OMITTED",
   "user":{
      "client_user_id":"OMITTED",
   },
   "client_name":"My application",
   "products":[
      "auth"
   ],
   "country_codes":[
      "US"
   ],
   "language":"en"
}
```

# Expected Result
Account selection screen after solving a reCaptcha should appear the same as the account selection screen in the non-captcha flow.

# Screenshots
**iOS**
<img width="489" alt="Screen Shot 2020-10-16 at 1 36 07 PM" src="https://user-images.githubusercontent.com/1141573/96299482-22fcd880-0fc2-11eb-9e4c-5dfd03b441c2.png">

**android**
<img width="467" alt="Screen Shot 2020-10-16 at 1 41 15 PM" src="https://user-images.githubusercontent.com/1141573/96299510-2abc7d00-0fc2-11eb-9b20-6fff4439c51d.png">

# Logs
N/A

# Code To Reproduce Issue 
You just need a pretty standard setup once you generate the linkToken.

```
import React from 'react';
import { Text } from 'react-native';
import PlaidLink from 'react-native-plaid-link-sdk';

export const PlaidBtn = () => {
    return (
        <PlaidLink token={linkToken}>
            <Text>Add Account</Text>
        </PlaidLink>
    );
};
```

**Comment by JeroenMols** [comment]
Hi @bpander,

We've just rolled out a new design for Link and have made significant improvements to our RN SDK.
Can you try upgrading to `7.0.0-rc2` and see if the issue still persists there?

Note that the 7.0.x upgrade is quite a significant one, should that be an obstacle at the moment you can also test on the latest `6.0.4` version. Instructions to upgrade can be found in [our readme](https://github.com/plaid/react-native-plaid-link-sdk#updating-from-previous-versions).

**Comment by bpander** [comment]
@JeroenMols No dice. I retested using `6.0.4` on android (plaid sdk 3.2.0) and ios (plaid sdk 2.0.9) as well as `7.0.0-rc2` on android (3.2.2) and ios (2.0.9). The data was still missing in every case (no last 4 digits or account balance).

**Comment by JeroenMols** [comment]
Thanks for trying the upgrade! I had assumed that would also provide you with the Link redesign, but that appears not to be the case. I'm going to follow up with this internally and get back to you when I know more.

**Comment by bpander** [comment]
If it helps, those new versions did have a different design from the screenshots posted, but the data was still missing.

**Comment by JeroenMols** [comment]
Thanks for clarifying that, I'm now able to reproduce your issue:

<img src="https://user-images.githubusercontent.com/6319637/104181302-cff2c000-540e-11eb-8bd6-d4efb14c0ee1.png" width="40%"> <img src="https://user-images.githubusercontent.com/6319637/104181306-d2551a00-540e-11eb-9d90-a4b080bd5d30.png" width="40%">

I'll update the internal issue we have for tracking this and will keep you posted once I have an ETA.

Most likely this will be fixed on the new design earlier that the old, so I would recommend to stay on the lastest SDK version if that's possible for you.

**Comment by JeroenMols** [comment]
This appears to be a feature: when our backend considers a request risky it will strip some information such as account mask and balances. This isn't something you should be concerned about for production traffic.
