### ISSUE TITLE
iOS - When Plaid closes, it closes all other modals and leaves app in unresponsive state

### ISSUE THREAD

**Issue by bpander** [plaid/react-native-plaid-link-sdk#227]
# The problem
If a react-native Modal is open when Plaid exits (e.g. Plaid is launched from a Modal), Plaid closes that modal, and the app is no longer responsive.

# Environment
|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.2                |
| ReactNative Version     | 0.63.3 (also seen in 61.5)                |
| Occurs on Android             | no                |
| Android OS Version                    |                 |
| Android Devices/Emulators    |                 |
| Occurs on iOS     | yes                |
| iOS Version           | 13.5 (also seen in 11)                |
| iOS Devices/Emulators               | iPhone 11 Simulator                |

# Steps to Reproduce
1. Add a PlaidLink button to a react-native Modal
2. Open the modal, then launch Plaid
3. Exit Plaid
4. Observe the modal is also closed and the app is no longer responsive

# Expected Result
Plaid should not close other modals nor leave the app in an unresponsive state.

# Screenshots
https://i.imgur.com/i01qB0v.mp4

# Logs
This probably isn't relevant, but I'll include it just in case. This is what I see in the logs when I trigger the bug.

```
2020-10-20 16:29:40.319389-0400 PlaidModalBug[12476:106719] WF: _userSettingsForUser : (null)
2020-10-20 16:29:40.319559-0400 PlaidModalBug[12476:106719] WF: _WebFilterIsActive returning: NO
2020-10-20 16:29:40.579252-0400 PlaidModalBug[12476:106719] Unbalanced calls to begin/end appearance transitions for <LinkKit.InProcessWebviewFallbackController: 0x7fe416f29d80>.
2020-10-20 16:29:44.332931-0400 PlaidModalBug[12476:106719] [ProcessSuspension] 0x117e26b10 - ProcessAssertion::processAssertionWasInvalidated()
2020-10-20 16:29:44.338826-0400 PlaidModalBug[12476:106719] [ProcessSuspension] 0x117e26ab0 - ProcessAssertion::processAssertionWasInvalidated()
```

# Code To Reproduce Issue 
Here's a repo demonstrating the faulty behavior. Make sure to replace the `client_id` and `secret`. https://github.com/bpander/PlaidModalBug

**Comment by bpander** [comment]
If it helps at all, it looks like the issue with this sdk is there's two "dismiss" calls. The linkHandler dismisses the plaid modal, then the onExit/onSuccess callback (in ios/RNLinksdk.m) calls dismissLinkViewController, which dismisses whatever non-plaid modal is open.

I'm not an iOS developer, but this seems to do the trick for me:

```
// react-native-plaid-link-sdk/ios/RNLinksdk.m

- (void)dismissLinkViewController {
    BOOL isPlaidModalOpen = RCTPresentedViewController() != self.presentingViewController;
    if (isPlaidModalOpen) {
        [self.presentingViewController dismissViewControllerAnimated:YES completion:nil];
        self.presentingViewController = nil;
        self.linkHandler = nil;
    }
}
```

@afh @wkiefer @pladaub Would you like me to create a PR?

**Comment by BrandonCao** [comment]
I'm getting this error as well!
