### ISSUE TITLE
Is it possible to launch the plaid flow on render?

### ISSUE THREAD

**Issue by djMax** [plaid/react-native-plaid-link-sdk#228]
Our use case would be better served by not needing a button wrapped in the plaid control launch the flow. Is this possible? To be specific, we have a useEffect that will go fetch the link token, and then if they click our button BEFORE that's done, we'll just make a spinner and then render the PlaidLink component conditionally based on the completion of the call. But I can't see any way to do that without requiring an additional user tap.

**Comment by djMax** [comment]
I think "openLink" is meant to do this, but it does not take the link token, it only takes the public key...

**Comment by Maftalion** [comment]
@djMax `openLink` takes the token and other values you pass via props with the component implementation
```
    const plaidConfig = {
      onSuccess,
      onExit,
      token,
    };

    openLink(plaidConfig);
```

**Comment by djMax** [comment]
Thx. I realize now that I had to roll my own Typescript defs, and hadn't included these other props.
