### ISSUE TITLE
Build Issue with 6.0.2 in iOS

### ISSUE THREAD

**Issue by jack-fin** [plaid/react-native-plaid-link-sdk#239]
# The problem

I am working to update our v5 version of Plaid to the v6.0.2 release. This worked well under Andriod but is causing an XCode a build failure.

See below for details on my env, running >.60 so my pods should auto link, and I have installed the latest Pods from this Plaid upgrade.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 6.0.2                |
| ReactNative Version     | e.g. 0.63.3                |
| Occurs on Android             | e.g. no                |
| Android OS Version                    | e.g. 5.0.0 (21)                |
| Android Devices/Emulators    | e.g. Pixel 3a physical                |
| Occurs on iOS     | e.g. yes                |
| iOS Version           | e.g. 11                |
| iOS Devices/Emulators               | e.g. iPhone X                |

# Steps to Reproduce

Bump Plaid Link React Native to v6.0.2, install Pods, and then build a release/debug in Xcode. During the build the following error occurs:
```
cp: /Users/jack/git/coindust_app/ios/Pods/Plaid/ios/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
/Users/jack/Library/Developer/Xcode/DerivedData/Coindust-enwgxbixtajtnwdpaveandhinfur/Build/Intermediates.noindex/Coindust.build/Debug-iphonesimulator/Coindust.build/Script-0464D6082525369200167C9C.sh: line 5: /Users/jack/Library/Developer/Xcode/DerivedData/Coindust-enwgxbixtajtnwdpaveandhinfur/Build/Products/Debug-iphonesimulator/Coindust.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

# Expected Result
Xcode build to succeed, after installing the latest pods.

Thank you!

**Comment by amytang0** [comment]
Hey, what version of Plaid is in your Podfile?
Could you try `pod 'Plaid', '~> 2.0.5'`?

**Comment by jack-fin** [comment]
Hello! I do not actually have Plaid in the Podfile itself, I do see `Plaid (2.0.5)` within the Podfile.lock, however.

I tried adding `pod 'Plaid', '~> 2.0.5'` to my Podfile as well, just in case but am seeing the same issue in my build.

**Comment by jack-fin** [comment]
I do see this change was made to my project file, possibly by the auto linking? Seems like it could be related?
<img width="1488" alt="Screen Shot 2020-10-30 at 2 34 20 PM" src="https://user-images.githubusercontent.com/5135602/97749413-05993580-1abd-11eb-86c6-6ed03995619a.png">

**Comment by afh** [comment]
Thank you for using Plaid Link, @jack-fin.

The custom build script phase is no longer necessary with LinkKit 2.x, please see the [1.x to 2.x Migration Guide](https://plaid.com/docs/link/ios/ios-v2-migration/#remove-the-custom-prepare-for-distribution-build-phase) for details.

Note that the majority of the migration guide covers manual or cocoapods integrations. For react-native integration most of it does not apply as the react-native bridge ([`RNLinksdk`](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/ios/RNLinksdk.m)) has already been updated to work with the changes that LinkKit 2.x brought.

**Comment by jack-fin** [comment]
@afh Thank you! I'm sorry I missed that migration guide, this resolved my issue. I simply needed to remove the custom build script phase.
