### ISSUE TITLE
Android, link doesn't open Plaid

### ISSUE THREAD

**Issue by osikes** [plaid/react-native-plaid-link-sdk#24]
I'm running into issues v 2.0.3. The component link renders but when I click on link, the android app doesn't switch to a Plaid view of banks. In log cat I see error 
`Class not found when unmarshalling: com.plaid.linkbase.models.LinkConfiguration` I'm assuming I have something configured wrong, but unsure of how to debug.

**Comment by kanji-keraliya** [comment]
@wkiefer Now showing button but do not open Plaid window.
I am using V2.0.3 and React Native V0.61.5

Showing warning in development 
` TypeError: null is not an object (evaluating '_reactNative.NativeModules.PlaidAndroid.getConstants')
    openLink$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:157682:66` 

Can you please help me

**Comment by kanji-keraliya** [comment]
@wkiefer I request you to add working example so every one know how to integrate it on android as well as iOS

Thanks in advance

**Comment by zsweigart** [comment]
Hi @osikes,
So with a class not found it usually indicates something wrong with the gradle setup, or a file was obfuscated accidentally.  There are a few things we can look at.  

First do you have the [build.gradle](https://github.com/plaid/react-native-plaid-link-sdk#androidappbuildgradle) and [settings.gradle](https://github.com/plaid/react-native-plaid-link-sdk#androidappbuildgradle) files configured? 

Next, sometimes the auto update doesn't work when you change gradle files so I would suggest running `npx react-native run-android` again to start the app from scratch.

Finally, are you running with minify (proguard or R8) enabled? If so we might want to look at your proguard file.

**Comment by Mande3p** [comment]
Facing the same issue, link does not open Plaid on android. it works as expected on iOS.

**Comment by osikes** [comment]
@zsweigart I've verified build.gradle and settings.gradle. I have no proguard settings enabled. Perhaps I"m using the wrong value in the webviewRedirectUri. I'm assuming the 'yourAppName' should be replaced with value in strings.xml (@string/app_name) ?

**Comment by zsweigart** [comment]
So you will need to [register a redirect URI ](https://plaid.com/docs/link/android/#register-redirect-uri) and then use that redirect URI as the webviewRedirectUri property.  We suggest you use something unique like your company name as the scheme to avoid conflicts with other apps in which case the app chooser will show.

**Comment by osikes** [comment]
Yep, did that as well. Ensured uri is set in webviewRedirectUri prop, as well as data element in AndroidManifest file.

**Comment by osikes** [comment]
I just attempted to test react-native-plaid-link-sdk for android on a new react native app, using[ cli quick start guide](https://facebook.github.io/react-native/docs/getting-started). And running into same issue 🤷‍♂

**Comment by osikes** [comment]
An update.. I got it work 🍺 ... apparently for 'auth' product the props  [userLegalName, userEmailAddress] are required... which I don't understand why they aren't also required for iOS?

**Comment by zsweigart** [comment]
Ahh yes those fields should be required for 'auth' 
@wkiefer can you double check why those aren't required for `auth` on ios?

**Comment by osikes** [comment]
@zsweigart they aren't required for web version of Plaid either (for 'auth' product) ... curious why required for mobile then?

**Comment by zsweigart** [comment]
That is a good catch, there was a miscommunication when building the android sdk, we will update this to be optional for the next release

**Comment by osikes** [comment]
Just wanted to say how awesome it is to have this official RN package for Plaid. And how much I appreciate getting dev support from y'all. 👍 Thank you. 😊

**Comment by osikes** [comment]
This seems to be more broken. 2.0.4 I can't get the android link to open at all.
