### ISSUE TITLE
Causes activity callback issues for other packages

### ISSUE THREAD

**Issue by Mande3p** [plaid/react-native-plaid-link-sdk#25]
When 'react-native-plaid-link-sdk' is used in app, it causes activity callback to fail for other apps like 'react-native-image-picker'. 'react-native-image-picker' crashes the first time when you use it together with 'react-native-plaid-link-sdk', as its the first time when 'react-native-image-picker' asks for permissions from user, the callback for which it does not receive due to 'react-native-plaid-link-sdk' which makes the app crash.

Tested several times, once i remove  'react-native-plaid-link-sdk', everything starts working fine as expected. Please fix this, thanks.

**Comment by Mande3p** [comment]
Fixed it, so removing reactApplicationContext.removeActivityEventListener(this) on Plaid unmount solved the issue.

Added this method to to PlaidModule.kt:
`  @ReactMethod
  @Suppress("unused")
  fun removeActivityEventListener(){
    reactApplicationContext.removeActivityEventListener(this)
  }`

Updated PLaidLink.js:
`export class PlaidLink extends Component{

  componentWillUnmount(){
    if (Platform.OS === 'android') {
      NativeModules.PlaidAndroid.removeActivityEventListener();
    }
  }

  render(){
    const{
      component,
      componentProps,
      children,
      ...linkProps
  }= this.props;
  const Component = component;

  return (
    <Component
      {...componentProps}
      onPress={() => handlePress(linkProps, componentProps)}
    >
      {children}
    </Component>
  );
  }
};`

**Comment by zsweigart** [comment]
Hi @Mande3p would you mind opening a PR with the changes so we can review them?

**Comment by zsweigart** [comment]
Hi @Mande3p since we've updated how the PlaidLink component is built, this code will now live in your app.js file.
