### ISSUE TITLE
Unable to redirect user to a specific institution when opening Plaid Link 

### ISSUE THREAD

**Issue by Bhavik-P** [plaid/react-native-plaid-link-sdk#260]
# The problem

We 

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          |  6.0.3               |
| ReactNative Version     |  0.61.5                |
| Occurs on Android             |  yes                |
| Android OS Version                    |  All                |
| Android Devices/Emulators    |  All                |
| Occurs on iOS     |  No               |
| iOS Version           | N/A                |
| iOS Devices/Emulators               | N/A               |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

The configuration I use is on the backend using the JAVA SDK. It creates a token that I can use to open up the Plaid Link client.
```
LinkTokenCreateRequest.User user = new LinkTokenCreateRequest.User(userId);

LinkTokenCreateRequest tokenCreateRequest = new LinkTokenCreateRequest(
  user,
  "[REDACTED]",
  Collections.singletonList("transactions"),
  "US",
  "en"
);
```

```
const configuration = {
    token: <GENERATED_TOKEN>,
    onSuccess: (data) => (),
    onExit: (data) =>. (),
    institution: "ins_3",
  };
```

# Expected Result
Open Plaid Link and redirect the user to open Chase

# Screenshots
If this is a visual bug a screenshot would be helpful.

# Logs
None

# Code To Reproduce Issue 
With sample code it's easier to reproduce the bug and it's much faster to fix it. 
Don't forget to omit any keys or personally identifiable information.
Please provide one of the following:

1. (Best) A link to a minimal demo app showing the faulty behaviour.
1. (Better) A concise code sample which can be dropped into fresh application
1. A snippet of code for your configuration for opening Link

```
import { openLink } from "react-native-plaid-link-sdk";

const configuration = {
    token: <GENERATED_TOKEN>,
    onSuccess: (data) => (),
    onExit: (data) =>(),
    institution: "ins_3",
 };

openLink(configuration);
```

**Comment by zsweigart** [comment]
Hi @Bhavik-P 
It looks like you need to pass the institution id on the server side when creating your link token.  Also please check with your account manager that your account is enabled for opening an institution directly.

**Comment by JeroenMols** [comment]
Hi @Bhavik-P ,

We haven't heard back from you in a while so we're assuming you've been able to sort out this issue already.
Please don't hesitate to get in touch should that not be the case.

Jeroen
