### ISSUE TITLE
Xcode build error - dylib failure

### ISSUE THREAD

**Issue by teeolendo** [plaid/react-native-plaid-link-sdk#261]
I'm using the RNPLS version 6.0.3, and when I run the application on my device, I get a persistent build error. It builds fine on the simulator but it doesn't build when I run it on my device or when I set it to a generic ios device.

`ld: building for iOS, but linking in dylib file (/Users/********/Library/Developer/Xcode/DerivedData/projectname-fwcxydociljoyzfueniqbwswsbyy/Build/Products/Release-iphoneos/LinkKit.framework/LinkKit) built for iOS Simulator, file '/Users/*********/Library/Developer/Xcode/DerivedData/projectname-fwcxydociljoyzfueniqbwswsbyy/Build/Products/Release-iphoneos/LinkKit.framework/LinkKit' for architecture arm64`

I've followed the instructions [here](https://stackoverflow.com/questions/63391793/xcode-12-build-target-in-wrong-order/63405201#63405201)

 This is a screenshot of my .xcodeproj setup. pod project looks pretty much the same
<img width="766" alt="Screenshot 2020-11-16 at 2 56 23 AM" src="https://user-images.githubusercontent.com/2772900/99221759-8fcce380-27b7-11eb-867c-105277a0caba.png">

# Environment
|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.3                |
| ReactNative Version     | 0.62.2                |
| XCode Version            | 12.2                |
| Plaid version                   | 2.0.5             |
| Android Devices/Emulators    | n/a                |
| Occurs on iOS     | yes                |
| iOS Version           | 12 >              |
| iOS Devices/Emulators               | works on Simulator; doesn't work on connected iPhone 11 |

# Logs
Results from when I run `find . -path '*LinkKit.framework/Info.plist'|pbcopy; pbpaste; pbpaste|xargs -n1 /usr/libexec/PlistBuddy  -c 'Print CFBundleSupportedPlatforms' -c 'Print CFBundleShortVersionString' -c 'Print CFBundleVersion'`:
```
./ios/Pods/Plaid/LinkKit.xcframework/ios-arm64_x86_64-simulator/LinkKit.framework/Info.plist
./ios/Pods/Plaid/LinkKit.xcframework/ios-arm64/LinkKit.framework/Info.plist
Array {
    iPhoneSimulator
}
2.0.5
1131.1
Array {
    iPhoneOS
}
2.0.5
1131.1
```

**Comment by cohen72** [comment]
my co-worker @elingersin1 and I spent the day digging and discovered that the by switching the order of the entries within the `./Pods/Plaid/LinkKit.xcframework/Info.plist`, so that the entry for `ios-arm64` comes **before** the entry for `ios-arm64_x86_64-simulator`.

Then re-run `pod install` and it should correctly generate the `Pods-<Project>-artifacts.sh` file which is being run during the `[CP] Prepare Artifacts` build phase

**Comment by osikes** [comment]
Running into same issue. With a  m1 MacBook Pro.

**Comment by Zhuxingzhi01** [comment]
怎么解决呢

**Comment by Liamandrew** [comment]
Very frustrating issue, especially when there's not much support on how to fix it. Eventually I upgraded to the latest cocoapods version (1.10.0) & did `pod install` and this fixed the issue for me without needing to modify the `Info.plist` like above.

**Comment by lukaskai** [comment]
Yes, upgrading cocoapods version to 1.10.0 helped.

**Comment by afh** [comment]
Thanks, for the report @Liamandrew, @lukaskai.

@teeolendo can you confirm that updating CocoaPods 1.10.0 resolves the issue for you too and close this issue?

**Comment by agoldis** [comment]
Upgraded cocoapods to `1.10.1` - still facing the issue

**Comment by afh** [comment]
@agoldis Can you check if the Xcode Build Setting `VALIDATE_WORKSPACE` is set to `NO`, set it accordingly if it isn't and retry, please?

**Comment by agoldis** [comment]
@afh I did, still no luck - I am seeing the next message:

```
dyld: Library not loaded: @rpath/LinkKit.framework/LinkKit
  Referenced from: /private/var/containers/Bundle/Application/F3B7A692-0561-4989-8858-DC33A1582D3D/xxx-staging.app/xxx-staging
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib
```
Trying to run on a iOS 14.2 physical device

Xcode version 12.3 (12C33)
Cocoapods version 1.10.1
react-native-plaid-link-sdk 6.0.4
react-native 0.61.3

<img width="527" alt="Screen Shot 2021-01-20 at 12 05 28 PM" src="https://user-images.githubusercontent.com/1637928/105228789-d7ede680-5b17-11eb-89b9-1477f937ce18.png">

**Comment by agoldis** [comment]
Fixed by switching to new build system and dragging LinkKit into embedded frameworks
