### ISSUE TITLE
When completing the Same Day Micro-Deposit flow, the account's verification_status is missing

### ISSUE THREAD

**Issue by bpander** [plaid/react-native-plaid-link-sdk#264]
# The problem

When completing the Same Day Micro-Deposit flow, in the onSuccess payload, the account's verification_status is not present in android and is an empty string in iOS, but it should be manually_verified.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.3                |
| ReactNative Version     | 0.61.5                |
| Occurs on Android             | yes                |
| Android OS Version                    | 29                |
| Android Devices/Emulators    | Galaxy S9 Emulator                |
| Occurs on iOS     | yes                |
| iOS Version           | 13.5                |
| iOS Devices/Emulators               | iPhone 11 Simulator                |

# Steps to Reproduce

1. Implement the Same Day Micro-deposit flow (https://plaid.com/docs/auth/coverage/same-day/#the-same-day-micro-deposit-flow)
2. Test the Same Day Micro-deposit flow (https://plaid.com/docs/auth/coverage/testing/#testing-same-day-micro-deposits)
3. Observe that in the onSuccess callback after manually entering the micro-deposit amounts, the account's verification_status property does not exist in android and an empty string in iOS.

# Expected Result
Per the documentation, "Upon successful entry of the two amounts, the onSuccess callback will be fired, with an updated verification_status: 'manually_verified'."

# Screenshots
<img width="522" alt="Screen Shot 2020-11-17 at 1 39 11 PM" src="https://user-images.githubusercontent.com/1141573/99432549-517c1500-28da-11eb-8655-8724a6072f00.png">

# Logs
N/A

# Code To Reproduce Issue 

```
import React, { useEffect, useState, useCallback } from 'react';
import { View, Text } from 'react-native';
import PlaidLink from 'react-native-plaid-link-sdk';

const client_id = 'OMITTED';
const secret = 'OMITTED';

const SameDayMicroDepositFlow = () => {
    const [initialLinkToken, setInitialLinkToken] = useState('');
    const [continueLinkToken, setContinueLinkToken] = useState('');

    useEffect(() => {
        const loadToken = async () => {
            const res = await fetch('https://sandbox.plaid.com/link/token/create', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    client_id,
                    secret,
                    client_name: 'My Client',
                    language: 'en',
                    country_codes: ['US'],
                    user: { client_user_id: 'abcd-1234' },
                    products: ['auth'],
                }),
            });
            const json = await res.json();
            setInitialLinkToken(json.link_token);
        };
        loadToken();
    }, []);

    const onInitialSuccess = useCallback(async (plaidResponse) => {
        const exchangeRes = await fetch('https://sandbox.plaid.com/item/public_token/exchange', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                client_id,
                secret,
                public_token: plaidResponse.public_token,
            }),
        });
        const exchangeData = await exchangeRes.json();
        const res = await fetch('https://sandbox.plaid.com/link/token/create', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                client_id,
                secret,
                client_name: 'My Client',
                language: 'en',
                country_codes: ['US'],
                user: { client_user_id: 'abcd-1234' },
                access_token: exchangeData.access_token,
            }),
        });
        const json = await res.json();
        setContinueLinkToken(json.link_token);
    }, []);

    if (!initialLinkToken) {
        return null;
    }

    return (
        <View style={{ margin: 50 }}>
            {(!continueLinkToken) ? (
                <PlaidLink token={initialLinkToken} onSuccess={onInitialSuccess}>
                    <Text>Initialize Link</Text>
                </PlaidLink>
            ) : (
                <PlaidLink token={continueLinkToken} onSuccess={(...args) => console.log('success', args)}>
                    <Text>Continue Setup</Text>
                </PlaidLink>
            )}
        </View>
    );
};
```

**Comment by amytang0** [comment]
Hey, this is a KP on iOS. Can you show an example payload on Android?

Thank you!

**Comment by bpander** [comment]
Sure thing. When I run my sample code in android, this is the payload I get in the onSuccess callback after entering the microdeposit amounts. In android, verification_status is not present at all.

<img width="778" alt="Screen Shot 2020-11-18 at 4 37 41 PM" src="https://user-images.githubusercontent.com/1141573/99591282-8fea0080-29bc-11eb-82aa-c8a486664b1a.png">

**Comment by AnkurGahtori2012** [comment]
I am also not getting "### verification_status" field in IOS.
[
![Screenshot 2020-11-19 at 1 06 30 PM](https://user-images.githubusercontent.com/60691396/99762461-92646b80-2b1e-11eb-8817-9be76c6d75bd.png)
](url)
my Current Environment
**React native 60.5
React Native Plaid Sdk 5.0.1
Plaid IOS SDK 1.1.38
Sandbox environment**


I recently shifted to this environment after facing issue #254 that is resolved but now facing this new issue.

After filling in account details last screens appears,
![Screenshot 2020-11-20 at 11 03 36 AM](https://user-images.githubusercontent.com/60691396/99763266-6ba73480-2b20-11eb-9c43-741e19bc519e.png)
Clicking on the Continue button triggers onSuccess callback with data but not having field ### verification_status. With last version (**RN Plaid SDk  3.2.0 and IOS Plaid SDK 1.1.32**) I was getting data having "### verification_status"

**Comment by ankurgahtori** [comment]
![Screenshot from 2020-11-20 12-23-16](https://user-images.githubusercontent.com/37188059/99768768-5d124a80-2b2b-11eb-9c11-431fd989a24d.png)
But on android I am getting ### verification_status

**Comment by afh** [comment]
Hi @bpander, which version of the [`Plaid` CocoaPod](https://cocoapods.org/pods/Plaid) is used in your project?
```
% grep 'pod.*Plaid' $(find . -name Podfile) 
pod 'Plaid', '~> 2.0.6'
```

**Comment by bpander** [comment]
@afh Yeah 2.0.6. I just retested against the latest ios sdk version (2.0.8), and the issue still happens in that version too.

**Comment by afh** [comment]
Thanks for the update, @bpander, I'll continue with the investigation.

**Comment by drekembe** [comment]
Hi, just my 2 cents: I'm on react-native-plaid-link-sdk 4.0.1 and iOS Plaid SDK 1.3.3, and am not getting the verification_status field at all in the accounts array when onSuccess is called. Thanks for looking into it

**Comment by afh** [comment]
Thank you for your patience @bpander. We have identified the cause of the issue and are working on a fix. I'll update this issue once the fix is available, probably some time next week ([cw 51](http://www.whatweekisit.org)).

**Comment by afh** [comment]
We are rolling out a fix and it should be available in a few hours ([21:00 UTC](https://everytimezone.com/?t=5fd7fc80,a8c)).
@bpander, can you test that Link behaves the way you'd expect and close the issue if it does?

**Comment by bpander** [comment]
@afh Looks good. I retested with the latest android and ios sdks (3.2.2 and 2.0.9 respectively), and verification_status was present and correct for both.
`verification_status: { json: "manually_verified" } // android`
`verification_status: "manually_verified" // ios`

Closing this as fixed. Thank you!
