### ISSUE TITLE
'TypeError: null is not an object' when clicking 'Add Account'

### ISSUE THREAD

**Issue by alexlod** [plaid/react-native-plaid-link-sdk#27]
I've followed the instructions in the README for `ios`. When I click `Add Account` in the iOS simulator, no Plaid dialog pops up. Instead I get a warning in the UI and the following error in my Expo terminal:

```
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNLinksdk.create')]
- node_modules/react-native-plaid-link-sdk/PlaidLink.js:28:28 in openLink$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- ... 36 more stack frames from framework internals
```

The UI warning looks like this:

<img width="320" alt="Screen Shot 2019-12-19 at 8 49 44 PM" src="https://user-images.githubusercontent.com/39045/71231095-35728c80-22a1-11ea-9260-f5df4bd3ef5a.png">

I'm using version `2.0.4` with `react-native` version `35.0.0` (Expo's fork).

This is the JSX code I'm using (with the correct variables):

```
<PlaidLink
  publicKey="<my-public-key>"
  clientName="<my-client-name>"
  env="sandbox"
  product={["transactions"]}
  webviewRedirectUri = "<my-app-name>://redirect"
  onSuccess={this.handleOnSuccess}
  onExit={this.handleOnExit}>
    <Text>Add Account</Text>
</PlaidLink>
```

EDIT: I manually linked the SDK via `npx react-native link react-native-plaid-link-sdk` and am using `expo start` with xCode to run the app. I think I've done all the right setup here but I am new to React Native.

Any ideas? Thanks!

**Comment by alexlod** [comment]
I have a feeling this is related to my Expo setup. I'll close this for now while I continue to debug. I'll report back with my findings.

**Comment by alexlod** [comment]
Yes, indeed this was an Expo setup. I wasn't properly linking the Plaid SDK. I need to do this:

```
yarn run react-native link react-native-plaid-link-sdk
cd ios
pod install
cd ..
```

I was missing `pod install`.

**Comment by devika7** [comment]
Hi, I am facing the same issue. Do I have to eject the project from Expo to be able to do the above steps? There is no ios or android folder in my current react native project. So wanted to know if I can use plaid without ejecting my project from expo.

**Comment by alexlod** [comment]
Yes you need to eject the expo project.

**Comment by devika7** [comment]
@alexlod Thanks for your input. Hoping to get this resolved now as I was stuck with this for some days. Do you have any example project where you have integrated Plaid? Would be very helpful to refer a bit.

**Comment by alexlod** [comment]
Unfortunately I don’t have any resources that would be helpful for you. Although personally I’ve found expo to do more harm than good when a native library is needed. You may benefit from restarting your project with pure react native and avoiding expo.
