### ISSUE TITLE
'Day of Month' change request

### ISSUE THREAD

**Issue by Sterlingryan** [plaid/react-native-plaid-link-sdk#289]
# The problem

I have created a standing order with **/payment_initiation/payment/create** and put -1 for **interval_execution_date** as per the API documentation for the standing order to execute the last day of the month. When opening link, in the payment details page, the value for Day of Month is -1, is it possible to change '-1' to something more user friendly ? something along the lines of 'last day of month'

# Screenshots
![Simulator Screen Shot - iPhone 11 Pro - 2020-12-09 at 14 19 09](https://user-images.githubusercontent.com/15817814/101748426-d4088680-3acc-11eb-9c06-bac82058ca90.png)

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4                |
| Occurs on Android             | yes                |
| Occurs on iOS     | yes                |

**Comment by amytang0** [comment]
Hey, thanks for the flag! I've passed this issue onto our payment initiation team and will let you know when that's fixed. No new SDK changes should be necessary

**Comment by Sterlingryan** [comment]
Any update on this ?

**Comment by amytang0** [comment]
Sorry, our payments team have not prioritized this ticket. I would suggest opening a support ticket, as this is not a React Native SDK issue. Apologies again
