### ISSUE TITLE
iOS tiggers onExit callback (with valid linked response) instead of onSuccess, Android works fine

### ISSUE THREAD

**Issue by DjordjePetrovic** [plaid/react-native-plaid-link-sdk#290]
# The problem

In the Lates version, I noticed the issue where on the Android, upon Success Linking I'll get a callback on the onSuccess method, but on the iOS onExit with onSuccess data.

Here is the response that's returned on the onExit method: 

```
{
  "metadata": {
    "accounts": [[Object]],
    "institution": {
      "id": "ins_3",
      "name": "Chase"
    },
    "linkSessionId": "2aae6b8f-45b2-4e0f-ab99-69bb7bb712bf",
    "metadataJson": "{\"institution\":{\"name\":\"Chase\",\"institution_id\":\"ins_3\"},\"account\":{\"id\":\"QlKDg8E681u7GPywA1rDHaqLJa7E3LhpPGnaa\",\"name\":\"Plaid Checking\",\"type\":\"depository\",\"subtype\":\"checking\",\"mask\":\"0000\"},\"account_id\":\"QlKDg8E681u7GPywA1rDHaqLJa7E3LhpPGnaa\",\"accounts\":[{\"id\":\"QlKDg8E681u7GPywA1rDHaqLJa7E3LhpPGnaa\",\"name\":\"Plaid Checking\",\"mask\":\"0000\",\"type\":\"depository\",\"subtype\":\"checking\"}],\"link_session_id\":\"2aae6b8f-45b2-4e0f-ab99-69bb7bb712bf\",\"public_token\":\"public-sandbox-fe3e2b27-73fd-4855-a476-49f107cb0fbd\"}"
  },
  "publicToken": "public-sandbox-fe3e2b27-73fd-4855-a476-49f107cb0fbd",
  "status": "connected"
}
```

**Problem Comes from this method:** 

https://github.com/plaid/react-native-plaid-link-sdk/blob/master/PlaidLink.tsx#L67

As you can see on the response above, "**status**" is not a part of the "**metadata**" object. Any idea why this structure is different on the iOS and Android? 

And is it possible that the problem is with my local setup or it comes from the Plaid API?, Thanks!

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.0-rc1                |
| ReactNative Version     | ~0.63.4                |
| Occurs on Android             | no                |
| Occurs on iOS     | yes                |
| iOS Version           | 11                |
| iOS Devices/Emulators               | iPhone 11                |

# Expected Result
onSuccess Triggered when Linking is done properly

**Comment by spsaucier-bakkt** [comment]
I, too, am seeing this on `7.0.0-rc1`.

**Comment by afh** [comment]
A fix for this issue will be available with the next release candidate (for details see #294).

**Comment by spsaucier-bakkt** [comment]
The `7.0.0-rc2` version has fixed my issue 👍

**Comment by JeroenMols** [comment]
Thank you for letting us know!
