### ISSUE TITLE
After Generating Link Token, Invalid hook Call at <PlaidLink /> (rerenders page infinitely)

### ISSUE THREAD

**Issue by emi1337** [plaid/react-native-plaid-link-sdk#295]
Hey folks, I'm having trouble getting plaid set up. Apologies if I'm doing something wrong, but I can't see it.

I'm able to successfully generate a link token, and the RN renders the correct amount of times. As soon as I add the RN component <PlaidLink>, I get this issue, and the screen starts rerendering over and over (such that the isLoading useState that was already set to false, gets reset to true again as if the page is remounting or something).

# Environment
| Plaid Link React Native: 7.0.0-rc1
| ReactNative Version: 0.62.2
| Occurs on Android: YES
| Android Devices/Emulators: Pixel 3 physical
| Occurs on iOS: YES
| iOS Version: 13.5
| iOS Devices/Emulators: iPhone 11 emulator

# Steps to Reproduce
Starting with the following code in render works just fine and loads a generated token with an object like {link_token: 'blah', ...}. However, as soon as you un-comment-out the <PlaidLink /> code below, it gets the screenshot error (and starts refetching tokens/rerendering undlessly).

   ```
    // render():
    const [isLoadingLinkToken, setIsLoadingLinkToken] = useState(true);
    const [linkTokenData, setLinkTokenData] = useState(null);

    useEffect(() => {
        if (isLoadingLinkToken && !linkTokenData) {
            generateLinkToken(
                userID,
                userCountryCode,
                setIsLoadingLinkToken,
                setLinkTokenData,
            );
        }
    }, [linkTokenData, isLoadingLinkToken, userID, userCountryCode]);

    if (isLoadingLinkToken) {
        return <StyledLoadingSpinner />;
    }

    if (!linkTokenData || !linkTokenData.link_token) {
        return (
            <StyledText>
                We were unable to initialize Plaid. Please restart your app or
                contact support
            </StyledText>
        );
    }

    return (
        <View>
            {/* <PlaidLink
                tokenConfig={{token: linkTokenData.link_token}}
                onSuccess={() => {console.log('wtf')}}
                onExit={() => {console.log('wtf')}}> */}
                <Text>test</Text>
            {/* </PlaidLink> */}
        </View>
    );

// calling Plaid
const generateLinkToken = async (
    userID: string,
    userCountryCode: string,
    setIsLoadingLinkToken: (boolean) => void,
    setLinkTokenData: ({link_token: string}) => void,
): Promise<void> => {
    try {
        await MutationBankAccounts.getLinkToken(userID, userCountryCode).then(
            async (response) => {
                const generatedLinkToken = await response.json();
                setIsLoadingLinkToken(false);
                if (generatedLinkToken && generatedLinkToken.link_token) {
                    setLinkTokenData(generatedLinkToken);
                    return;
                }
                setLinkTokenData(null);
            });
    } catch (error) {
        Toasts.showErrorForLong('Could not initialize Plaid: ' + error.message);
        setIsLoadingLinkToken(false);
    }
};
```

url: https://sandbox.plaid.com/link/token/create

config: {
    android_package_name: 'OMITTED,
    client_id: PLAID_CLIENT_ID,
    client_name: 'OMITTED',
    language: 'en',
    products: ['auth'],
    secret: PLAID_CURRENT_VERSION.secret_key,
    user: {
            client_user_id: userID,
        },
    country_codes: [countryCode]
}

# Screenshots
<img width="486" alt="Screen Shot 2020-12-17 at 6 00 58 PM" src="https://user-images.githubusercontent.com/1188988/102554920-b53d5d80-4093-11eb-9ff9-715d97a51820.png">

Thanks so much in advance! Hope you're well and having a good holiday~

**Comment by BrandonCao** [comment]
Mine is able to generate except the app just becomes unresponsive

**Comment by JeroenMols** [comment]
I've looked into your issue, but am currently unable to reproduce.

Wondering whether there is a react native version mismatch. Could you please try to upgrade your react native version to `0.63.3`? And see if the problem persists?
https://github.com/plaid/react-native-plaid-link-sdk/blob/master/package.json#L48

**Comment by grantackerman1** [comment]
I'm having the same issue and am using react-native version 0.63.4, react-native-plaid-link-sdk version 7.0.0-rc2, and react version 17.0.1

**Comment by BrandonCao** [comment]
@JeroenMols I was able to get it to work. The only time it became unresponsive was when I wasn't running the app with a remote debugger.

**Comment by SravanthiGujjula** [comment]
I'm having the same issue. I am using react version 16.11.0, react-native version 0.63.4 and react-native-plaid-link-sdk version 7.0.0-rc2

**Comment by JeroenMols** [comment]
@BrandonCao That's great news! Do you happen to know what changes you made that resolved this?

That may help me reproduce and hopefully fix/avoid this issue in the future. Thank you!

**Comment by BrandonCao** [comment]
@JeroenMols I just tried it without remote debugger in the background haha. Although I was still able to continue development it's still inconvenient without being able to use debug mode. I'll keep messing around and if I find anything I'll post on here!

**Comment by emi1337** [comment]
> I've looked into your issue, but am currently unable to reproduce.
> 
> Wondering whether there is a react native version mismatch. Could you please try to upgrade your react native version to `0.63.3`? And see if the problem persists?
> https://github.com/plaid/react-native-plaid-link-sdk/blob/master/package.json#L48

Hey @JeroenMols, apologies for the delays. Am still able to repro on react-native 0.63.3. Thanks for looking into this!

**Comment by JeroenMols** [comment]
Hi @emi1337,

Sorry for the delay in getting back to you, but I was struggling to come up with a good next step to help you on this.

Some ideas would be:

- Can you try to disable the remote debugger in the background (like @BrandonCao )?
- Would it be possible for you to publish a basic sample project that reproduces this?
- Does this still happen on `7.0.0-rc2` (I assume it does, but good to check regardless)

Thank you,
Jeroen

**Comment by JeroenMols** [comment]
We've just published a new release [7.0.0-rc3](https://www.npmjs.com/package/react-native-plaid-link-sdk/v/7.0.0-rc3) that changes the way we depend on React Native and React. 

Can you please give that a try and see if it fixes this issue?

**Comment by gpbaculio** [comment]
@JeroenMols upgrading to  7.0.0-rc3 fixed it for me

**Comment by JeroenMols** [comment]
Awesome, thanks for letting us know.
