### ISSUE TITLE
onPress is not getting intercepted by PlaidLink component

### ISSUE THREAD

**Issue by cavalos0086** [plaid/react-native-plaid-link-sdk#297]
# The problem
In the docs, it is mentioned that `PlaidLink wraps the view you provide as a child with a Pressable component and intercepts the onPress event.` However:
1. The onPress doesn't get trigger.
2. The type definition for `PlaidLink` doesn't have an onPress props

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.0rc2                |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             | idk                |
| Android OS Version                    | Not Applicable                |
| Android Devices/Emulators    | Not Applicable                |
| Occurs on iOS     | yes                |
| iOS Version           | 14.3                |
| iOS Devices/Emulators               | iPhone 12 Pro Max                |

# Steps to Reproduce
You could use the following component:

```
export class Cards extends React.Component<IProps, IState> {
  constructor(props: IProps) {
    super(props);.
    this.state = {
      linkToken: '',
    };
  }

  addCard() {
    console.log('Adding a new card')
  }

  render() {
    return (
      <View style={{width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center'}}>
        <PlaidLink
          onPress={() => this.addCard()}
          tokenConfig={{token: this.state.linkToken}}
          onSuccess={this.exchangePublicToken.bind(this)}
          onExit={this.onExitPlaidFlow.bind(this)}
          >
              <View style={{justifyContent: 'center', alignItems: 'center'}}>
                <Text>Add Account</Text>
                <FontAwesomeIcon icon="plus-square" size={40}/>
              </View>
        </PlaidLink>
      </View>
    );
  }
}
```
 and you will see that the addCard method doesn't get called. 

# Expected Result
- onPress call gets executed.
- Typescript recognizes the onPress as a property to the `PlaidLink` component

# Screenshots
NONE

# Logs
NONE

# Code To Reproduce Issue 
Attached

**Comment by JeroenMols** [comment]
Hi @cavalos0086 ,

Thank you for reporting this issue. 

Just to clarify: your custom `onPress` logic doesn't get pressed, but does our SDK open the Link flow for you?

We currently add an `onPress` listener under the hood to the component you provide to us (e.g. a `View` in your case), but we don't offer the ability to also add your own custom `OnPress` logic when the button get pressed.

Some ideas for you to consider:

- We do offer a hook for Link events, which you can use to detect when Link gets opened and run your logic. (`usePlaidEmitter(linkEvent => console.log(linkEvent))`)
- You can technically call `openLink()` directly without using our `PlaidLink` component, though we don't advise doing that as some of the more complex Link flows may required additional setup (e.g. Deeplinks) and `openLink()` doesn't set those for you.

Please let me know if that resolves your issue!

**Comment by cavalos0086** [comment]
Hello @JeroenMols 
Thanks for the reply. Oh, I see, I miss understood the documentation. 

Maybe you could help me with how to launch Link then. In the docs, it mentions that we need to pass the `publick_token` when opening the Link flow, so I am stuck here:

At the moment my flow is this:
- Click the + button, this will trigger a backend call to get the public Token. This will display the `add account` message which is the View that the Plaid component is wrapping up. 
- Then the user will need to click the `add account` button to open the link flow. 

What I want to do is that the user will only need to press only one button. Seems to be related to [this](https://github.com/plaid/react-native-plaid-link-sdk/issues/9)

**CODE REFERENCE:**

```
<View style={{width: '100%', height: '100%', justifyContent: 'space-around', alignItems: 'center'}}>
          <View style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%'}}>
            <Pressable
              onPress={this.getPlaidLinkToken.bind(this)}>
              <FontAwesomeIcon icon="plus-square" size={40}/>
            </Pressable>
          </View>
          {
            this.state.linkToken ?
            <>
              <PlaidLink
                tokenConfig={{token: this.state.linkToken}}
                onSuccess={this.onPlaidSuccess.bind(this)}
                onExit={this.onExitPlaidFlow.bind(this)}
                onPress={() => this.callSomething()}
                >
                  <View style={{justifyContent: 'center', alignItems: 'center'}}>
                    <Text>Add Account</Text>
                  </View>
              </PlaidLink>
            </>
            :
            <></>
```

**Comment by JeroenMols** [comment]
To programmatically open Plaid Link, do the following after receiving the token:

```javascript
import { openLink } from "react-native-plaid-link-sdk";

let linkTokenProps: PlaidLinkProps = {
    tokenConfig: {
        token: "<INSERT_TOKEN>",
        logLevel: LinkLogLevel.ERROR
    },
    onSuccess: (success: LinkSuccess) => {
         // TODO
    },
    onExit: (linkExit: LinkExit) => {
        // TODO
    }
}

openLink(linkTokenProps)
```

However, this won't set up the deeplink redirector hook, so you need to make sure to call that yourself as well:
https://github.com/plaid/react-native-plaid-link-sdk/blob/3ad36fedb79cab6ffaaf89cbc720b4485c95bf7e/PlaidLink.tsx#L103

(Note that this hook is required to make OAuth work on iOS, so it's very important not to forget to set this.)

Please let me know if this helps.

**Comment by cavalos0086** [comment]
Gotcha!
Thanks! I'll give it a try.
