### ISSUE TITLE
Android Autolinking

### ISSUE THREAD

**Issue by Taylor123** [plaid/react-native-plaid-link-sdk#299]
# The problem

Android auto linking does not currently work.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.0-rc2                |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             | yes                |

## react-native config output
```
"react-native-plaid-link-sdk": {
      "root": "app/node_modules/react-native-plaid-link-sdk",
      "name": "react-native-plaid-link-sdk",
      "platforms": {
        "ios": {
          "sourceDir": "app/node_modules/react-native-plaid-link-sdk/ios",
          "folder": "app/node_modules/react-native-plaid-link-sdk",
          "pbxprojPath": "app/node_modules/react-native-plaid-link-sdk/ios/RNLinksdk.xcodeproj/project.pbxproj",
          "podfile": null,
          "podspecPath": "app/node_modules/react-native-plaid-link-sdk/react-native-plaid-link-sdk.podspec",
          "projectPath": "app/node_modules/react-native-plaid-link-sdk/ios/RNLinksdk.xcodeproj",
          "projectName": "RNLinksdk.xcodeproj",
          "libraryFolder": "Libraries",
          "sharedLibraries": [],
          "plist": [],
          "scriptPhases": []
        },
        "android": null
      },
      "assets": [],
      "hooks": {},
      "params": []
    },
```

# Expected Result
android react-native config should not be `null`

**Comment by JeroenMols** [comment]
Thank you for requesting this feature!

Looks interesting, we are going to look into adding support for this.

**Comment by JeroenMols** [comment]
We've managed to get autolinking work when we use `ReactPackage`, but not when we use `TurboReactPackage`.

Looking at the `react-native-community-cli` project it also seems like turbo packages aren't yet supported: https://github.com/react-native-community/cli/issues/356

So I wonder if both are mutually exclusive? 🤔 

@Taylor123  do you happen to know if we can support both autolinking and Turbo packages at the same time? Or do we have to choose one or the other?

**Comment by Taylor123** [comment]
I haven't personally used `TurboReactPackage`, so i'm not entirely sure. I'll be sure to post here if i gain any insight

**Comment by JeroenMols** [comment]
I've created a draft proposal that makes autolinking work (at the expense of app startup time). Please chime in with feedback and opinions.

**Comment by JeroenMols** [comment]
We've decided to stick to turbo modules for now as faster app initialization outweighs the easier integration (especially on the longer term)

In the future we may decide to revise this or to add auto linking support for Turbo Modules. (when that becomes possible)

**Comment by Taylor123** [comment]
@JeroenMols Makes sense, thanks for taking the time to look into this
