### ISSUE TITLE
onSuccess Payload Type Discrepancy

### ISSUE THREAD

**Issue by jackmaris** [plaid/react-native-plaid-link-sdk#3]
On iOS it's a JSON object, while on Android it's a string that you have to call JSON.parse on

**Comment by zachrnolan** [comment]
This is a little annoying, but definitely a workaround to use JSON.parse on Android. 

I've also noticed that the payload for the event listener uses different keys for the event name. iOS uses `event` while Android uses `event_name`. Little things like this force us to sprinkle in Platform checks.

**Comment by wkiefer** [comment]
Thanks for the report — we'll have a fix for this going out on Monday.

**Comment by zsweigart** [comment]
Thanks for the feedback! We are going to update `event_name` to `event` and change the return type to a JSONObject in the next release

**Comment by wkiefer** [comment]
Fixed in https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v2.0.1
