### ISSUE TITLE
iOS application not start after adding plaid

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#30]
Can anyone help me to setup plaid in iOS, added plaid package and follow all step provided in readme file
According to readme file go to node_modules ➜ react-native-linksdk and add RNLinksdk.xcodeproj but `react-native-linksdk` directory not found in node_modules so i added from `react-native-plaid-link-sdk`

Please find following sample git repository and branch `ios-setup`
https://github.com/kanji-keraliya/RNPlaidExample/tree/ios-setup

**Comment by kanji-keraliya** [comment]
@wkiefer  Can anyone help me to setup plaid in iOS. I tried all steps given in readme file but not success. Can any one help me setup Plaid step by step.

Thanks

**Comment by wkiefer** [comment]
Your Podfile is incorrect here:
https://github.com/kanji-keraliya/RNPlaidExample/blob/ios-setup/ios/Podfile#L38

It should be `pod 'Plaid', '~> 1.1.25'`

Please see the [README](https://github.com/plaid/react-native-plaid-link-sdk#ios) and make sure you've followed the same steps. thanks!
