### ISSUE TITLE
Getting "require cycle" warning when creating a <PlaidLink> component with RN fetch API being used in both 'componentDidMount' and <PlaidLink> 'onSuccess' handler

### ISSUE THREAD

**Issue by QO-Development** [plaid/react-native-plaid-link-sdk#301]
# The problem

I am attempting to do three things with my custom component: 

1. Fetch a link token from /link/token/create using the Plaid API + my server in componentDidMount.
2. After the link token is fetched from the API, update the state in my custom component to include the token and render <PlaidLink> with the token included in the tokenConfig object. 
3. After the user enters their banking credentials, fetch a permanent token inside the 'onSuccess' handler of the <PlaidLink> component using the Plaid API + my server. 

When I include calls to the React Native fetch API inside both componentDidMount and the 'onSuccess' handler I get a warning that says 'Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.'. 

fetch will work to retrieve the link token, but when I try to call fetch to retrieve the permanent token I then get the error: 'TypeError: undefined is not a function (near '...fetch...')' 

# Environment

react-native: 0.63.3
react-native-plaid-link-sdk: ^7.0.0-rc2
iOS 14.3 
iOS Emulator: iPhone 11

# Steps to Reproduce

1. Call fetch in componentDidMount. 
2. Call fetch in 'onSuccess' 

# Expected Result
What did you expect to happen?

I expected no require cycles and fetch to work just fine.

# Screenshots
If this is a visual bug a screenshot would be helpful.

# Logs
Any relevant logs from Android Logcat or the iOS console including stacktraces.

[Thu Jan 07 2021 12:04:49.906]  WARN     Require cycle: node_modules/react-native-plaid-link-sdk/node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native-plaid-link-sdk/node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Thu Jan 07 2021 12:04:49.918]  WARN     Require cycle: node_modules/react-native-plaid-link-sdk/node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native-plaid-link-sdk/node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Thu Jan 07 2021 12:04:49.921]  WARN     Require cycle: node_modules/react-native-plaid-link-sdk/node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native-plaid-link-sdk/node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Thu Jan 07 2021 12:04:49.924]  ERROR    TypeError: undefined is not a function (near '...fetch...')

# Code To Reproduce Issue 
```javascript
import React from 'react';
import {StyleSheet, View, Text} from 'react-native';
import {API_URL} from '../models/enums';

import {PlaidLink} from 'react-native-plaid-link-sdk';

class SettingsModal extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      token: null,
    };
  }

  componentDidMount() {
    fetch(API_URL + '/linkToken')
      .then((response) => response.json())
      .then((json) => {
        this.setState({
          token: json.token,
        });
      })
      .catch((e) => {
        console.log('error fetching link token');
        console.log(e);
      });
  }

  render() {
    let buttonArea;

    if (!this.state.token) {
      buttonArea = <Text>Why does this cause an error?</Text>;
    } else if (this.state.token) {
      buttonArea = (
        <>
          <PlaidLink
            tokenConfig={{
              token: this.state.token,
            }}
            onSuccess={(success) => {
              fetch(API_URL + '/plaidPermanentToken', {
                method: 'POST',
                headers: {
                  Accept: 'application/json',
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                  value: success.publicToken,
                }),
              });
            }}>
            <View style={styles.button}>
              <Text style={styles.textStyle}>Add Account</Text>
            </View>
          </PlaidLink>
        </>
      );
    }

    return <View style={styles.buttonContainer}>{buttonArea}</View>;
  }
}

const styles = StyleSheet.create({
  button: {
    backgroundColor: 'purple',
    height: 50,
    justifyContent: 'center',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
  },
  buttonContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
  },
});

export default SettingsModal;

```

**Comment by dtroupe-plaid** [comment]
Closing because Plaid Link React Native 7.x.x is no longer supported. If the issue persists in the latest SDK please open a new issue.
