### ISSUE TITLE
[React-native-plaid-link-sdk] null account information is returned in sandbox environment for ios. Account_id is null.

### ISSUE THREAD

**Issue by asadkaleememumba** [plaid/react-native-plaid-link-sdk#303]
react-native-plaid-link-sdk: 3.0.1
ios-sdk pod 'Plaid', '~> 1.1.36'
environment: 'sandbox'
react-native: .63.4
ios:13
xcode: 11.6

Issue: user_good and pass_good are used as credentials for sandbox environment, but still getting **account_id: null**.

Received response:
 ```
{
  "status": "connected",
  "link_session_id": "xxx",
  "institution": {
    "institution_id": "ins_3",
    "name": "Chase"
  },
  "accounts": [
    {
      "id": null,
      "mask": "1111",
      "name": "Plaid Saving",
      "subtype": "savings",
      "type": "depository"
    }
  ],
  "account": {
    "id": null,
    "mask": null,
    "name": null,
    "subtype": null,
    "type": null
  },
  "request_id": null,
  "public_token": "public-sandbox-xxx-xxx-xxx",
  "account_id": null
}
```

**Comment by amytang0** [comment]
Hi, 3.x is 3 major releases behind our latest stable release and thus is no longer receiving updates. Could you try updating to 6.0.4? Thanks!

**Comment by asadkaleememumba** [comment]
@amytang0 it working on 6.0.4. Thanks
