### ISSUE TITLE
[ios] Webhook not passed - 6.0.4

### ISSUE THREAD

**Issue by edo1493** [plaid/react-native-plaid-link-sdk#304]
# The problem

After upgrading to 6.0.4 (Plaid 2.0.9), Plaid is not hitting our webhook any longer.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 6.0.4                |
| ReactNative Version     | e.g. 0.63.3                |
| Occurs on iOS     | e.g. yes                |
| iOS Version           | e.g. 11                |
| iOS Devices/Emulators               | e.g. iPhone X                |

# Steps to Reproduce

We are opening Plaid link in this way.

```
        openLink({
          onExit,
          onSuccess,
          clientName: client_name,
          publicKey: key,
          env,
          webhook: webhook_uri,
          product: products,
          language,
          countryCodes: country_codes,
          linkCustomizationName: link_customization_name,
          webviewRedirectUri: 'emma://loginsuccess',
        });
```
On Android everything is working, but on iOS we can't sync the connection because it seems Plaid is not receiving our "webhook_uri" any longer.

# Expected Result
We would expect the webhook to trigger just like on Android.

If I downgrade to 5.0.1 and Plaid 1.1.34, everything just works fine.

# Screenshots

We can see from the plaid dashboard that the webhook is no longer being passed - we were on 5.0.1 before this upgrade.

<img width="521" alt="Screenshot 2021-01-14 at 17 20 44" src="https://user-images.githubusercontent.com/2309030/104625658-de4e0f80-568c-11eb-8e54-8b8c9eb2de38.png">

**Comment by pladaub** [comment]
Hi, I've confirmed this is an issue in the LinkKit dependency. We're working on a fix, and will close this issue once it is released. Thanks for the report!

**Comment by edo1493** [comment]
Do you have a timeline?

**Comment by edo1493** [comment]
Same here, like are we expected to work with something that breaks randomly?

**Comment by pladaub** [comment]
Hi, this has been fixed in RN v7-rc4 and is available now, apologies for not updating this ticket earlier and thanks again for filing.
