### ISSUE TITLE
Handoff stopped firing on Android 5.0.1

### ISSUE THREAD

**Issue by edo1493** [plaid/react-native-plaid-link-sdk#307]
# The problem

After the Christmas break, we have noticed our HANDOFF event doesn't fire anymore on Android. We are noticing a similar behaviour in production where on some Android devices it doesn't fire at all.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 5.0.1                |
| ReactNative Version     | e.g. 0.63.3                |
| Occurs on Android             | e.g. yes                |

# Steps to Reproduce

We are using RN Plaid 5.0.1 and the Android SDK 2.0.0.

This is how we open Plaid:
```
        openLink({
          onExit,
          onSuccess,
          clientName: client_name,
          publicKey: key,
          env,
          webhook: webhook_uri,
          product: products,
          language,
          countryCodes: country_codes,
          linkCustomizationName: link_customization_name,
          webviewRedirectUri: 'emma://loginsuccess',
        });
```

This is how we listen to events. They all come through apart from HANDOFF (this works on iOS).

```
 const emitter = new NativeEventEmitter(Platform.OS === 'ios' ? NativeModules.RNLinksdk : NativeModules.PlaidAndroid);
  this._listener = emitter.addListener('onEvent', this._onHandlePlaid);
```

# Expected Result

Handoff firing after the user has completed the login.

**Comment by zsweigart** [comment]
Hi @edo1493 Could you try upgrading to the latest stable version of the SDK (6.0.4). You can find the upgrade guide on our [docs page](https://plaid.com/docs/link/react-native/react-native-v5-v6-migration/).

**Comment by edo1493** [comment]
If I upgrade, Handoff fires on Android, but then I have the webhook not passed issue, which I have filed here: https://github.com/plaid/react-native-plaid-link-sdk/issues/304.

**Comment by zsweigart** [comment]
Thanks for letting us know, we'll be releasing a fix for #304 soon then this issue should be resolved as well.

**Comment by edo1493** [comment]
Any ETA?

**Comment by edo1493** [comment]
Like you broke our build in production and are not fixing it.

**Comment by amytang0** [comment]
Hey, sorry for the frustrating experience so far. I'm curious what you're using the HANDOFF events for?

Android `< 3.1.1` (which is what `5.0.1` is using) never output `HANDOFF` events; we instead provided `LinkResultHandler` with `onSuccess` and `onExit` listeners.  If possible, we recommend you you instead pass in the `onSuccess` and `onExit` callbacks.

Additionally, we are aiming to get 7.0 out next week, which should solve the [webhook issue](https://github.com/plaid/react-native-plaid-link-sdk/issues/304).

**Comment by amytang0** [comment]
Thanks for your patience, [7.0.0](https://www.npmjs.com/package/react-native-plaid-link-sdk/v/7.0.0) is out now!
