### ISSUE TITLE
version 2.0.4 does not work on android

### ISSUE THREAD

**Issue by Mande3p** [plaid/react-native-plaid-link-sdk#31]
Version 2.0.4 does not open anything on click of PlaidLink on android, reverted back to 2.0.3 and it works fine. Please look into it.

**Comment by osikes** [comment]
2.0.4 works for me , make sure your app build.gradle has ' implementation 'com.plaid.link:sdk-core:0.3.2''

**Comment by zsweigart** [comment]
Correct. 2.04 with com.plaid.link:sdk-core:0.3.2 is the right setup.  Do you have any log messages?  Is your webviewRedirectUri whitelisted? Currently the Uri is case sensitive but we are looking to update that soon.

**Comment by tribou** [comment]
Not sure if this is related, but I wanted to post in case it helps. I'm getting an error when trying to press on Android with v2.0.4... I think this is the relevant part of the error log:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.plaid.linkbase.data.models.LinkClientGetResponseSuccess com.plaid.linkbase.data.models.LinkClientGetResponse.getLinkClientGetResponseSuccess()' on a null object reference
        at com.plaid.link.root.LinkRootInteractor$refreshFeatures$1.accept(LinkRootInteractor.kt:171)
        at com.plaid.link.root.LinkRootInteractor$refreshFeatures$1.accept(LinkRootInteractor.kt:45)
        at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onError(SingleDoOnEvent.java:68)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
```

Reverting to v2.0.3 resolves the issue for me as well.

**Comment by tribou** [comment]
...for some reason, the iOS app does not throw any errors when using an invalid webview_redirect_uri 🤔 I was able to successfully complete the linking process on iOS with an unauthorized webview_redirect_uri.

Why is this blocking only on android? 😕

**Comment by osikes** [comment]
@tribou did you follow the steps int the readme ? 


> To register your redirect uri:
> Log into your Plaid Dashboard
> Select API under Team Settings in the top navigation bar
> Click configure then Add New Uri then enter your Uri (for example yourAppName://redirect)
> Click Save Changes

**Comment by mikeislearning** [comment]
@osikes This fixed my issue, thank you! It turns out I needed to add 2 redirect uris, one for my production app, one for my staging one

**Comment by tribou** [comment]
@osikes Registering the redirect URI fixes the crash on Android!

However, I'm still confused as to why the iOS SDK doesn't require a redirect URI to successfully register an account but the Android SDK does. Is this a bug?

**Comment by osikes** [comment]
@tribou i can’t really speak for this library, but iOS and android simply have different redirecting strategies so, and only android requires a redirect url is my understanding .

**Comment by zsweigart** [comment]
Hi in the latest release 3.0 which includes our first non-beta Android sdk release you no longer need the webview redirect uri, instead you will need to register you android app id on the dashboard. plaid.com/docs/link/android/#register-app-id
