### ISSUE TITLE
"Select account" screen - need to make an extra drag to uncover the "Don't see your bank?" CTA

### ISSUE THREAD

**Issue by a613** [plaid/react-native-plaid-link-sdk#312]
# The problem

On both Android and iOS, the CTA at the bottom of the account selection screen - need to make an extra drag to uncover the CTA

all notchless screens, both physical and emulators devices (e.g. iPhone 11, Android S10)

not version-specific, all iOS and Android ver are affected

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4           |
| ReactNative Version     | 0.63.3           |
| Occurs on Android             | yes           |
| Android OS Version                    | Android 11 and 7            |
| Android Devices/Emulators    | both physical and emulators devices (e.g. Android S10) |
| Occurs on iOS     | yes        |
| iOS Version           | iOS 14 and 11            |
| iOS Devices/Emulators               | both physical and emulators devices (e.g. iPhone 11)          |

# Steps to Reproduce

1. tap “Continue” on Plaid Terms
1. expect to land on the FI selection screen, scroll all the way down
1. Observe on the smaller screens "Don't see your bank?..." on the notchless device need to make an extra drag to uncover the CTA

# Expected Result

Swiping up brings the CTA into full view, then tapping it opens the search view.

# Screenshots

https://user-images.githubusercontent.com/5733420/105359256-3de47780-5bc5-11eb-8500-79e1e49948a1.MP4

# Logs

N/A

# Code To Reproduce Issue 

```jsx
<Wrapper>
  <PlaidLink
    token={token || 'placeholder'}
    onSuccess={onSuccess}
    onCancelled={onExit}
    onExit={onExit}
    component={TokenAwareButton}
    componentProps={{ haveToken: !!token, plaidFlowInProgress }}
  >
    {plaidFlowInProgress ? 'PROCESSING' : 'CONTINUE'}
  </PlaidLink>
</Wrapper>
```

```typescript
const Wrapper = styled.View`
  width: 100%;
`;
```

**Comment by JeroenMols** [comment]
Thank you for reporting this!

Let me check internally and see if/what we should do about this.

**Comment by amytang0** [comment]
Closing ticket as a no-op. We've given this feedback to our team and are opting for the current design
