### ISSUE TITLE
"Select account" screen - "Don't see your bank?" CTA can’t be tapped

### ISSUE THREAD

**Issue by a613** [plaid/react-native-plaid-link-sdk#313]
# The problem

On both Android and iOS, the CTA at the bottom of the account selection screen can’t be tapped

all smaller screen, both physical and emulators devices with a button (e.g. iPhone 8 or Galaxy S7)

not version-specific, all iOS and Android ver are affected

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4           |
| ReactNative Version     | 0.63.3           |
| Occurs on Android             | yes           |
| Android OS Version                    | Android 11 and 7            |
| Android Devices/Emulators    | both physical and emulators devices with a button (e.g. Galaxy S7) |
| Occurs on iOS     | yes        |
| iOS Version           | iOS 14 and 11            |
| iOS Devices/Emulators               | both physical and emulators devices with a button (e.g. iPhone 8)          |

# Steps to Reproduce

1. tap “Continue” on Plaid Terms
1. expect to land on the FI selection screen, scroll all the way down
1. Observe on the smaller screens "Don't see your bank?..." isn’t tappable

# Expected Result

Swiping up brings the CTA into full view, then tapping it opens the search view.

# Screenshots

https://user-images.githubusercontent.com/5733420/105359243-3a50f080-5bc5-11eb-8f1d-242988609758.MP4

# Logs

N/A

# Code To Reproduce Issue 

```jsx
<Wrapper>
  <PlaidLink
    token={token || 'placeholder'}
    onSuccess={onSuccess}
    onCancelled={onExit}
    onExit={onExit}
    component={TokenAwareButton}
    componentProps={{ haveToken: !!token, plaidFlowInProgress }}
  >
    {plaidFlowInProgress ? 'PROCESSING' : 'CONTINUE'}
  </PlaidLink>
</Wrapper>
```

```typescript
const Wrapper = styled.View`
  width: 100%;
`;
```

**Comment by JeroenMols** [comment]
Thank you for reporting this!

Let me check internally and see if/what we should do about this.

**Comment by amytang0** [comment]
Can't repro as of today, please re-open if this issue still recurs
