### ISSUE TITLE
400 and crash when trying to open Plaid on Android

### ISSUE THREAD

**Issue by a613** [plaid/react-native-plaid-link-sdk#314]
# The problem

Seeing a 400 from https://production.plaid.com/link/client/get when launching Plaid, which results in Plaid crashing.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4            |
| ReactNative Version     | 0.63.3      |
| Occurs on Android             | yes         |
| Android OS Version                    | 10           |
| Android Devices/Emulators    | Samsung S10e physical             |
| Occurs on iOS     | no             |
| iOS Version           | N/A           |
| iOS Devices/Emulators               | N/A            |

# Steps to Reproduce

Launch plaid flow

# Expected Result

flow opens on screen to select institution

# Screenshots

N/A

# Logs

N/A

# Code To Reproduce Issue 

Our flow:

1. request link token from Plaid
2. launch plaid with link token

```jsx
<PlaidLink
  token={token || 'placeholder'}
  onSuccess={onSuccess}
  onCancelled={onExit}
  onExit={onExit}
  component={TokenAwareButton}
  componentProps={{ haveToken: !!token, plaidFlowInProgress }}
>
  {plaidFlowInProgress ? 'PROCESSING' : 'CONTINUE'}
</PlaidLink>
```

**Comment by afh** [comment]
Thank you for reporting @a613, we're looking into it.

**Comment by amytang0** [comment]
Closing this issue, reiterating the solution for other customers who may run into this. Please check the error that is being returned in the LinkExit, and to ensure that the dashboard contains your Android package name. Thank you!
