### ISSUE TITLE
Empty accounts array from certain geolocation

### ISSUE THREAD

**Issue by Taylor123** [plaid/react-native-plaid-link-sdk#317]
# The problem

Receiving an `onSuccess` callback with no accounts in the array when the user is in Hong Kong. Running through the same steps on the same account from a US user works fine.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.0-rc3                |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             | Not sure yet                |
| Occurs on iOS     | yes                |
| iOS Version           | 14.3                |
| iOS Devices/Emulators               | iPhone X                |

# Steps to Reproduce

Using a vpn located in Hong Kong, go through the normal Plaid Link flow.

```
{
      clientName: 'Name',
      environment: PlaidEnvironment.PRODUCTION,
      products: [
        PlaidProduct.AUTH,
        PlaidProduct.IDENTITY,
        PlaidProduct.TRANSACTIONS,
      ],
      publicKey: PLAID_PUBLIC_KEY,
      language: 'en',
      countryCodes: ['US'],
    }
```

# Expected Result
Plaid Link's `onSuccess` callback to have the expected account(s).

Are there restrictions for certain territories by IP?

**Comment by thuat410** [comment]
We have the same issue with locate Vietnam. We cần not get account array in onSuccess callback.

**Comment by JeroenMols** [comment]
Could you provide us with a link session id so we can have a look at our systems?

**Comment by Taylor123** [comment]
@JeroenMols `e81b3f42-e3b3-4416-aef1-046e842fc194`

**Comment by Taylor123** [comment]
@JeroenMols Is there any update on this issue? Thanks!

**Comment by JeroenMols** [comment]
Sorry for the delay.

I've moved the issue to our internal tracking system and hope we can have a look at it soon.
(this likely isn't mobile related, so I need help of backend folks)

**Comment by amytang0** [comment]
Hi Taylor, it looks like this session was caught by our risky/malicious behavior algorithm. If you see another session with empty accounts, please re-open this issue
