### ISSUE TITLE
self.clientName is , but must be a properly formatted, non-empty string

### ISSUE THREAD

**Issue by Jpmaloiv** [plaid/react-native-plaid-link-sdk#318]
[
![plaid-error](https://user-images.githubusercontent.com/3642879/106974056-e5ef5a00-6708-11eb-92d8-675e186638c1.png)
](url)

Using standard Plaid Link format, was working fine until a few days ago. Have tried specifying clientName in link configuration but to no avail. Any ideas? Thanks

**Comment by amytang0** [comment]
Hey would you mind using the [bug report template](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)? 

Based on the screenshot, it looks like you're using iOS, is this happening only there or also on Android?

What versions of the SDK are you using?

**Comment by brittneykernan** [comment]
@Jpmaloiv what was the solution? Also running into this on iOS after customizing Link by adding Select Account. Disabling this did not resolve.

react-native-plaid-link-sdk version 7.0.0, rn 0.63.4. yarn cache reset and app delete + reinstall, and erase sim data aren't resolving this issue.

**Comment by vaughansharman** [comment]
Hi, @Jpmaloiv 

Can you please share what the solution is? We are also experiencing

**Comment by cryptoman04** [comment]
Any updates on this? I am having the same problem.

**Comment by taxidermic** [comment]
Has anyone solved it since?

**Comment by Jpmaloiv** [comment]
Hi guys, sorry it's been a while, if I recall correctly it was a versioning issue. At the time I believe it was a new update that was fixed in a version like a month later. I would try downgrading the version and corresponding Plaid pod. I also recall that it happened when I tried to call what I think was the openPlaidLink() method instead of using the <PlaidLink /> component
