### ISSUE TITLE
Link update mode?

### ISSUE THREAD

**Issue by mgm-self** [plaid/react-native-plaid-link-sdk#32]
I am working on implementing PlaidLink in React Native Android app. The new link case works fine for me but I am running into bugs with link update case.

Following tag results in regular new link mode. That is, I see the bank selector and I got a new public token once I complete the sign up.
`<PlaidLink token={currentLink.publicToken}>...</PlaidLink>`

I tried using publicToken as property name, as below
`<PlaidLink publicToken={currentLink.publicToken}>...</PlaidLink>`

That fails to open Plaid modal and my onExit handler is invoked with error
`{"message":"The public token provided is not formatted correctly","class":"com.plaid.linkbase.models.PlaidLinkConfigurationInvalidTokenException"}`
The publicToken is a string like "public-sandbox-98f6c2bd-b916-43ff-a153-xxxxxxxxxxxx" and it looks correctly formatted for me.

Version: 2.0.4
Platform: Android

**Comment by zsweigart** [comment]
Thanks for the report, we have found the issue and will be fixing it soon.

**Comment by vafada** [comment]
@mgm-self see #55

**Comment by zsweigart** [comment]
The Issue has been fixed in version 3.0
