### ISSUE TITLE
Plaid Link crashes whole host app when opening link a second time on Android

### ISSUE THREAD

**Issue by curtismgt** [plaid/react-native-plaid-link-sdk#323]
# The problem

When Link opens subsequent times on Android 10 (tested on 7, 9, 10, 11), whole react native app crashes. No native error or javascript error is thrown/catchable. ADB Logcat results in `chromium: [ERROR:context_group.cc(433)] ContextResult::kFatalFailure: too few uniforms or varyings supported.` multiple times while Link shows a spinner before crashing.

Found this link while trying to troubleshoot
https://stackoverflow.com/questions/63869914/android-webview-chromium-exception-contextresultkfatalfailure-too-few-unifo

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4   &   7.0.0-rc4             |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             | yes                |
| Android OS Version                    | 10                |
| Android Devices/Emulators    | Pixel 3 emulator                |
| Occurs on iOS     | no               |
| iOS Version           | N/A               |
| iOS Devices/Emulators               | N/A                |

# Steps to Reproduce

Open Plaid link, complete process successfully. Open Link again using different token, crashes.

# Expected Result
Plaid Link should be able to open multiple times in a row as long as it's been given a different link token every time.

# Screenshots

# Logs
`02-16 13:52:47.081 14578 15024 E chromium: [ERROR:context_group.cc(433)] ContextResult::kFatalFailure: too few uniforms or varyings supported.
02-16 13:52:47.098 14578 15024 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008b49
02-16 13:52:47.099 14578 15024 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008b49
02-16 13:52:47.101 14578 15024 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008b4b
02-16 13:52:47.101 14578 15024 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008b4b
02-16 13:52:47.104 14578 15024 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008b4a
02-16 13:52:47.105 14578 15024 E eglCodecCommon: glUtilsParamSize: unknow param 0x00008b4a
`

# Code To Reproduce Issue

**Comment by zsweigart** [comment]
Hi @curtismgt, thanks for the report! I have been able to reproduce the issue with the sample in this repository. Have you been able to reproduce it there?

**Comment by curtismgt** [comment]
@zsweigart I will try and reproduce this using the sample here

**Comment by curtismgt** [comment]
@zsweigart @JeroenMols 
We figured it out. Just took us a couple of days. The problem is with an out of date Chrome browser. OOTB the Android 10 emulator build comes with a bugged Chrome browser. After updating it from the app store/play store, everything works as expected. Sorry for the waste of time.

**Comment by JeroenMols** [comment]
Glad you were able to figure this out, well done!
