### ISSUE TITLE
Logs warn about deprecated public_key but we've already migrated to link tokens

### ISSUE THREAD

**Issue by a613** [plaid/react-native-plaid-link-sdk#328]
# The problem

Even though we have migrated to link tokens, the SDK is still logging warnings about public_key being deprecated, which is misleading.

> The public_key is being deprecated. Learn how to upgrade to link_tokens at https://plaid.com/docs/#create-link-token

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.4            |
| ReactNative Version     | 0.63.3           |
| Occurs on Android             | yes       |
| Android OS Version                    | 11             |
| Android Devices/Emulators    | Pixel 3a emulator                |
| Occurs on iOS     | yes          |
| iOS Version           | 14.4          |
| iOS Devices/Emulators               | iPhone 11 simulator              |

# Steps to Reproduce

Begin plaid link flow, look at logs

# Expected Result

No warning about public_key use, because there is none.

# Screenshots

N/A

# Logs

> The public_key is being deprecated. Learn how to upgrade to link_tokens at https://plaid.com/docs/#create-link-token

# Code To Reproduce Issue 

N/A

**Comment by JeroenMols** [comment]
Thank you for reporting!

With our upgrade to 7.0.0 we've removed this warning by mistake, so upgrading should fix your issue.
We'll add this warning again and make sure it doesn't occur when using public tokens.
