### ISSUE TITLE
Avoid hardcoding pubkey in AndroidManifest and load it from Js as for iOS?

### ISSUE THREAD

**Issue by lcareto** [plaid/react-native-plaid-link-sdk#33]
For iOS, the configuration to open the PlaidLink can be loaded from Javascript code, while Android requires to add additional codes in **AndroidManifest**.
Even if I can use the `manifestPlaceholders` properties in `build.gradle`, we have the requirement to load the **entire** Plaid configuration dynamically from the server, therefore I'm looking for a way to avoid having the pubKey hardcoded in AndroidManifest.

**Comment by zsweigart** [comment]
You can load the public key dynamically as part of the `Plaid.create(...)` call plaid.com/docs/link/android/#initialize-plaidlink-options

**Comment by zsweigart** [comment]
In version 3.0 you will now use `Plaid.setPublicKey(...)` see the [docs](plaid.com/docs/link/android/#initialize-plaidlink-options)
