### ISSUE TITLE
Android resource linking failure (drawable tint)

### ISSUE THREAD

**Issue by alexandrasmith00** [plaid/react-native-plaid-link-sdk#331]
# The problem

Upgrading our SDK to 7.0.0 and am getting a compile error regarding a missing attribute `drawableTint`

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.0          |
| ReactNative Version     | 0.63.4           |
| Occurs on Android             | yes           |

# Steps to Reproduce

Upgrading to 7.0.0 SDK from earlier 3.2.0 and unable to build the android app using the react native build script.

Example error:
```
* What went wrong:
Execution failed for task ':app:processDevDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/XXX/.gradle/caches/transforms-2/files-2.1/fb393748b35e6f93f8f239bafea064ce/jetified-sdk-core-3.2.3/res/layout/plaid_selling_point.xml:10: AAPT: error: attribute drawableTint (aka com.XXX.dev:drawableTint) not found.
```

**Comment by amytang0** [comment]
Hi Alexandra, would you mind sharing what version of androidx.appcompat you're using? Potentially something to try is to add `implementation "androidx.appcompat:appcompat:1.2.0"` to your `build.gradle`

**Comment by alexandrasmith00** [comment]
Thanks for the help, Amy! Turns out I had a different version in my `build.gradle` and simply removing it did the trick
