### ISSUE TITLE
OauthConfiguration not under LinkTokenConfiguration?

### ISSUE THREAD

**Issue by lucasjohnston** [plaid/react-native-plaid-link-sdk#332]
Currently upgrading from Link 5.0.1 to 7.0.0.

I'm a bit confused why your docs say `You must not use the oauthNonce or oauthRedirectUri` ([see here](https://plaid.com/docs/link/react-native/react-native-v5-v7-migration/)) and that we should `migrate to a token configuration` when your LinkToken integration doesn't support OAuth?

At least that's what the TS bindings say - OAuth callbacks are only supported when using the old PublicKey config:
<img width="687" alt="Screenshot 2021-02-22 at 12 07 10" src="https://user-images.githubusercontent.com/24899791/108707184-916d1c80-7507-11eb-8104-3018c4bbd227.png">

If the the Link SDK needs reinstantiating after the callback, can you clarify why we have to use the PublicKey namespace config to do this? Why isn't `oauthConfiguration` an option under `LinkTokenConfiguration`, given that the connection is being created with a link token?

Or am I missing something - are OAuth states handled automatically in 7.x? Thanks :)

**Comment by lucasjohnston** [comment]
Ha. Just spotted this in the [Link SDK docs](https://plaid.com/docs/link/oauth/) as soon as I posted this.
> "The oauthStateId prop is no longer needed, and will be ignored, as of v6.0.0 of the React Native Plaid Link SDK."

Your [upgrade](https://plaid.com/docs/link/react-native/react-native-v5-v7-migration/) docs do still say this though:
> "oauthNonce, oauthRedirectUri and **oauthStateId** are now encapsulated in oauthConfiguration"

Probably worth making the dropping of `stateId` clear in the upgrade docs as it's a pretty big change (and taking out the `oauthConfiguration` line given it's not correct) 🙂

**Comment by amytang0** [comment]
Hey sorry about that and thanks for the flag! We're updating our docs to make the change clearer

**Comment by lucasjohnston** [comment]
No worries, thanks! :)
