### ISSUE TITLE
v7 will crash on all RN versions < 0.63

### ISSUE THREAD

**Issue by yawnr** [plaid/react-native-plaid-link-sdk#334]
# The problem

`PlaidLink` now crashes on RN versions < `0.63` since the launcher is now wrapped in a `Pressable` (which was introduced in `v0.63`) instead of a `TouchableOpacity`.

Related: having a RN peer dep of version >=0.61 is incorrect.

The most reasonable fix would probably be to keep the peer dep the same and reverting to the `TouchableOpacity` so it doesn't break for everyone not on 63 yet.

Thanks!

**Comment by JeroenMols** [comment]
This is awesome, thank you for the clear explanation. 🙇 

Enforcing a minimum RN version of `0.63` feels to aggressive, so I agree with your suggestion.
