### ISSUE TITLE
Could not resolve pro.streem.pbandk:pbandk-runtime-android

### ISSUE THREAD

**Issue by OnurVar** [plaid/react-native-plaid-link-sdk#348]
# The problem

Hello. Latest version(7.0.1) is failing to build on Android Studio. It might be related with [this issue on plaid-link-android](https://github.com/plaid/plaid-link-android/issues/139). I tried the suggested workaround but still no luck.

> Execution failed for task ':react-native-plaid-link-sdk:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-plaid-link-sdk:debugCompileClasspath'.
   > Could not resolve pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2.
     Required by:
         project :react-native-plaid-link-sdk > com.plaid.link:sdk-core:3.2.5
      > No matching variant of pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2 was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'metadataApiElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'
              - Other compatible attribute:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Variant 'releaseApiElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2 declares an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'
          - Variant 'releaseRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2 declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.1                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             |  yes                |
| Occurs on iOS     | no                |

**Comment by a613** [comment]
Reproduced. This is blocking our upgrade from 6.x to 7.x.

**Comment by OnurVar** [comment]
Downgrading 7.0.0 seems like fixing the issue for now.

**Comment by amytang0** [comment]
Hi, sorry about that errant build requirement! In the meantime, you can continue to use `7.0.2` if you include 
```
implementation("com.plaid.link:sdk-core:3.2.3") {
    force true
}
```
in your `build.gradle` file. We are in the process of releasing `3.2.6` this week which will remove that build requirement as well

**Comment by a613** [comment]
> you can continue to use `7.0.2` if you include
> 
> ```
> implementation("com.plaid.link:sdk-core:3.2.3") {
>     force true
> }
> ```
> 
> in your `build.gradle` file

Did that work for you? The build crashes for a different reason when I try that:

```
Execution failed for task ':app:lintVitalQa'.
> Could not resolve all artifacts for configuration ':react-native-plaid-link-sdk:debugRuntimeClasspath'.
   > Could not resolve pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2.
     Required by:
         project :react-native-plaid-link-sdk > com.plaid.link:sdk-core:3.2.5
      > Unable to find a matching variant of pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
          - Variant 'metadataApiElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible attributes:
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found incompatible value 'common'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
          - Variant 'releaseApiElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
          - Variant 'releaseRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible attribute:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
```

**Comment by a613** [comment]
> you can continue to use `7.0.2` if you include
> 
> ```
> implementation("com.plaid.link:sdk-core:3.2.3") {
>     force true
> }
> ```
> 
> in your `build.gradle` file

Not working - the build fails for basically the same reason (and 3.2.5 is still referenced):

```
Execution failed for task ':app:lintVitalQa'.
> Could not resolve all artifacts for configuration ':react-native-plaid-link-sdk:debugRuntimeClasspath'.
   > Could not resolve pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2.
     Required by:
         project :react-native-plaid-link-sdk > com.plaid.link:sdk-core:3.2.5
      > Unable to find a matching variant of pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
          - Variant 'metadataApiElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible attributes:
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found incompatible value 'common'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
          - Variant 'releaseApiElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
          - Variant 'releaseRuntimeElements-published' capability pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2:
              - Incompatible attribute:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
```

**Comment by amytang0** [comment]
Sorry, this also requires changing the line
```   
    implementation project(':react-native-plaid-link-sdk')
```
to
```
    implementation(project(path: ':react-native-plaid-link-sdk', configuration: 'default'))
 ```
 
 Thanks for your patience!

**Comment by a613** [comment]
Thanks, that didn't fix the build though, got another error. I'll see if we can find a solution here. @OnurVar interested to hear if you have success with the above.

**Comment by OnurVar** [comment]
When I tried these lines below 
   ```    
implementation(project(path: ':react-native-plaid-link-sdk', configuration: 'default'))
implementation("com.plaid.link:sdk-core:3.2.3") {
      force true
}
```
Gradle sync failed with error
```
No variants found for 'react-native-plaid-link-sdk'. Check build files to ensure at least one variant exists.
```

So I changed ```default``` to ```release``` or ```debug```, for example
```
implementation(project(path: ':react-native-plaid-link-sdk', configuration: 'debug'))
implementation("com.plaid.link:sdk-core:3.2.3") {
    force true
}
```
Gradle sync succeeded but when trying to run the app, I got another error
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-plaid-link-sdk.
     Required by:
         project :app
      > Project :app declares a dependency from configuration 'implementation' to configuration 'debug' which is not declared in the descriptor for project :react-native-plaid-link-sdk.

```


so for now, I think we will be waiting for next release.

**Comment by amytang0** [comment]
Hi apologies all for the errant pbandk dependency, we have removed it for [7.0.2](https://www.npmjs.com/package/react-native-plaid-link-sdk/v/7.0.2).

**Comment by OnurVar** [comment]
Hi @amytang0,

I tried 7.0.2 and it seems like working. Thanks for the help.

Best regards
