### ISSUE TITLE
language and countryCodes in LinkPublicKeyConfiguration are required

### ISSUE THREAD

**Issue by Gentlee** [plaid/react-native-plaid-link-sdk#349]
# The problem

language and countryCodes in LinkPublicKeyConfiguration are required, so i got error while using TypeScript when migrated from 5x version.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.1                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             | yes                |
| Occurs on iOS     | yes                |

# Expected Result
Should be optional.

# Screenshots
![Screenshot 2021-03-24 at 02 41 46](https://user-images.githubusercontent.com/2361140/112232937-87dfed00-8c4a-11eb-905e-70d091395bab.png)

# Code To Reproduce Issue 
```
openLink({
  publicKeyConfig: {
    clientName: 'Example',
    publicKey: Config.APP_PLAID_KEY,
    environment: Config.APP_PLAID_ENV as PlaidEnvironment,
    products: [PlaidProduct.AUTH],
  }
})
```

**Comment by Gentlee** [comment]
And there is nothing in docs about these fields, including migration docs from 5x to 7x.

**Comment by amytang0** [comment]
Thank you for flagging that these fields became required in 7.x! We will update the docs accordingly
