### ISSUE TITLE
Android app crashes on startup

### ISSUE THREAD

**Issue by Gentlee** [plaid/react-native-plaid-link-sdk#351]
# The problem

Android app crashes on startup if I remove `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'` from dependencies as asked in migration from 5x to 7x guide. Also no info about that in getting started docs.

# Environment

| Plaid Link React Native          | 7.0.2                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android               | yes                |
| Android OS Version                    | Android 8 and 10                |
| Android Devices/Emulators    | Pixel 4 API 30 Emulator, Nexus 5x device                |

# Steps to Reproduce

Follow getting started guide for android and/or migration from 5x to 7x guide.

# Logs
```
2021-03-25 17:47:37.495 18418-18514/com.altruist.mobileapp E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.altruist.mobileapp, PID: 18418
    java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes
```

# Code To Reproduce Issue

Happens when the only dependency in build.gradle is `implementation project(':react-native-plaid-link-sdk')`, without `okhttp`

**Comment by zsweigart** [comment]
Hi @Gentlee thank you for the report.  The SDK is only compatible with okhttp3 versions 4.x.x but it should be included automatically via our SDK. Would you be able to post your dependencies in your `build.gradle` file (here are the dependencies from [our sample](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/example/android/app/build.gradle#L183-L211)) and the dependency tree from `./gradlew :app:dependencies`?

**Comment by Gentlee** [comment]
Hello @zsweigart 

`build.gradle` dependencies:
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.android.support:multidex:1.0.3'

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    implementation project(':react-native-plaid-link-sdk')
}
```


`./gradlew :app:dependencies` [deps.txt](https://github.com/plaid/react-native-plaid-link-sdk/files/6278743/deps.txt)

**Comment by zsweigart** [comment]
It seems okhttp3 version 5 has been released and is being packaged in.

From your dependencies:
```
+--- com.squareup.okhttp3:okhttp:{strictly 5.0.0-alpha.2} -> 5.0.0-alpha.2 (c)
```

We have not tested with 5 and it seems to be incompatible.  We'll work on a fix on our end but for now including `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'` will work

**Comment by walterholohan** [comment]
I can confirm that adding `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'` fixed the issue for me. See below the dependencies i have setup in my `app/build.gradle` file

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    implementation project(':react-native-plaid-link-sdk')
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
```

**Comment by jarredt** [comment]
Adding `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.0'` also solved crasher for us -- thanks!

**Comment by zsweigart** [comment]
Great to hear that worked for you, we'll update the documentation
