### ISSUE TITLE
MFA screen back press gives blank white screen

### ISSUE THREAD

**Issue by MusabAkram** [plaid/react-native-plaid-link-sdk#355]
When adding bank of America account it requires multi-factor authentication. When you click back arrow on the top from multi-factor screen it renders blank white screen.

**Plaid Link React Native**: 7.0.2
**ReactNative Version** : 0.63
**Occurs on**: Android/IOS

**# Steps to Reproduce**

1. Choose bank of America
2. Add credentials 
3. submit
4. Multifactor screen renders
5. Click back arrow on top
6. Blank screen

**Comment by pladaub** [comment]
Hi, could you attach the following information:

1. A video of the flow
2. Details on how you're configuring Plaid:
i) Are you using Link Token or Public Key based configurations?
ii) Does this happen in all environments, or just some environments? If only some, which environments?
iii) Could you share the code you're using to configure link? **Please ensure that any credentials (e.g. a link token or public key) are redacted**
3. Has this issue always occurred, or has it started occurring recently? If so, when? Did you change anything about the integration around that time (e.g. upgrading the SDK, if so from what version)?
4. You mentioned this only happens for Bank of America. Are you seeing MFA screens work for other institutions, or have you only been able to test the MFA flow on Bank of America?

Thanks!

**Comment by MusabAkram** [comment]
https://user-images.githubusercontent.com/19502504/114848019-bbe8a100-9df7-11eb-93e4-599b371c7ac5.mp4

**Comment by amytang0** [comment]
This issue with Bank of America is resolved; please reopen this issue if this is not the case
