### ISSUE TITLE
`webviewRedirectUri` marked required

### ISSUE THREAD

**Issue by dustinhorton** [plaid/react-native-plaid-link-sdk#36]
https://github.com/plaid/react-native-plaid-link-sdk/commit/4817c20c6626dced26527671fad54b29ea2f8f71#diff-97c99a924bd133e937208283f87b5ae8R103

Does this make sense to be required? My app is iOS only…easy enough to get around, but hate to set an option needlessly.

**Comment by wkiefer** [comment]
Thanks for checking! Because RN targets both iOS and Android and the string is required for Android to function, we need to make it required.
