### ISSUE TITLE
Android - backHandler support

### ISSUE THREAD

**Issue by iamandiradu** [plaid/react-native-plaid-link-sdk#362]
On Android, pressing the 'back' button will close Plaid instead of navigating back. Is there a way to prevent this? 
Adding the BackHandler bypass on the root screen doesn't work. This needs to be handled inside of Plaid component.

**Comment by JeroenMols** [comment]
Thanks for reporting @iamandiradu.

Unfortunately, our SDK doesn't offer a way to modify the back behavior and pressing back currently closes Plaid Link. This however is on our roadmap, so please stay up to date with our SDK so you'll get it as soon as we roll out this feature.

**Comment by iamandiradu** [comment]
Do you accept PRs? I might be able to add this feature.

**Comment by JeroenMols** [comment]
Thank you for offering that's super kind!

We do accept PRs for React Native, but not for the Android/iOS SDKs that are wrapped by RN unfortunately. At the moment it's also challenging to properly to support this (given that we render Plaid Link in a Webview), but we will soon be changing that which would enable us to provide proper back support.

**Comment by a613** [comment]
Can this be left open? It's a production bug. Not only does the SDK close upon Back pressed, there are zero events fired as a result, meaning we have no way to react to it happening.

**Comment by iamandiradu** [comment]
@a613, the onExit event is not fired? I'm currently using it to open a form and it works.

**Comment by a613** [comment]
Oh I was using the webview directly there, and saw no events at all. But after turning the SDK on, yes I do get an onExit, and it seems to only have metadata.linkSessionId in it, unlike the more filled-out event payloads if the user uses the Plaid UI to exit. That should let us differentiate between a normal exit and a Back-button exit.

Still a prod bug, and would prefer if it was left open to reflect that.

**Comment by JeroenMols** [comment]
@a613 good point, for for the eager close.

Let's keep this open to track the progress.

**Comment by amytang0** [comment]
Hi, our native beta does support a more nuance back behavior. Please contact android@plaid.com with your `client_id` in order to enable this feature.
