### ISSUE TITLE
SDK does not dismiss as expected when wrapped within a UINavigationController

### ISSUE THREAD

**Issue by joel-stewart** [plaid/react-native-plaid-link-sdk#365]
# The problem

We have run into an issue in which the SDK does not dismiss as expected when wrapped within a `UINavigationController`. When triggering a close event (either manually via the close button or automatically) you are left with a blank screen because the View is not being dismissed.

We are required to wrap in a `UINavigationController` as this is required for another SDK integration. We have done some investigation and have had trouble coming up with a work around.

We are hoping that Plaid could help shed some light on why this occurring (as the webview is a blackbox) and possibly offer a solution or fix.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.2                |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             | no                |
| Android OS Version                    | N/A                |
| Android Devices/Emulators    | N/A                |
| Occurs on iOS     | yes                |
| iOS Version           | 14.4                |
| iOS Devices/Emulators               | iPhone 12 Pro                |

# Steps to Reproduce

1. Open the app.
2. Trigger the Plaid Link SDK.
3. Attempt to close the Plaid SDK via the close button.

# Expected Result
The SDK should close to reveal the RN app.

# Screenshots
https://user-images.githubusercontent.com/2966155/115835876-25049000-a45a-11eb-89d5-c16cb11aa24a.mov

# Logs
N/A.

# Code To Reproduce Issue 
Forked link to the demo app with a few lines changed to replicate the issue:

https://github.com/joel-stewart/react-native-plaid-link-sdk

**Comment by pladaub** [comment]
Hi, this can be worked around by using the `-[PLKHandler openWithPresentationHandler:dismissalHandler:options:]` method.

Please  change `open` in RNLinkSdk.m to the following:

```objectivec
RCT_EXPORT_METHOD(open:(RCTResponseSenderBlock)onSuccess :(RCTResponseSenderBlock)onExit) {
    if (self.linkHandler) {
        self.successCallback = onSuccess;
        self.exitCallback = onExit;
        self.presentingViewController = RCTPresentedViewController();
        NSDictionary *options = self.institutionID.length > 0 ? @{@"institution_id": self.institutionID} : @{};
        __weak typeof(self) weakSelf = self;
        [self.linkHandler openWithPresentationHandler:^(UIViewController *plaidViewController) {
            [weakSelf.presentingViewController presentViewController:plaidViewController animated:YES completion:nil];
        } dismissalHandler:^(UIViewController *plaidViewController) {
            [weakSelf dismissLinkViewController];
        } options:options];
    } else {
        id error = self.creationError ? RCTJSErrorFromNSError(self.creationError) : RCTMakeError(@"create was not called", nil, nil);
        onExit(@[error]);
    }
}
```

We'll look at making changes to LinkKit itself to make this workaround unnecessary.

**Comment by joel-stewart** [comment]
Hi @pladaub,

Thanks for responding so quickly. I've tested this fix and it works perfectly, thank you so much for looking into this.

Any chance you might be able to offer a rough estimate of when you think you might be able to get this fix in for a future release? We are not looking to push our integration live for a while yet but it would be great to get some kind of timeline so I can communicate this to our our team.

Thanks again!

**Comment by pladaub** [comment]
This is out in 7.0.4
