### ISSUE TITLE
Unable to Redirect back to iOS React Native App from PlatyPus OAuth Test Bank when "Deny access" or "Simulate Error" is Selected

### ISSUE THREAD

**Issue by drencewicz** [plaid/react-native-plaid-link-sdk#366]
I am currently using react-native-plaid-link-sdk 5.0.2 to connect users to Plaid in our iOS and Android apps. There are no issues with Android, but with iOS the app is able to successful create a LinkToken and open the PlaidLink component. When testing OAuth the Platypus OAuth test bank it works fine when I press "Grant access" (the Plaid connection is created and I'm returned to the app), but when I press "Deny access" or "Simulate Error" I get a spinner with a button "Click to continue" and when I press it I get an error message that says "an unexpected error occured request_id 'FwikjLSqnUn0T'" and the spinner spins infinitely. I'm aware that you should set a redirect uri to a domain that has an Apple App Site Association file, but when I do that all three buttons take me to our redirect webpage, not the app.

![Screen Shot 2021-04-27 at 2 16 18 PM](https://user-images.githubusercontent.com/26094088/116291947-2b994d00-a763-11eb-84ca-abd5d2172692.png)

![Screen Shot 2021-04-27 at 12 14 56 PM](https://user-images.githubusercontent.com/26094088/116291724-eaa13880-a762-11eb-8e11-5ea230d95e42.png)

![Screen Shot 2021-04-27 at 12 17 09 PM](https://user-images.githubusercontent.com/26094088/116291424-8ed6af80-a762-11eb-92f1-e1fdbc40d215.png)

**Comment by pladaub** [comment]
We don't have first party support for OAuth in React Native 5.x and older. For first party support, please upgrade to RN 7.
