### ISSUE TITLE
v7.0.3 is missing dist folder

### ISSUE THREAD

**Issue by movespawan** [plaid/react-native-plaid-link-sdk#370]
# The problem

I got this error
```
Error: While trying to resolve module `react-native-plaid-link-sdk` from file
```
When I installed the latest version. Looks like the package is missing the dist folder. Downgrading to v7.0.2 worked.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | e.g. 6.0.0                |
| ReactNative Version     | e.g. 0.61.3                |
| Occurs on Android             | e.g. yes                |
| Android OS Version                    | e.g. 5.0.0 (21)                |
| Android Devices/Emulators    | e.g. Pixel 3a physical                |
| Occurs on iOS     | e.g. yes                |
| iOS Version           | e.g. 11                |
| iOS Devices/Emulators               | e.g. iPhone X                |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

For example:
```
{
   "client_id":"OMITTED",
   "secret":"OMITTED",
   "user":{
      "client_user_id":"OMITTED",
      "legal_name":"OMITTED"
   },
   "client_name":"My application",
   "products":[
      "auth"
   ],
   "country_codes":[
      "US"
   ],
   "language":"en",
   "android_package_name":"com.mycompany.myapp"
}
```

# Expected Result
What did you expect to happen?

# Screenshots

# Logs
Any relevant logs from Android Logcat or the iOS console including stacktraces.

# Code To Reproduce Issue 
With sample code it's easier to reproduce the bug and it's much faster to fix it. 
Don't forget to omit any keys or personally identifiable information.
Please provide one of the following:

1. (Best) A link to a minimal demo app showing the faulty behaviour.
1. (Better) A concise code sample which can be dropped into fresh application
1. A snippet of code for your configuration for opening Link

**Comment by IljaDaderko** [comment]
Replicated, app crashes because it can't find it

<img width="350" alt="Screenshot 2021-04-29 at 09 42 52" src="https://user-images.githubusercontent.com/3154053/116511570-4e487480-a8cf-11eb-8242-1f537b021719.png">

**Comment by Matcenko** [comment]
the same problem, it tries to find /node_modules/react-native-plaid-link-sdk/dist/index.js. It`s true, there are not one, /node_modules/react-native-plaid-link-sdk here only android,ios and node_modules folder and several other files.

**Comment by Matcenko** [comment]
As I said previously: there is not folder dist in this module. Downgrate to v7.0.2 version, It works great for me!

**Comment by djMax** [comment]
Hey Plaid team, this is basically a poison release. Can you please fix/acknowledge?

**Comment by phoenixy1** [comment]
@djMax acknowledged!  Very sorry about this, we'll get a fix out ASAP.

**Comment by zsweigart** [comment]
@djMax @Matcenko @IljaDaderko Apologies for the release, 7.0.4 is out now
