### ISSUE TITLE
Execution failed for task ':react-native-plaid-link-sdk:compileDebugKotlin'

### ISSUE THREAD

**Issue by FaizanMostafa** [plaid/react-native-plaid-link-sdk#376]
Hello collaborators, thanks for developing such an awesome package. Unfortunately I am facing issues while integrating this package using [these docs](https://plaid.com/docs/link/react-native/android-setup/). On running `npx react-native run-android` I get the following error! Stuck on this issue for last couple of hours, please let me know of any possible solution, thanks!

> > Task :react-native-plaid-link-sdk:compileDebugKotlin FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
> 63 actionable tasks: 61 executed, 2 up-to-date
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-plaid-link-sdk:compileDebugKotlin'.
> > Could not resolve all artifacts for configuration ':react-native-plaid-link-sdk:debugCompileClasspath'.
>    > Failed to transform bcprov-jdk15on-1.65.jar (org.bouncycastle:bcprov-jdk15on:1.65) to match attributes {artifactType=android-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
>       > Execution failed for JetifyTransform: /home/faizan/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.65/320b989112f00a63a3bcfa5a98f31a4f865a20fa/bcprov-jdk15on-1.65.jar.
>          > Failed to transform '/home/faizan/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.65/320b989112f00a63a3bcfa5a98f31a4f865a20fa/bcprov-jdk15on-1.65.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 7s

I am using:

- **React Native** 0.63.4
- **react-native-plaid-link-sdk** ^7.0.5
- **minSdkVersion** 21

**Comment by jdbarrera** [comment]
I am getting the same error.  It was working fine and suddenly started saying this.

**Comment by dnvarun** [comment]
Try updating android gradle plugin to >= 4.0.0 . It solved the issue for me. Source: https://github.com/square/okhttp/issues/6125

**Comment by gudberg** [comment]
I have gradle 4.1.0 but this is still happening in my project. Any ideas?

**Comment by amytang0** [comment]
Fwiw, these are our current gradle versions.
```
  const val android = "com.android.tools.build:gradle:7.0.3"
  const val kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30"
  const val kotlin_serialization = "org.jetbrains.kotlin:kotlin-serialization:1.5.30"
  ```
  
 ```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
```
