### ISSUE TITLE
Link update mode not working in iOS

### ISSUE THREAD

**Issue by dnvarun** [plaid/react-native-plaid-link-sdk#378]
# The problem

Item update mode is not working in iOS sandbox environment after upgrading from 5.x.x to 7.0.5. Plaid link opens as if we are linking a new item and goes to the institution list page. But weird part is it is working fine on android sandbox.
Note: we are still using the legacy public key configuration. 

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.5                |
| ReactNative Version     | 0.63.2                |
| Occurs on Android             | no                |
| Occurs on iOS     | yes                |
| iOS Version           | 14.4                |
| iOS Devices/Emulators               | iPhone 11 device and iPhone 12 emulator                |

# Steps to Reproduce

Use the https://sandbox.plaid.com/sandbox/item/reset_login api to reset login for an item. And try opening the update mode of PlaidLink with token in publicKeyConfig

For example:
```
<PlaidLink
      publicKeyConfig={{
        clientName: plaidDetails.clientName,
        publicKey: plaidDetails.publicKey,
        environment: plaidDetails.env,
        products: plaidDetails.product,
        token: plaidDetails.token,
        language: 'en',
        countryCodes: Array.of('US'),
        logLevel: LinkLogLevel.DEBUG,
        webhook: plaidDetails.webhook,
      }}
      onSuccess={plaidDetails.onSuccess}
      onExit={plaidDetails.onExit}
    >
      {customComponent()}
    </PlaidLink>
```

# Expected Result
PlaidLink should directly go to the credentials form. But it is going to the select institution page

# Screenshots
None

# Logs
None

# Code To Reproduce Issue 
Mentioned above

**Comment by pladaub** [comment]
Thanks for the report! I've validated the issue an identified a fix. The fix will be present in the next release of the SDK, 7.0.6. I will update this issue once that has been released.

**Comment by dnvarun** [comment]
Thanks! What is the approximate eta for the next release?
