### ISSUE TITLE
Application crash in android when long press in input text - Android

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#38]
Hello @wkiefer @zsweigart 

I have one issue in plaid, after adding username in plaid windows I tried to copy that username but when I long press on that text input application crashed.

Can you help me, how to prevent application crash in any condition?

**Comment by zsweigart** [comment]
Hi @kanji-keraliya thanks for the report, we will investigate with the latest 3.0 release

**Comment by zsweigart** [comment]
Hi @kanji-keraliya we have been unable to reproduce, can you provide more information including:
- What device are you using?
- What OS version is it running?

**Comment by zsweigart** [comment]
Closing as cannot reproduce
