### ISSUE TITLE
Plaid Link intercepting onPress events requires it to have a dedicated screen in order to add preemptive error handling

### ISSUE THREAD

**Issue by trex-quo** [plaid/react-native-plaid-link-sdk#383]
# The problem

It is impossible to launch Plaid Link from an existing screen in the app (and properly handle errors); the behavior of intercepting the child view onPress requires Plaid Link to have its own screen. Once the user clicks the button that PlaidLink wraps, it is impossible to prevent the Link flow from opening itself up (the link flow overrides attempts to open an alert box). 

I would like to be able to perform checks on the user once they click that button, e.g. assert that they have < 3 bank accounts connected before allowing them to proceed. I have attempted to manually intercept the button ref and automatically open the Link flow as the user moves to the screen containing the component, but manually triggering the onPress method does not open the flow.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          |  7.0.5                |
| ReactNative Version     | 0.63.3                |
| Occurs on Android             |  yes                |
| Occurs on iOS     | yes                |

# Steps to Reproduce

Applies to using the SDK in general

# Expected Result
I would either like for the component to automatically open when placed onto a screen (so that an additional user interaction isn't required for them to begin the Link flow), or I would like to be able to manually trigger a callback to open the Link flow, so that it can be done in a useEffect right as the screen loads.

**Comment by pladaub** [comment]
Hi, I believe the `PlaidLink.openLink` API should address this usecase.

When using `PlaidLink.openLink`, be sure to invoke the `useDeepLinkRedirector` hook

**Comment by trex-quo** [comment]
Thank you for the help! I hadn't initially realized that this method existed. Thanks again 😄
