### ISSUE TITLE
Android Application crashed if not providing com.plaid.link.public_key

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#39]
Hello @wkiefer @zsweigart 

I want to use different plaid key dynamic based on platform like sandbox or production, I already set key in  <PlaidLink ... publicKey = "##YOUR PUBLIC KEY##" />.

When I removed bellow line from AndroidManifest.xml then application crashed on app launch

```<meta-data   android:name="com.plaid.link.public_key"   android:value="YOUR KEY" />```

Can you please help me

**Comment by kanji-keraliya** [comment]
@zsweigart does any way to set in react native instead of android menifest or MainApplication.java?

**Comment by Mactub07** [comment]
@kanji-keraliya , https://github.com/luggit/react-native-config

**Comment by zsweigart** [comment]
Hi @kanji-keraliya in the latest 3.0 release you can set the public key in the [PlaidLink component](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/PlaidLink.js#L107) by calling `Plaid.setPublicKey(...)`  in Android code or by adding the key to the manifest.  The key must be set before you open link.
