### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin.

### ISSUE THREAD

**Issue by FaizanMostafa** [plaid/react-native-plaid-link-sdk#392]
Hello collaborators, thanks for developing such an awesome package. Unfortunately I am facing issues while integrating this package using [these docs](https://plaid.com/docs/link/react-native/android-setup/). On running npx react-native run-android I get the following error! Stuck on this issue for last couple of hours, please let me know of any possible solution, thanks!

> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkAccount.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (32, 11): Class 'com.plaid.link.result.LinkAccountVerificationStatus' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkAccountVerificationStatus.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (32, 31): Unresolved reference: let
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (32, 37): Cannot infer a type for this parameter. Please specify it explicitly.
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (33, 51): Unresolved reference: let
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (34, 11): Unresolved reference: addProperty
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (34, 46): Unresolved reference: it
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (39, 40): Class 'com.plaid.link.result.LinkAccount' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkAccount.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (39, 44): Class 'com.plaid.link.result.LinkAccountSubtype' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkAccountSubtype.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (40, 16): Unresolved reference: let
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (41, 9): Unresolved reference: addProperty
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (41, 29): Unresolved reference: it
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (42, 9): Unresolved reference: addProperty
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNAccountAdapter.kt: (42, 32): Unresolved reference: it
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (13, 30): Class 'com.plaid.link.result.LinkInstitution' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkInstitution.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (16, 49): Class 'com.plaid.link.result.LinkInstitution' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkInstitution.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (19, 10): Class 'com.plaid.link.result.LinkInstitution' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkInstitution.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (23, 9): Class 'com.plaid.link.result.LinkInstitution' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkInstitution.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (26, 28): Unresolved reference: apply
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (28, 7): Unresolved reference: addProperty
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (28, 25): Class 'com.plaid.link.result.LinkInstitution' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkInstitution.class
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (30, 7): Unresolved reference: addProperty
> e: /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native-plaid-link-sdk/android/src/main/java/com/plaid/gson/RNLinkInstitutionAdapter.kt: (30, 27): Class 'com.plaid.link.result.LinkInstitution' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
> The class is loaded from /home/faizan/.gradle/caches/transforms-2/files-2.1/fc533cbdccd3de1159c08116bc214c68/jetified-sdk-core-3.4.0-api.jar!/com/plaid/link/result/LinkInstitution.class

**FAILURE: Build failed with an exception.**

* What went wrong:
Execution failed for task ':react-native-plaid-link-sdk:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

   

>  at makeError (/media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/execa/index.js:174:9)
>     at /media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/execa/index.js:278:16
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async runOnAllDevices (/media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
>     at async Command.handleAction (/media/faizan/New Volume/Buckets Investing/v3/RNBucketsInvestingV3/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
> info Run CLI with --verbose flag for more details.

**I am using:**

- React Native = 0.64.2
- react-native-plaid-link-sdk = ^7.0.5
- buildToolsVersion = "29.0.3"
- minSdkVersion = 21
- compileSdkVersion = 29
- targetSdkVersion = 29
- ndkVersion = "20.1.5948944"

**Comment by pjcaro** [comment]
@FaizanMostafa any update?

**Comment by FaizanMostafa** [comment]
> @FaizanMostafa any update?

No ☹️

**Comment by pjcaro** [comment]
@FaizanMostafa ok thanks, it worked for me using version 7.0.6

**Comment by FaizanMostafa** [comment]
> @FaizanMostafa ok thanks, it worked for me using version 7.0.6

I'll try that as well, can you please tell me the react-native version and other configs your are using?

**Comment by pjcaro** [comment]
@FaizanMostafa I'm using:

```
"react-native": "0.64.0",
"react-native-plaid-link-sdk": "7.0.6",
```

```
android/build.gradle
....
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
    }
...
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.1')
    }
...

```

**Comment by FaizanMostafa** [comment]
> @FaizanMostafa I'm using:
> 
> ```
> "react-native": "0.64.0",
> "react-native-plaid-link-sdk": "7.0.6",
> ```
> 
> ```
> android/build.gradle
> ....
>     ext {
>         buildToolsVersion = "29.0.3"
>         minSdkVersion = 21
>         compileSdkVersion = 29
>         targetSdkVersion = 29
>         ndkVersion = "20.1.5948944"
>     }
> ...
>     dependencies {
>         classpath('com.android.tools.build:gradle:4.2.1')
>     }
> ...
> ```

Thanks

**Comment by Taylor123** [comment]
Just ran into this myself. You'll need to update you're Kotlin version (or define it if it wasn't previously as was my case)

in `android/build.gradle`
```
buildscript {
    // other stuff
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10'
       // other stuff
    }
}

```

**Comment by amytang0** [comment]
Apologies for the late reply, but it looks like you are using Kotlin 1.1.16, which was released ~2017. We don't guarantee compatibility with any library older than 3 years, and Taylor's suggestion to use Kotlin version `1.5.10` is good.

**Comment by pjcaro** [comment]
Thanks @Taylor123, @amytang0 this worked for me 

> Just ran into this myself. You'll need to update you're Kotlin version (or define it if it wasn't previously as was my case)
> 
> in `android/build.gradle`
> 
> ```
> buildscript {
>     // other stuff
>     dependencies {
>         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10'
>        // other stuff
>     }
> }
> ```

**Comment by pjcaro** [comment]
@amytang0 I'm having another problem on iOS, I followed the steps in the documentation, but on iOS it doesn't take me to the screen to choose the bank account, on android it works fine, it takes me to the screen to choose an account so the onSuccess returns me only one account, but on iOS I can't access this screen, what could be the reason for this?

**Comment by amytang0** [comment]
What does your `iOS/Podfile` specify for its Plaid dependency? e.g. `pod 'Plaid', '~> 2.1.0'`

**Comment by azzayan** [comment]
Thanks, @Taylor123! Your solution worked for me.

**Comment by pjcaro** [comment]
> What does your `iOS/Podfile` specify for its Plaid dependency? e.g. `pod 'Plaid', '~> 2.1.0'`

I fixed that, it was because of the language in the request header. Thanks @amytang0
