### ISSUE TITLE
Android React Native Oauth stuck at OPEN_OAUTH

### ISSUE THREAD

**Issue by Taylor123** [plaid/react-native-plaid-link-sdk#393]
# The problem
React Native Android OAuth flow does not open the OAuth page when no redirect url is present. When there is a redirect url, the `OPEN_OAUTH` works fine and opens a browser. However, when I remove the redirect url it no longer redirects from my app to the respective OAuth provider.

Is this intentional on Android when testing in the sandbox environment?

# Environment

|                        |  |
| ------------------------| ---------- |
| environment          | sandbox                |
| Plaid Link React Native          | 7.0.7                |
| ReactNative Version     |  0.63.3                |
| Occurs on Android             | yes                |
| Android OS Version                    | 10                |
| Android Devices/Emulators    | Google Pixel 2XL                |

# Steps to Reproduce

- Fetch link_token
- open plaid link 
- search for `Platypus OAuth Bank`
- select `Platypus OAuth Bank`
- click to "Continue to sign in"

After this, nothing happens

# Expected Result
After clicking to sign in the app should be redirected to the OAuth flow to grant access.

# Logs
These are the link events that are logging, but then nothing happens after `OPEN_OAUTH`.
```
{metadata: {…}, eventName: "OPEN"}
{metadata: {…}, eventName: "TRANSITION_VIEW"}
{metadata: {…}, eventName: "SEARCH_INSTITUTION"}
{metadata: {…}, eventName: "SELECT_BRAND"}
{metadata: {…}, eventName: "SUBMIT_CREDENTIALS"}
{metadata: {…}, eventName: "OPEN_OAUTH"}
```

**Comment by amytang0** [comment]
When you create the Link token on Android, are you passing in the [`android_package_name`](https://plaid.com/docs/api/tokens/#link-token-create-request-android-package-name) parameter? This is needed to redirect back to the correct app

**Comment by Taylor123** [comment]
Nope, was only using the redirect URI. Misread the docs thinking i only needed to register the `android_package_name`.

Will reopen if the issues persists after the changes, thanks!
