### ISSUE TITLE
useDeepLinkRedirector does not seem to be necessary in iOS for OAuth

### ISSUE THREAD

**Issue by dnvarun** [plaid/react-native-plaid-link-sdk#396]
# The problem

The OAuth redirection seems to work fine in ReactNative iOS without using the code for useDeepLinkRedirector even if I use PlaidLink.openLink . To give context about our app, we are using https://github.com/react-navigation/react-navigation/ which automatically handles linking. Also we are using class components. So initially I was not sure if I have to / can use useDeepLinkRedirector. So I tried testing without using it and it worked. The Capital One auth page seems to open inside the app itself and does not open a new safari/chrome window. 

Please let us know if there are any cases this wont work and we have to somehow integrate the logic of useDeepLinkRedirector. Also if this will cause any issues with react-navigation library.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.6                |
| ReactNative Version     | 0.63.2                |
| Occurs on Android             | N/A                |
| Android OS Version                    | N/A                |
| Android Devices/Emulators    | N/A                |
| Occurs on iOS     | yes                |
| iOS Version           | 14.6                |
| iOS Devices/Emulators               | iPhone 11 physical                |

# Steps to Reproduce
N/A

# Expected Result
N/A

# Screenshots
N/A

# Logs
N/A

# Code To Reproduce Issue 
N/A

**Comment by pladaub** [comment]
Hi, could you attach a video of the flow working when `useDeepLinkRedirector` is not invoked?

The hook is necessary as it propagates the deep link to the Link SDK. Without this, the user will get stuck during app-to-app OAuth. During in-app OAuth, this propagation is not necessary. I suspect that the working flow you're experiencing is the in-app OAuth flow, and so a video will help confirm that.

**Comment by dnvarun** [comment]
Yes, we have tested in-app OAuth only, did not consider the app-to-app case. 
But it is not trivial how to include `useDeepLinkRedirector` as hooks are not supported directly in class components. Also we are using [react-navigation](https://github.com/react-navigation/react-navigation/) library to handle deep linking and so we are not sure if there will be a clash in handling the deep links.
Please guide us how to use useDeepLinkRedirector logic in our scenario.

**Comment by Krisztiaan** [comment]
Reading the source for the hook, you can easily adapt it to class components (via `componentXMount`, `componentXUnmount`)
```js
export const useDeepLinkRedirector = () => {
    const _handleListenerChange = (event) => {
        if (event.url !== null && Platform.OS === 'ios') {
            NativeModules.RNLinksdk.continueFromRedirectUriString(event.url);
        }
    };
    useEffect(() => {
        Linking.addEventListener('url', _handleListenerChange);
        return function cleanup() {
            Linking.removeEventListener('url', _handleListenerChange);
        };
    }, []);
};
```

**Comment by AntonOmelchuk** [comment]
as I see in PlaidLink we call useDeepLinkRedirector hook so when I use PlaidLink it's not necessary to use useDeepLinkRedirector in my code?

**Comment by jhurray** [comment]
@dnvarun I'm going to close this out given the examples shared & the callout that `PlaidLink ` includes a call to `useDeepLinkRedirector ` - please re-open & tag me if there are still issues / asks!
