### ISSUE TITLE
'LinkKit/LinkKit.h' file not found (RNLinksdk.m)

### ISSUE THREAD

**Issue by dustinhorton** [plaid/react-native-plaid-link-sdk#4]
After installing, I can no longer build due to:

```
RNLinksdk
  Lexical or Preprocessor Issue
    'LinkKit/LinkKit.h' file not found
      RNLinksdk.m
```

I see this specific error pointed out in the [iOS SDK docs](https://plaid.com/docs/link/ios/#manual), but I'm not 100% it's applicable here, or what I might need to update the 'Framework Search Paths' to. I've tried basically every incantation of `PROJECT_DIR` and `PODS_ROOT` to no avail.

I think the file it's looking for exists at `ios/Pods/Plaid/LinkKit.framework/Headers/LinkKit.h`, but I'm not even sure that's actually the right file.

**Comment by wkiefer** [comment]
Have you added `pod 'Plaid'`to your `ios/Podfile`?

**Comment by dustinhorton** [comment]
@wkiefer Yes, and Podfile looks like this:

```
target 'feespotter_mobile' do
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'RCTImage',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Plaid', '~> 1.1.24'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'react-native-plaid-link-sdk', :path => '../node_modules/react-native-plaid-link-sdk'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
```

**Comment by wkiefer** [comment]
`ios/Pods/Plaid/LinkKit.framework/Headers/LinkKit.h` is the correct header for the Plaid Link iOS SDK.

I'm not a Cocoapods expert, but your podfile seems to be missing a few lines from what I've seen in typical RN .60+ setups.

at the top
`require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'`
and just before your `target` `end` you can add `use_native_modules!`.

(I'm also assuming you successfully ran `pod install` and the generated workspace has the Plaid SDK library inside it?)

**Comment by dustinhorton** [comment]
Really appreciate you taking a look.

I'm actually on React Native `0.59.8`.

`pod install` ran successfully and I see references to Plaid in the workspace, but not 100% sure how to confirm it's 'successfully' inside the workspace.

**Comment by wkiefer** [comment]
if you open up the `.xcworkspace` file in your `ios` directory, you should see something like this within your Pods project:

![example](https://user-images.githubusercontent.com/103811/69382489-0bab5300-0c6c-11ea-9347-6aed9bf282e8.png)

If it's not there, than something is going wrong with the pods setup/install process.

**Comment by dustinhorton** [comment]
Yes, that's what mine looks.

**Comment by wkiefer** [comment]
Hmm, i'm not sure. Cocoapods should have created a `Pods-<Target>.debug.xcconfig` file with the proper framework search paths: e.g.
 `FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Plaid"`

It's possible your project is overriding that configuration — so check your framework search paths in Build Settings. thanks!

**Comment by dustinhorton** [comment]
Didn't resolve with my setup as-is, but got React Native upgraded and it seems to work as expected.

**Comment by jake-long-game** [comment]
I have this same issue, getting `'LinkKit/LinkKit.h' file not found`and my Pod folder looks a bit different than yours. 
@whockey 

<img width="286" alt="Screen Shot 2020-10-06 at 3 07 41 PM" src="https://user-images.githubusercontent.com/45996516/95265292-c4777380-07e5-11eb-82fa-22819d833e84.png">

Note: I have not use this react native plaid link library before. Until now, I have been doing plaid via webview. 
and I'm following this guild to set up https://plaid.com/docs/link/react-native/ios-setup/, running Plaid 2.0.1

**Comment by djMax** [comment]
I'm having this problem in *detox* builds but not in regular builds from xcode or the react-native CLI.

**Comment by sebastianpaz** [comment]
@jake-long-game did that work for you?

**Comment by Amit-Singh-Phartiyal** [comment]
I fixed the issue by just updating the **cocoapods version**. I update the version from 1.8.0 to 1.10.0

**Command to update.**
sudo gem install cocoapods --pre
