### ISSUE TITLE
User gets "trapped" in Plaid Link UI after pressing Continue button when using user_good / error_ITEM_LOCKED testing credentials

### ISSUE THREAD

**Issue by prometheas** [plaid/react-native-plaid-link-sdk#404]
# The problem

Attempting to login to most banks with the error-inducing credentials `user_good` / `error_ITEM_LOCKED` and pressing the "Continue" button, results in broken UI state that "traps" the user in the PlaidLink UI modal, requiring a force-quite of the app to ultimately recover.

FWIW, I also have a corollary support [incident](https://dashboard.plaid.com/support/case/327816) filed.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.7                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             | unknown                |
| Android OS Version                    | n/a                |
| Android Devices/Emulators    | n/a                |
| Occurs on iOS     |. Yes                |
| iOS Version           | 14.6                |
| iOS Devices/Emulators               | iPhone 12, iPhone 12 Mini, iPhone 12 Pro Max, and various simulated models         |

# Steps to Reproduce

Login to most banks (Chase, Chime, Wells Fargo, and Navy Federal all exhibit this behavior) with the error-inducing credentials `user_good` / `error_ITEM_LOCKED`, press the "Continue" button, and witness that:

1. The bank's website is loaded into the system's default web browser (for me, Safari), opening up in a new tab.
2. Upon return to the RN app, however, the PlaidLink UI gets stuck showing what seems to be a noscript version of an HTML page hosted by that bank (see attached screenshot), and does not offer any way to recover to any meaningful usage of the app. The user is forced to force-quit the app in order to continue using it.

This happens consistently.

# Expected Result

No expectations beyond not arriving to an irrecoverable state, frankly 😉 

# Screenshots

![Simulator Screen Shot - iPhone 11 - 2021-08-03 at 18 06 41](https://user-images.githubusercontent.com/185966/128548455-02117564-aca4-408e-a3f4-295bc640e8fc.png)

**Comment by pladaub** [comment]
Hi, thanks for the report. In order to isolate the behavior, we need the version of the underlying iOS Plaid SDK. This can be found in

`ios/Podfile`

**Comment by prometheas** [comment]
In case it's useful, I'm also including both dependency lock files from our project here.

[dependency-lockfiles.zip](https://github.com/plaid/react-native-plaid-link-sdk/files/6955412/dependency-lockfiles.zip)

Additionally, I'll proactively mention (as the question was asked on our internal support ticket) that nothing interesting is appearing in the console when this happens, beyond the single debug-level message my local build issues confirming the sandbox PlaidLink token… I've had eyes on both the JavaScript console, and stdout.

**Comment by prometheas** [comment]
Hey there, @pladaub - just checking here to confirm that you guys have everything you need from our end, after my having posted all project lock files above.

**Comment by pladaub** [comment]
Thanks for providing the file! I see you're on 2.1.3. This behaviour is very surprising and we have not received reports from other users. Could you please provide a video of this occuring so we can dig in? Figuring this out is a high priority for my team.

**Comment by pladaub** [comment]
Oh, additionally, could you provide an HTTP Archive file of the session? This can be collected using an HTTPS proxy, such as Charles Proxy. It's possible that a custom user agent is being set, which may explain the issue with the "Please update your browser" screen.

**Comment by prometheas** [comment]
Hey @pladaub - so I dunno if you have access to the Plaid incident link I included in the issue description, but — if you do — that includes a link to an unlisted YouTube video of a screen recording I made of the experience. I'm reluctant to post the video link here, as it's a public forum, and our software is unreleased.

If you haven't got access to the support ticket, however, I should be able to trim the video down so it shows only the bits where the PlaidLink UI is visible — just say the word.

Another possibly-relevant detail that came up in the aforementioned incident link is that this phenomenon is observed in our sandbox Plaid account (our app does not yet connect to our prod infrastructure), which I'm led to believe _theoretically_ could account for what we're seeing.

Anyway, lemme know if you can get the video link on that ticket, and I'll carve some time to record a HAR from the HTTP traffic in the morning (I'm in US Eastern, fwiw).

**Comment by pladaub** [comment]
@prometheas Thanks for the extra context – I can access the internal incident. I will follow up with you tomorrow, or Friday at the latest.

**Comment by prometheas** [comment]
Bi-weekly check in time…

**Comment by pladaub** [comment]
Hi, apologies for the delay – I just returned from leave. This issue is tracked internally, but we don't have an ETA. As it only occurs on sandbox it is not high priority. Given the delay so far, I'll take a look to estimate the effort required to fix, and see if I can provide an estimate.

**Comment by jhurray** [comment]
@prometheas we found a fix for this issue and it will be included in the next iOS & ReactNative releases. Closing this out since its not a ReactNative specific issue. Thank you for reporting through here & support!
