### ISSUE TITLE
Same Day Microdeposit - Verify Your Account - Different Webview between sandbox and prod env

### ISSUE THREAD

**Issue by liplylie** [plaid/react-native-plaid-link-sdk#406]
# The problem

The webview for the sandbox env is different from production. The sandbox env appears to have a newer design, the keyboardType is numeric, and default value is $0. Production env seems to have an older design, keyboardType is default, and default value is $0.00.

Not a huge issue, but the ux for sandbox is better, and the user has an easier time entering the values in comparison to production.

Note: this doesn't seem to happen consistently.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native  | 7.0.2                |
| ReactNative Version |  0.63.4   |
| Occurs on Android             | n/a                |
| Android OS Version                    | n/a               |
| Android Devices/Emulators    | n/a               |
| Occurs on iOS     |  yes                |
| iOS Version           | 14.7              |
| iOS Devices/Emulators               | iPhone X (real device)               |

# Steps to Reproduce

Go through Same Day Micro deposit flow. Go to Verification Step.

```
      openLink({
        publicKeyConfig: {
          clientName: '****',
          publicKey:,
          environment,
          products,
          language: 'en',
          countryCodes: ['US'],
          token,
        onSuccess,
        onExit
```

# Expected Result
Webview between both environments should be the same

# Screenshots
(Prod)
![Screen Shot 2021-08-09 at 12 43 22 PM](https://user-images.githubusercontent.com/28817645/128765434-e77b3848-c08d-431e-a54a-c1ff342cfdeb.jpg)
(Sandbox)
![Screen Shot 2021-08-09 at 12 43 10 PM](https://user-images.githubusercontent.com/28817645/128765438-f8cd91e4-b542-4c63-8905-f877f4149a85.jpg)

**Comment by amytang0** [comment]
Apologies for the late response. Our teams have been experimenting with new UX, and I'm glad to hear that you like the newer design!
We tend to experiment with these newer designs in sandbox before pushing them out to prod (where consumers will see them). 
I am curious, in the future, how would you like to be informed of these new UI changes?

**Comment by liplylie** [comment]
No worries! 

That makes sense.

Hmm, I think just having a callout module in https://plaid.com/docs/link/react-native/#overview saying there may be changes in ui would be great
