### ISSUE TITLE
TypeError: Cannot read property 'startLinkActivityForResult' of undefined

### ISSUE THREAD

**Issue by krunalray** [plaid/react-native-plaid-link-sdk#408]
I have followed all the steps from the below link
https://github.com/plaid/react-native-plaid-link-sdk#android-setup

but i'm still getting this error

TypeError: Cannot read property 'startLinkActivityForResult' of undefined

Hear is my Code

<PlaidLink
tokenConfig={{
token: plaidToken,
environment:"sandbox"
}}
onSuccess={(success: LinkSuccess) => {console.log(success)}
onExit={(exit: LinkExit) => {console.log(exit)}
>

**Comment by ParthNandaniya** [comment]
anyone found a solution to this problem ? having same issue.

`TypeError: Cannot read property 'startLinkActivityForResult' of null`
