### ISSUE TITLE
plaid-link-react-native npm package

### ISSUE THREAD

**Issue by safaiyeh** [plaid/react-native-plaid-link-sdk#41]
I own the npm namespace `plaid-link-react-native` as I was planning to make a react native module but never got around to it.

Great to see effort being put into supporting React Native! Would y'all want owner ship of the package name so you have consistent naming for the link SDKs.

**Comment by safaiyeh** [comment]
cc @wkiefer

**Comment by wkiefer** [comment]
Thanks so much @safaiyeh, we'd really appreciate taking ownership of your npm package to help avoid confusion out there.

My npm name is `wkiefer-plaid`, if you add me as a maintainer then I can transfer to the Plaid organization. Really appreciate, it, thanks!

**Comment by safaiyeh** [comment]
Invite sent @wkiefer

**Comment by safaiyeh** [comment]
When you confirm you have access I'll remove myself from the package

**Comment by wkiefer** [comment]
Confirmed as maintainer, thanks so much!

(I don't see the "Admin" tab yet, before you leave maybe double check my role is set correctly?)

**Comment by wkiefer** [comment]
I see admin now, thanks!

**Comment by safaiyeh** [comment]
Awesome, all yours! I just removed myself.

Excited about Plaid's work, can't wait to see more.
