### ISSUE TITLE
Plaid UI takes a very long time to appear

### ISSUE THREAD

**Issue by marcaaron** [plaid/react-native-plaid-link-sdk#411]
# The problem
Here's what I am seeing...

- Launching the modal takes a "long time" (not totally sure the best way to debug this so can't provide much more information unfortunately besides "it's slow"). I can tell you that we make an API request to fetch the link token but that only takes about 1 second and there is a significant amount of extra time (>30 seconds) spent waiting after that.

https://user-images.githubusercontent.com/32969087/131591795-21a864ba-e23e-41c2-a2f0-489a9acf2b9f.mp4

<details>
  <summary>Resolved part of original issue</summary>

Our Plaid Link implementation has begun to fail on **Android**. Still looking into recent changes to see if anything on our side could have caused this (perhaps updating React Native to `0.64`). But it _was_ working well and suddenly isn't (so I suspect there is a dependency conflict - but not entirely sure).

Another possibility is that our implementation [here](https://github.com/Expensify/App/blob/993bc0bc52d310c66abfde122c47b7fa60a15122/src/components/PlaidLink/index.native.js#L1-L48) has always been incorrect since we are doing a similar strategy laid out [here](https://github.com/plaid/react-native-plaid-link-sdk/issues/48).

  - Sometimes the Plaid UI does not load at all and results in a screen that looks like this:
![2021-08-31_15-17-36](https://user-images.githubusercontent.com/32969087/131596230-7689760b-e481-4379-91c9-a6234624e01c.png)

This seems similar to what was reported [here](https://github.com/plaid/react-native-plaid-link-sdk/issues/361) but that user mentioned it only happens in release builds (this was on debug) and the error message does not look the same.

- Other times we get an Uncaught error when pressing "Continue" on this screen that looks like this:
![2021-08-31_15-18-44](https://user-images.githubusercontent.com/32969087/131596190-13b45c7c-3733-4e99-9d2b-b06a11de1338.png)
![2021-08-31_15-17-05](https://user-images.githubusercontent.com/32969087/131596198-65daee3a-6e54-47a4-8e57-155646ddc306.png)
```
Invariant Violation: No callback found with cbID 12022 and callID 6011 for  PlaidAndroid.startLinkActivityForResult - most likely the callback was already invoked. Args: '[{"publicToken":"public-sandbox-03be0714-067c-41df-b17f-58c945ce06f3","metadata":{"metadataJson":"{\"institution\":{\"name\":\"Chase\",\"institution_id\":\"ins_3\"},\"account\":{\"id\":null,\"name\":null,\"type\":nul...(truncated)...","linkSessionId":"4bd6f513-fab0-4e53-aebb-56457340f8b2","institution":{"name":"Chase","id":"ins_3"},"accounts":[{"subtype":"checking","mask":"0000","name":"Plaid Checking","type":"depository","id":"jvVjdr8r47Sb1QdAZBa4iEGVWZjQQptyGZZVq"},{"subtype":"savings","mask":"1111","name":"Plaid Saving","type":"depository","id":"7oA6jy9ynXc8oK5E1mLkfraJxmXjjDcN1MMon"}]}}]', js engine: hermes
```
</details>

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.1.0                |
| ReactNative Version     | e.g. 0.64.1               |
| Occurs on Android             | yes                |
| Android OS Version                    | 9                |
| Android Devices/Emulators    | Galaxy S8 physical                |
| Occurs on iOS     | no                |
| iOS Version           | n/a                |
| iOS Devices/Emulators               | n/a                |

# Steps to Reproduce

Our source is open in the project where we are experiencing this issue and there's a linked PR here that updates this package to the latest version (where all these issues were experienced):

https://github.com/Expensify/App/pull/4962

# Expected Result

When the Plaid link modal opens it takes a reasonable amount of time to appear

# Screenshots
If this is a visual bug a screenshot would be helpful.

# Logs
Some device logs (errors + warnings only) here from Flipper (can export JSON if needed)
![2021-08-31_14-07-48](https://user-images.githubusercontent.com/32969087/131591452-a9f4f4ac-02dd-4a7e-ae8e-5651ae03b2af.png)

# Code To Reproduce Issue 
See linked PR above

**Comment by amytang0** [comment]
Thanks for reporting these issues! For future issues, it would be wonderful if these were split up, but as they are:
1. Wow that is indeed some poor lag, and while our web team is currently working on the bundle size, there is at least one clear UI issue (the completely blank screen with no spinner) that I would love to address.
2. This issue unfortunately can stem from a flaky Internet connection; essentially in between receiving the next URL to load and loading the received URL, there is no Internet connection, and thus the webview displays this. We are launching our fully native UI by October, which will no longer have this issue.
3. This issue occurs when Link is opened multiple times (e.g. clicking the button multiple times). This can be mitigated by preventing future clicks or ensuring Link is opened only once per interval.

**Comment by marcaaron** [comment]
Thanks for the quick response @amytang0! 🙇  I'll try some things on my end and break these out into separate issues this afternoon.

>This issue unfortunately can stem from a flaky Internet connection; essentially in between receiving the next URL to load and loading the received URL, there is no Internet connection, and thus the webview displays this. We are launching our fully native UI by October, which will no longer have this issue.

Should we expect some error event to emit when this happens? Flaky connections can happen, but ideally we can return the user back to the start of the flow and ask them to try again later.

>This issue occurs when Link is opened multiple times (e.g. clicking the button multiple times). This can be mitigated by preventing future clicks or ensuring Link is opened only once per interval.

Got it. Can you define an "interval" for me? Is there some way to ensure the Plaid Link is properly cleaned up if the flow is exited? Preventing clicks seems less than ideal because that effectively disables the option to connect via Plaid. What would we suggest to users at that point? "Please force quit the app and reopen to connect with Plaid" 🙃

**Comment by marcaaron** [comment]
Alright, so I tried to reproduce the issue where Link is opened multiple times and verified on my end that **we are doing bad things**. TL;DR, used the `openLink()` method to programmatically open the Link flow and indeed somehow managed to call that method twice.

I'll update this issue accordingly. The slowness still persists after fixing the mistake in our code and I haven't been able to reliably reproduce the Webpage not available error.

**Comment by amytang0** [comment]
> Should we expect some error event to emit when this happens? Flaky connections can happen, but ideally we can return the user back to the start of the flow and ask them to try again later.
That is an excellent point! I will discuss with the team introducing a new `NO_CONNECTIVITY` event (exact name subject to change). As mentioned previously, we have been focusing our efforts on a fully native experience, which will cover this case (and actually display an error to the user to check their connection and retry), but it would probably be useful analytics for everyone to see how often users run into these issues.

> Got it. Can you define an "interval" for me?
This would be setting a debounce interval on the button. Typically we use 200ms (the standard Android animation duration), but honestly pretty arbitrary.

**Comment by marcaaron** [comment]
Quick update, FWIW other members of my team are not reporting any slowness when loading the Plaid Link UI so it's possible the slowness is device or Android OS specific. Will do more testing and see if I find out more.
