### ISSUE TITLE
(iOS 13) onExit & onSuccess not called if modal is dismissed by swiping

### ISSUE THREAD

**Issue by masonwolters** [plaid/react-native-plaid-link-sdk#42]
By default on iOS 13, the Plaid Link view controller is presented with a `modalPresentationStyle` of `UIModalPresentationPageSheet`. This is a [new default](https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e) in iOS 13 and causes the view controller to be able to be swiped interactively to dismiss.

<img src="https://user-images.githubusercontent.com/3914217/72288605-42637100-35fe-11ea-8269-2ea1890655a9.png" width="250" />

This is fine except when the user swipes to dismiss the modal (instead of explicitly pressing the "X" and "Yes, exit") the `onExit` callback is never called.

The same thing happens with the `onSuccess` callback at the end of the flow.

<img src="https://user-images.githubusercontent.com/3914217/72288922-f107b180-35fe-11ea-811c-c4c375ca278d.png" width="250" />

If the user swipes to dismiss this modal (instead of pressing "Finish"), the `onSuccess` callback is never called.

## Workaround

The current workaround I'm using on [my fork](https://github.com/masonwolters/react-native-plaid-link-sdk) is to set `modalInPresentation = YES` on `linkViewController`. This [prevents](https://developer.apple.com/documentation/uikit/uiviewcontroller/3229894-modalinpresentation?language=objc) the view controller from being dismissed by swiping. I don't think this is a good permanent solution though, because ideally you would still be able to swipe to dismiss with the callbacks firing as expected.

**Comment by vafada** [comment]
@masonwolters see #57

**Comment by wkiefer** [comment]
The default is now full screen so callbacks should work as expected. Thanks for the report!
