### ISSUE TITLE
LinkEventMetadata attribute casing not consistent between iOS and Android

### ISSUE THREAD

**Issue by jennifer-dickinson** [plaid/react-native-plaid-link-sdk#422]
# The problem

In trying to handle item-no-error, we found that Android would never receive an `errorCode` from the a link event. Root cause seems to be that `LinkEventMetadata` attribute names are snake case for android.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          |  7.0.5                |
| ReactNative Version     |  0.64.2            |
| Occurs on Android             | yes                |
| Android OS Version                    |  11                |
| Android Devices/Emulators    |  Pixel 4 |
| Occurs on iOS     | no             |
| iOS Version           | n/a            |
| iOS Devices/Emulators               | n/a  |

# Steps to Reproduce
Observe events from `usePlaidEmitter`;
View attribute names `LinkEventMetadata` in Android and compare to iOS.

# Expected Result
Expect meta data to match `LinkEventMetadata` interface

# Screenshots

Top two lines are Android, bottom two lines are iOS.
<img width="1005" alt="Screen Shot 2021-10-21 at 11 22 35 AM" src="https://user-images.githubusercontent.com/12005979/138343174-da19db52-666f-4ec5-996c-224dd08245a2.png">

**Comment by a613** [comment]
Update on this - it is still an issue. We are seeing only camelCase event properties on one platform and only snake_case on the other. This is hard to manage in Amplitude and messes with our funnel tracking. Any update on when this will be fixed?

We are now on Plaid SDK 7.1.0 and pod 2.2.1. Still on React Native 0.64.2.

**Comment by nchase** [comment]
We noticed this too. 

I'd love to know when this might be fixed!

**Comment by dtroupe-plaid** [comment]
Resolved in #532
