### ISSUE TITLE
Plaid issue with React Native V0.59.9

### ISSUE THREAD

**Issue by Statowfiq** [plaid/react-native-plaid-link-sdk#43]
Hi Team,

We are trying to integrate the plaid library with our react native project which is build on react
native version 0.59.9 and react js version 16.8.3. When we run the app then it is showing us the
error to increase the react native version to 0.61.5.
Will this library support older version of react native?
Can we use 0.59.9 version to integrate this library?

**Comment by zsweigart** [comment]
React Native 0.60 was a breaking change and this library is not backwards compatible before that.  We use the latest version; however, you can use previous versions as long as they are 0.60 or greater.
