### ISSUE TITLE
DOCS: a run script still needed for iOS?

### ISSUE THREAD

**Issue by AronBe** [plaid/react-native-plaid-link-sdk#434]
In the **[iOS setup](https://github.com/plaid/react-native-plaid-link-sdk#ios-setup)** there is a step to add a Run Script referenced in[ iOS installation guide](https://plaid.com/docs/link/ios/). But there is no mention of it there, maybe it is not needed anymore?

> Add a Run Script build phase (after the [CP] Embed Pods Frameworks step) to your target as described in Plaid Link for iOS documentation. This strips simulator symbols from App Store release builds.

**Comment by afh** [comment]
Thanks @AronBe, with the introduction of XCFramework in LinkKit 2.x, this is no longer needed.
