### ISSUE TITLE
Not working with Detox

### ISSUE THREAD

**Issue by svenlombaert** [plaid/react-native-plaid-link-sdk#438]
# The problem

I'm trying to run my Detox tests but I always get a Plaid error:

When I remove Plaid from the PackageList (as mention [here](https://github.com/plaid/react-native-plaid-link-sdk#2-add-plaidpackage-to-your-application)) my Detox tests do run correctly.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.1.1               |
| ReactNative Version     | 0.66.3                |
| Occurs on Android             | yes                |
| Android OS Version                    | 12.0.0   /10.0.0            |
| Android Devices/Emulators    | Pixel 4 emulator   + Huawei P30 Pro           |

# Expected Result
I'm able to run my Detox tests with Plaid

# Screenshots
<img src="https://user-images.githubusercontent.com/2846986/146962295-ff080d22-68c4-43fe-8d89-f477b62198cd.png" width="50%" />

**Comment by amytang0** [comment]
It looks like Plaid is being auto-linked, so when you try to manually link the module again, Detox breaks. I would suggest removing Plaid from the PackageList as you have already done. Thanks!
