### ISSUE TITLE
iOS : Statusbar changed after plaid window closed

### ISSUE THREAD

**Issue by kanji-keraliya** [plaid/react-native-plaid-link-sdk#44]
Hello,

We use default status bar and status bar showing properly till open plaid window.
After closing plaid window status bar not restoring as default status bar showing only white status bar with white font,so nothing showing in status bar

**Comment by pilotocheg** [comment]
the same

**Comment by pragyesh12** [comment]
I have same problem. I solve this by using this `    StatusBar.setBarStyle('dark-content');`

**Comment by ShahidAli786** [comment]
I have the same problem. I solve this by using this 
`    StatusBar.setBarStyle('dark-content');`
