### ISSUE TITLE
EventEmitter.removeListener('url', ...): Method has been deprecated.

### ISSUE THREAD

**Issue by roysc1984** [plaid/react-native-plaid-link-sdk#441]
# The problem
console warn on deprecated removeListener function after upgrade react native to 0.66.8

# Environment
latest react-native-plaid-link-sdk
Occurs on iOS: yes
iOS Version: 12

# Expected Result
no warring

**Comment by smeads-sweater** [comment]
This also occurs on Android, specifically seeing this while running a Pixel 5 API 29 simulator.

react-native-plaid-sdk: version 7.2.0
 
![image](https://user-images.githubusercontent.com/82860876/151450257-02b77ffb-a225-424e-ae41-2d01c97c42dd.png)

**Comment by amytang0** [comment]
Thanks for the heads up, we will resolve this in our next month's release

**Comment by mattmcdonald-uk** [comment]
@amytang0 This fix was reverted (8c9d7c03e734aff3cf955d3d7365a8f751542593) which reintroduced this bug.

Any reason why? And is it possible to re-open this issue?

Would a smaller PR that just fixed the deprecated method be accepted?
