### ISSUE TITLE
Loop on automated microdeposit testing flow

### ISSUE THREAD

**Issue by Krisztiaan** [plaid/react-native-plaid-link-sdk#444]
# The problem

When trying to link `Houndstooth Bank (ins_109512)`, after `Account number verification` step, for a brief moment, `Full name` screen is visible, then getting kicked back to starting screen.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | ^7.1.0                |
| ReactNative Version     | 0.64.2               |
| Occurs on Android             | no                |
| Occurs on iOS     | yes                |
| iOS Version           | 14.5                |
| iOS Devices/Emulators               | iPhone 12 - Simulator ONLY                |

# Steps to Reproduce

Walk through "Testing Automated Micro-deposits" on a new account

# Expected Result

Get token, submit to our server

# Screenshots
![Simulator Screen Recording - iPhone 12 - 2022-01-13 at 15 44 39 - 01](https://user-images.githubusercontent.com/4700811/149386182-1a381144-ac74-44ed-bdaa-58b005da7884.gif)

# Logs
`TRANSITION_VIEW` event triggered before returning to start

**Comment by amytang0** [comment]
Any chance you can grab a `link_session_id` or the `link_token` used? This does indeed look like incorrect behavior
