### ISSUE TITLE
How to filter an institution?

### ISSUE THREAD

**Issue by jetaix** [plaid/react-native-plaid-link-sdk#445]
I'm looking for directly redirect to a filtered list by institution, because in my case the search is handle before/outside opening the Plaid SDK.

**Expected output:**

have only one bank "selected/filtered"

<img src="https://user-images.githubusercontent.com/4866709/149415941-6caf5b8f-e11c-4578-afb5-4a2de5b7c0d3.jpeg" width="250" >

Any idea how to achieve this ?

**Comment by amytang0** [comment]
Hi, please contact support@plaid.com or your account manager for more information on this.
