### ISSUE TITLE
Getting error after upgrading from v5 to v7

### ISSUE THREAD

**Issue by JJ810** [plaid/react-native-plaid-link-sdk#454]
# The problem

I upgraded from v5 to v7 for the typescript support and now I am getting an error while building the app on Xcode.
I need to fix this issue asap so would be appreciate if you can help me with this as soon as you can.

Thanks in advance!

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.0                |
| ReactNative Version     | 0.63.4                |
| Occurs on Android             | didn't try yet                |
| Android OS Version                    |                 |
| Android Devices/Emulators    |       |
| Occurs on iOS     | yes                |
| iOS Version           | 15.2                |
| iOS Devices/Emulators               | iPhone 13 Simulator                |

# Steps to Reproduce

```
yarn add react-native-plaid-link-sdk@latest
// Update Podfile
pod 'Plaid', '~> 2.3.2' // originally '=1.1.34'
cd ios && pod install --repo-update
```

# Expected Result
Successful build

# Screenshots
![Screen Shot 2022-02-01 at 12 02 39 PM](https://user-images.githubusercontent.com/59910709/152015129-fbd6c960-dfb2-4b09-860a-e3facba35370.png)

# Logs
/Users/xxxx/Library/Developer/Xcode/DerivedData/SimbaApp-cfzwhqqjeyiawjeilxblgwleggbd/Build/Intermediates.noindex/SimbaApp.build/Debug Dev-iphonesimulator/SimbaApp.build/Script-B9FFC60E2474355500CA700A.sh: line 4: /Users/xxxx/Library/Developer/Xcode/DerivedData/SimbaApp-cfzwhqqjeyiawjeilxblgwleggbd/Build/Products/Debug Dev-iphonesimulator/Internal.app/Frameworks/LinkKit.framework/prepare_for_distribution.sh: No such file or directory

**Comment by afh** [comment]
Thanks for reaching out, @JJ810. Since the upgrade from v5 to v7 includes a major version upgrade on the underlying LinkKit library please review the [Reference for migrating the Link iOS SDK from 1.x to 2.x](https://plaid.com/docs/link/ios/ios-v2-migration/), especially the section on [remov[ing] the custom "Prepare for distribution" Build Phase](https://plaid.com/docs/link/ios/ios-v2-migration/#remove-the-custom-prepare-for-distribution-build-phase).

**Comment by JJ810** [comment]
@afh, I still am getting the same error. I followed this step -  https://plaid.com/docs/link/react-native/react-native-v5-v7-migration/

The link you shared with me doesn't seem to correct for my issue because I am on React Native not iOS native.

**Comment by afh** [comment]
@JJ810 `react-native-plaid-link-sdk` is a react-native bridge to the native Plaid Link iOS SDK, and internally [uses](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/react-native-plaid-link-sdk.podspec#L19) the [Plaid Cocoapod](https://cocoapods.org/pods/Plaid) (a.k.a LinkKit).

Version 5 of `react-native-plaid-link-sdk`  used LinkKit 1.x and version 7 requires LinkKit 2.x, so when upgrading from `react-native-plaid-link-sdk` version 5 to version 7 any native LinkKit migration steps from version 1.x to 2.x need to be applied, hence the note in my previous comment to _review the [Reference for migrating the Link iOS SDK from 1.x to 2.x](https://plaid.com/docs/link/ios/ios-v2-migration/), especially the section on [remov[ing] the custom "Prepare for distribution" Build Phase](https://plaid.com/docs/link/ios/ios-v2-migration/#remove-the-custom-prepare-for-distribution-build-phase)._

Please check whether there is a custom **Run Script Build Phase** in your Xcode project that calls `prepare_for_distribution.sh` and remove it.

**Comment by JJ810** [comment]
@afh, thank you so much! I was able to fix my issue!

**Comment by afh** [comment]
Glad to hear that you were able to fix the issue, @JJ810 🙂
