### ISSUE TITLE
Does Android auto-linking work now?

### ISSUE THREAD

**Issue by djMax** [plaid/react-native-plaid-link-sdk#456]
# The problem

After upgrading to React Native 0.67.4, I get an error:

```
2022-02-02 19:59:11.640 3736-7729/gbis.gbandroid E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: Native module PlaidAndroid tried to override com.reactlibrary.PlaidModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true. This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. Try removing the existing entry and rebuild.
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:55)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1462)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1433)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1327)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1104)
        at java.lang.Thread.run(Thread.java:923)
```

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.6                |
| ReactNative Version     | 0.67.4                |
| Occurs on Android             | yes                |
| Android OS Version                    | 32                |
| Android Devices/Emulators    | Samsung SM-F916U physical                |
| Occurs on iOS     | no                |

# Steps to Reproduce

Implement as specified by adding to getPackages() in MainApplication

# Expected Result

The app should run.

I can diagnose more, but first wanted to check whether something has changed in the toolchain that makes a thing that didn't used to work, work. I notice that in the generated "PackageList.java" has the PlaidPackage in it.

**Comment by Pfuster12** [comment]
Encountered same error, I have commented out this line in `MainActivity.java` and my App now runs in the simulator.
```java
packages.add(new PlaidPackage());
```

My package.json:
```json
"react-native": "^0.67.2",
"react-native-plaid-link-sdk": "^7.2.1",
```

**Comment by amytang0** [comment]
Yes, auto-linking works with newer React Native versions!

**Comment by JayFeldman12** [comment]
It would be great if the documentation could be updated to say that! Right now the documentation says
> [Autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) unfortunately isn't supported for Android, because the SDK makes use of https://github.com/react-native-community/discussions-and-proposals/issues/40 to speed up app cold starts. Have a look at https://github.com/plaid/react-native-plaid-link-sdk/pull/306 for more context.

And the installations steps below say

> Add packages.add(new PlaidPackage()); to List<ReactPackage> getPackages();

This actually causes a crash on the latest version of react native, saying there's multiple instances of the same dependency added. The error does point towards removing the packages.add line, but it's confusing when the documentation says you need that line.
