### ISSUE TITLE
IllegalStateException though token is being passed

### ISSUE THREAD

**Issue by dnvarun** [plaid/react-native-plaid-link-sdk#459]
# The problem

A fraction of users are facing crash with exception `IllegalStateException: Token must be part of configuration.` . We are sure we are passing the token while opening the plaid link.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.0.6                |
| ReactNative Version     | 0.63.2                |
| Occurs on Android             | yes                |
| Android OS Version                    | 11                |
| Android Devices/Emulators    | Multiple                |
| Occurs on iOS     | not sure                |
| iOS Version           | NA                |
| iOS Devices/Emulators               | NA                |

# Steps to Reproduce
As I said earlier, only a fraction of users are facing this issue. From our tracking events, we see the following behavior:
- User tries to open Link
- Our debug event gets logged indicating the token being passed to Link
- Link does not open. We are guessing that Link does not open at all because we dont get the `OPEN` event callback from Link.
- User moves on to some other part of the app.
- App crashes with `IllegalStateException: Token must be part of configuration` after a few seconds. We also saw one crash 35 seconds after trying to unsuccessfully open Link

# Expected Result
What did you expect to happen?
No crash

# Screenshots
NA

# Logs
NA

# Code To Reproduce Issue 
NA

**Comment by mashaalmemon** [comment]
We are also facing this issue. Using `openLink` directly vs the `PlaidLink` component. Any progress on this?

**Comment by dtroupe-plaid** [comment]
Closing because Plaid Link React Native 7.x.x is no longer supported. If the issue persists in the latest SDK please open a new issue.
