### ISSUE TITLE
Select Account step not showing

### ISSUE THREAD

**Issue by Dassine** [plaid/react-native-plaid-link-sdk#463]
# The problem

I started testing our sandbox last week and I was able to select accounts. Since yesterday, after signing in with user_good / pass_good, I land right away on Success screen. As you can see I'm mentioning that selectAccount should be displayed.

```
 <PlaidLink
              name="Roo"
              product={['auth']}
              **selectAccount={true}**
              tokenConfig={{
                token: token,
              }}
             ...
```

See the video of 02/14 and today 02/18

https://drive.google.com/drive/folders/1LdiYfMTBHUyM8p5Am_ryA1JezfulMIk5?usp=sharing

Is there any configuration that needs to be done? 
Is there anyone who can help with this? 

Thanks.

**Comment by phoenixy1** [comment]
@Dassine Are you using a recent version of this library with link tokens? Except for `tokenConfig`, none of the options your example is setting PlaidLink are presently configured client-side. Select account, for example, is configured on the plaid dashboard at https://dashboard.plaid.com/link/account-select
