### ISSUE TITLE
TS: LinkEventMetadata interface does not include "selection" field

### ISSUE THREAD

**Issue by smeads-sweater** [plaid/react-native-plaid-link-sdk#465]
# The Problem
First off, thank you for an awesome solution for using PlaidLink in a RN project.

PlaidLink's [documentation](https://plaid.com/docs/link/react-native/#link-react_native-onevent-metadata-selection) for React Native shows a `selection` field returned on the `metadata` object when the emitted event is `MATCHED_SELECT_VERIFY_METHOD`. However, the `selection` field is not currently included on the `LinkEventMetadata` interface and throws a TS error `Property 'selection' does not exist on type 'LinkEventMetadata'.`.

## Solution
Add the `selection` field and type on the `LinkEventMetadata` interface.

```
export interface LinkEventMetadata {
    otherFields...
    selection?: 'phoneotp' | 'password';
}
```

I apologize if `selection` isn't intended to be returned for RN in this scenario and the issue is an oversight on my part. In any case, the interface needs to be updated or the documentation.

Thank you!

**Comment by amytang0** [comment]
Thanks for bringing this to our attention! Happy to accept a PR and/or add this to our roadmap

**Comment by smeads-sweater** [comment]
> Thanks for bringing this to our attention! Happy to accept a PR and/or add this to our roadmap

@amytang0  I've got a PR ready to push up but it looks like I'll need permission to do so.

**Comment by amytang0** [comment]
Great! Curious what the precise error is (and would appreciate a copypasta) but a quick pre-diagnosis questions would be:
Are you trying to push to `master` branch? Please open a new branch instead.

Thanks!

**Comment by smeads-sweater** [comment]
@amytang0 No, I'm not trying to push to master. I'm working off of a branch.

```
ERROR: Permission to plaid/react-native-plaid-link-sdk.git denied to smeads-sweater.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by amytang0** [comment]
Sounds good, I'll look into the report permissions
