### ISSUE TITLE
Update the docs: Auto-linking works on android too

### ISSUE THREAD

**Issue by KROSF** [plaid/react-native-plaid-link-sdk#467]
# The problem

The docs are pointing that auto-linking is not working for android

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 73.0              |
| ReactNative Version     | 0.67.3              |
| Occurs on Android             |  yes                |
| Android OS Version                    | 11 (30)                |
| Android Devices/Emulators    | OnePlus AC2003 (Nord)               |

# The solution

Update docs to indicate auto-linking is working now at least for version >= 0.67.x

**Comment by dtroupe-plaid** [comment]
#538 Resolves this
