### ISSUE TITLE
Results for iOS and Android differ

### ISSUE THREAD

**Issue by gfreakcs** [plaid/react-native-plaid-link-sdk#47]
During selection:
1. iOS shows all accounts
![image](https://user-images.githubusercontent.com/2677477/73723216-7ea07200-4763-11ea-98e5-930d78d3f32e.png)

2. Android shows only depository types (checkings, savings)
![image](https://user-images.githubusercontent.com/2677477/73723245-89f39d80-4763-11ea-8bf8-bb40bf752747.png)

onSuccess:
1. iOS
```
{
  "account": {
    "id": "<account ID>",
    "mask": "0000",
    "name": "Plaid Checking",
    "subtype": "checking",
    "type": "depository"
  },
  "account_id": "<account ID>",
  "accounts": [
    {
      "id": "<account ID>",
      "mask": "0000",
      "name": "Plaid Checking",
      "subtype": "checking",
      "type": "depository"
    }
  ],
  "institution": {
    "institution_id": "ins_6",
    "name": "US Bank"
  },
  "link_session_id": "<link session ID>",
  "public_token": "<public token>",
  "request_id": "<request ID>",
  "status": "connected"
}
```

2. Android
```
{
  "link_connection_metadata": {
    "accounts": [[Object]],
    "institution_id": "ins_6",
    "institution_name": "US Bank",
    "link_session_id": "<link session ID>",
    "raw_data": {
      "account_id": "<account ID>",
      "account_mask": "0000",
      "account_name": "Plaid Checking",
      "account_subtype": "checking",
      "account_type": "depository",
      "accounts": "[{\"_id\":\"<account ID>\",\"balance\":{\"available\":100,\"currency\":\"USD\",\"current\":110,\"localized\":{\"available\":\"$100.00\",\"current\":\"$110.00\"}},\"meta\":{\"name\":\"Plaid Checking\",\"number\":\"0000\"},\"type\":\"depository\",\"subtype\":\"checking\"}]",
      "institution_id": "ins_6",
      "institution_name": "US Bank",
      "link_session_id": "<link session ID>",
      "public_token": "<public token>"
    }
  },
  "public_token": "<public token>"
}
```

`<PlaidLink />` variable is the same as default configuration 

Is this normal and should we just write code to query for platform?

**Comment by amarnadhb4u** [comment]
Is there a way to restrict subtype?

**Comment by zsweigart** [comment]
@gfreakcs thanks for the input.  We have noted the inconsistencies and will review them for the next release.

**Comment by eltonbasha** [comment]
@zsweigart Hi when is the next release going to be available? Thank you.

**Comment by zsweigart** [comment]
The next release is planned for mid-march.  This is a current inconsistency between iOS vs web/Android and there are no current plans to patch it so it will remain inconsistent in RN

**Comment by khazizaj** [comment]
@zsweigart A couple of questions in relation to aiding our own development processes:
Will both listed issues remain inconsistent for the next release? The different responses for both platforms can be handled, but the iOS bridge listing all accounts instead of only listing the depository types, does present as a significant issue for our live products. 
If we could have some feedback on how this might be prioritized, it would be quite helpful towards planning our own product releases; since alternatives need to be taken under consideration if this issue is not addressed promptly. Moreover, if this patch will not be planned as part of your next upcoming rollout, will this issue at least be handled in future iterations?

**Comment by wkiefer** [comment]
@khazizaj and @gfreakcs — what products are you passing in during initialization?

We'll be adding docs and support for account type filtering in the next release, which will ensure your results are the same on both platforms.

**Comment by khazizaj** [comment]
Hello, 
Do you have an approximate date on the release including the fix for account type filtering (discussed above)?

**Comment by gfreakcs** [comment]
> @khazizaj and @gfreakcs — what products are you passing in during initialization?
> 
> We'll be adding docs and support for account type filtering in the next release, which will ensure your results are the same on both platforms.

We are passing ['auth', 'identity']

**Comment by gfreakcs** [comment]
Just checking in if there is a fix for the iOS account filter to just show checking and savings?

**Comment by jacobparish** [comment]
Will this be fixed anytime soon? Even in the most recent release, the formats are still different, although they differ from what was posted in this issue (in particular, android is now has just a "metadata" property instead of "link_connection_metadata")

**Comment by tbadlov** [comment]
@wkiefer any update on this? It is quite problematic for us to move to your supported SDK given that updates Chase and Wells Fargo are imposing on us to leverage OAuth verification. Any update when will this be addressed?

**Comment by zsweigart** [comment]
Hi @tbadlov we will be releasing the next version of our native SDKs on 9/21.  The react native update will follow on 9/28 which will unify the results and have full support for OAuth verification.  Thank you for your patience

**Comment by ereio** [comment]
@zsweigart looking forward to this release. We're waiting to integrate on both iOS and Android until the payloads are the same. Any updates on progress?

**Comment by agamadev** [comment]
@zsweigart - I know you guys are working hard with the next update. We just made a different implementation for Android and it's now on the stores. It would be helpful if you guys can please let us know the exact date when this release is going to happen, so we can remove our implementation and have the same callback for iOS and Android beforehand; otherwise the Plaid integration for Android will fail for us and other people who made the same. Thanks!

**Comment by amytang0** [comment]
Sorry for the delay, 6.0.2 should have the same payloads in `onSuccess` and `onExit`. For `onEvent`, Android is still returning a json object for event names, but is otherwise returning the same payload. We will flatten this object in the next release

**Comment by agamadev** [comment]
Thanks @amytang0 - We are using the version 6.0.2-rc4 and can confirm that the response is still different. As mentioned, we made a different implementation (basically a parser) for Android.

**Comment by amytang0** [comment]
Hey would you mind sharing the differing results? Thanks!

**Comment by agamadev** [comment]
Hi @amytang0 - It seems that you guys are currently working on the output, two days ago the structure and issues were different:

- For Android, metadata_json did not exist, just medatada
- For iOS, metadata_json existed but not inside metadata, since this last one did not exist
- For iOS, when parsing metadata_json to a JSON object (it comes as a string), it did not work, but it worked for Android
- For iOS, the log asked yesterday to upgrade from Plaid 2.1 to 2.3

Because the previous reasons, we did not use metadata_json and instead we used metadata.accounts and metadata.institution, and in the outputs you can see that as of today, these two are still different:

iOS

```
{
   "public_token":"public-sandbox-8a514574-e7c5-414a-87e1-13364e59ec9d",
   "metadata":{
      "metadata_json":{
         "institution":{
            "name":"RBC Royal Bank",
            "institution_id":"ins_39"
         },
         "account":{
            "id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
            "name":"Plaid Checking",
            "type":"depository",
            "subtype":"checking",
            "mask":"0000"
         },
         "account_id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
         "accounts":[
            {
               "id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
               "name":"Plaid Checking",
               "mask":"0000",
               "type":"depository",
               "subtype":"checking"
            }
         ],
         "link_session_id":"4991b4b1-87db-497d-b191-0227d59de255",
         "public_token":"public-sandbox-8a514574-e7c5-414a-87e1-13364e59ec9d"
      },
      "link_session_id":"4991b4b1-87db-497d-b191-0227d59de255",
      "accounts":[
         {
            "type":"depository",
            "id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
            "verification_status":"",
            "mask":"",
            "name":"Plaid Checking",
            "subtype":"checking"
         }
      ],
      "institution":{
         "name":"RBC Royal Bank",
         "institution_id":"ins_39"
      }
   }
}
```

Android:

```
{
   "public_token":"public-sandbox-b03e57ad-d5ee-4ed2-9071-12d28b109f40",
   "metadata":{
      "metadata_json":{
         "institution":{
            "name":"RBC Royal Bank",
            "institution_id":"ins_39"
         },
         "account":{
            "id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR",
            "name":"Plaid Checking",
            "type":"depository",
            "subtype":"checking",
            "mask":"0000"
         },
         "account_id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR",
         "accounts":[
            {
               "id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR",
               "name":"Plaid Checking",
               "mask":"0000",
               "type":"depository",
               "subtype":"checking"
            }
         ],
         "link_session_id":"b0d8d066-5241-4eb2-bea0-f4cf79348b27",
         "public_token":"public-sandbox-b03e57ad-d5ee-4ed2-9071-12d28b109f40"
      },
      "link_session_id":"b0d8d066-5241-4eb2-bea0-f4cf79348b27",
      "institution":{
         "institution_name":"RBC Royal Bank",
         "institution_id":"ins_39"
      },
      "accounts":[
         {
            "subtype":{
               "json":"checking",
               "account_type":{
                  "json":"depository"
               }
            },
            "mask":"0000",
            "name":"Plaid Checking",
            "id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR"
         }
      ]
   }
}
```

Since now metadata_json is inside metadata for both iOS and Android, and for iOS we could parsed it properly, we are going to change the implementation and use metadata_json only. 

If anything else comes up, I will let you know!

**Comment by agamadev** [comment]
Hi @amytang0 - It seems that you guys are currently working on the output, two days ago the structure and issues were different:

- For Android, metadata_json did not exist, just medatada
- For iOS, metadata_json existed but not inside metadata, since this last one did not exist
- For iOS, when parsing metadata_json to a JSON object (it comes as a string), it did not work, but it worked for Android
- For iOS, the log asked yesterday to upgrade from Plaid 2.1 to 2.3

Because the previous reasons, we did not use metadata_json and instead we used metadata.accounts and metadata.institution, and in the outputs you can see that as of today, these two are still different:

iOS

```
{
   "public_token":"<public token>",
   "metadata":{
      "metadata_json":{
         "institution":{
            "name":"RBC Royal Bank",
            "institution_id":"ins_39"
         },
         "account":{
            "id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
            "name":"Plaid Checking",
            "type":"depository",
            "subtype":"checking",
            "mask":"0000"
         },
         "account_id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
         "accounts":[
            {
               "id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
               "name":"Plaid Checking",
               "mask":"0000",
               "type":"depository",
               "subtype":"checking"
            }
         ],
         "link_session_id":"<link session id>",
         "public_token":"<public token>"
      },
      "link_session_id":"<link session id>",
      "accounts":[
         {
            "type":"depository",
            "id":"gyZd8g9r48iB8nEzKByeFv8Pnwz9WeigRXVwQ",
            "verification_status":"",
            "mask":"",
            "name":"Plaid Checking",
            "subtype":"checking"
         }
      ],
      "institution":{
         "name":"RBC Royal Bank",
         "institution_id":"ins_39"
      }
   }
}
```

Android:

```
{
   "public_token":"<public token>",
   "metadata":{
      "metadata_json":{
         "institution":{
            "name":"RBC Royal Bank",
            "institution_id":"ins_39"
         },
         "account":{
            "id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR",
            "name":"Plaid Checking",
            "type":"depository",
            "subtype":"checking",
            "mask":"0000"
         },
         "account_id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR",
         "accounts":[
            {
               "id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR",
               "name":"Plaid Checking",
               "mask":"0000",
               "type":"depository",
               "subtype":"checking"
            }
         ],
         "link_session_id":"<link session id>",
         "public_token":"<public token>"
      },
      "link_session_id":"<link session id>",
      "institution":{
         "institution_name":"RBC Royal Bank",
         "institution_id":"ins_39"
      },
      "accounts":[
         {
            "subtype":{
               "json":"checking",
               "account_type":{
                  "json":"depository"
               }
            },
            "mask":"0000",
            "name":"Plaid Checking",
            "id":"JJL9l5qMjwC39K1kj74Au9qJVN6Dz3TdLGwaR"
         }
      ]
   }
}
```

Since now metadata_json is inside metadata for both iOS and Android, and for iOS we could parsed it properly, we are going to change the implementation and use metadata_json only. 

If anything else comes up, I will let you know!

**Comment by jack-fin** [comment]
@agamadev Are you still seeing metadata_json in both responses? I am seeing different responses between Android and iOS as well, but different from yours:
iOS:
```
{
	"account": {
		"id": "9XW7b76orwinWJDBaLjqfWB5VlqdajuRyaPyE",
		"mask": "3333",
		"name": "Plaid Credit Card",
		"subtype": "credit card",
		"type": "credit"
	},
	"account_id": "9XW7b76orwinWJDBaLjqfWB5VlqdajuRyaPyE",
	"accounts": [{
		"id": "9XW7b76orwinWJDBaLjqfWB5VlqdajuRyaPyE",
		"mask": "3333",
		"name": "Plaid Credit Card",
		"subtype": "credit card",
		"type": "credit"
	}],
	"institution": {
		"institution_id": "ins_16",
		"name": "SunTrust - Online Banking"
	},
	"link_session_id": "ffdd7723-bc9e-456f-b651-a5b5fbbeb391",
	"public_token": "public-sandbox-376ad95f-944a-4e56-9136-c9b11c63f7b0",
	"request_id": "fetobpOA1KtZWQe",
	"status": "connected"
}
```

Android:
```
{
	"metadata": {
		"accounts": [
			[Object]
		],
		"institution": {
			"institution_id": "ins_16",
			"institution_name": "SunTrust - Online Banking"
		},
		"link_session_id": "7cc5a856-ffd5-48d5-b74f-de7640fa7756",
		"metadata_json": "{\"institution\":{\"name\":\"SunTrust - Online Banking\",\"institution_id\":\"ins_16\"},\"account\":{\"id\":\"dKd3NnwZjeC418rxkqaKunqeaPV99xfZqgzk7\",\"name\":\"Plaid Credit Card\",\"type\":\"credit\",\"subtype\":\"credit card\",\"mask\":\"3333\"},\"account_id\":\"dKd3NnwZjeC418rxkqaKunqeaPV99xfZqgzk7\",\"accounts\":[{\"id\":\"dKd3NnwZjeC418rxkqaKunqeaPV99xfZqgzk7\",\"name\":\"Plaid Credit Card\",\"mask\":\"3333\",\"type\":\"credit\",\"subtype\":\"credit card\"}],\"link_session_id\":\"7cc5a856-ffd5-48d5-b74f-de7640fa7756\",\"public_token\":\"public-sandbox-978aa3b0-3a6a-4d6f-af9d-c40af1df7235\"}"
	},
	"public_token": "public-sandbox-978aa3b0-3a6a-4d6f-af9d-c40af1df7235"
}
```
