### ISSUE TITLE
PlaidModule.startLinkActivityForResult: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by Bhavik-P** [plaid/react-native-plaid-link-sdk#473]
# The problem

Getting a Null Pointer Exception coming from the PlaidModule class when calling the function startLinkActivityForResult. it seems like this function accepts a non-null parameter however the parameter that is passed to it is null. I'm not exactly sure what the user is seeing on their end but I would suspect that it's a hard crash.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          |  7.0.7              |
| ReactNative Version     | 0.65.1               |
| Occurs on Android             |  Yes               |
| Android OS Version                    | Android 9, 10, 12                |
| Android Devices/Emulators    |  Only seen on various Samsung devices                |
| Occurs on iOS     |  No                |
| iOS Version           | N/A                |
| iOS Devices/Emulators               | N/A                |

# Steps to Reproduce
Not sure exactly how to reproduce. The behavior is not consistent. It does work for majority of our users.

# Expected Result
A successful Plaid Link

# Screenshots
N/A

# Logs
```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter data
        at com.plaid.PlaidModule.startLinkActivityForResult(Unknown:4)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(SourceFile:-2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:8)
        at java.lang.Thread.run(Thread.java:920)
```

# Code To Reproduce Issue 
With sample code it's easier to reproduce the bug and it's much faster to fix it. 
Don't forget to omit any keys or personally identifiable information.
Please provide one of the following:

1. (Best) A link to a minimal demo app showing the faulty behaviour.
1. (Better) A concise code sample which can be dropped into fresh application
1. A snippet of code for your configuration for opening Link

**Comment by amytang0** [comment]
Can you upgrade to latest 7.4.0 and see if this issue still repros?

**Comment by Bhavik-P** [comment]
@amytang0 we can't upgrade to v7.4.0 as it implements version 3.4.1 of react-link-android which requires compileSdkVersion to be set at 31. See https://github.com/plaid/react-native-plaid-link-sdk/issues/477. At this moment we are unable to upgrade. I am looking at the diff in that file between v7.0.7 and v7.4.0 (see: https://github.com/plaid/react-native-plaid-link-sdk/compare/v7.0.7...v7.4.0) and it doesn't seem like there is any directly correlated with a potential fix.

**Comment by amytang0** [comment]
Could you try [v7.2.1](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v7.2.1) (does not require 3.7.1 compileSDKVersion 31)?

It's hard to tell the difference by looking purely at the RN versions since they are wrappers over the native Android SDKs, but I suspect the fix is in the Android versions between 7.0.7 and 7.2.1

**Comment by Bhavik-P** [comment]
@amytang0 When I try to install react-native-plaid-link-sdk version 7.2.1 via NPM it says that package version is not found. The latest one I am able to install is version 7.1.0.

**Comment by amytang0** [comment]
https://www.npmjs.com/package/react-native-plaid-link-sdk/v/7.1.0

What error are you receiving?

**Comment by Bhavik-P** [comment]
@amytang0 this is the exact error message I get:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-plaid-link-sdk@7.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
```

My package.json file includes this line:
```
"react-native-plaid-link-sdk": "7.2.1",
```

If I do it the following way it works:
```
"react-native-plaid-link-sdk": "github:plaid/react-native-plaid-link-sdk#v7.2.1",
```

**Comment by dtroupe-plaid** [comment]
Closing because Plaid Link React Native 7.x.x is no longer supported. If the issue persists in the latest SDK please open a new issue.
