### ISSUE TITLE
Important/breaking changes should be called out in release notes (e.g. mininum Android `compileSdkVersion`)

### ISSUE THREAD

**Issue by jarredt** [plaid/react-native-plaid-link-sdk#477]
Hello! Wanted to provide some feedback on the release notes based on a recent experience.

Version 7.3.0 of `react-native-plaid-link-sdk` implements version 3.7.1 of `plaid-link-android`. That version of `plaid-link-android` apparently requires that our app's `compileSdkVersion` be set to at least `31`. This is called out in the `plaid-link-android` release notes for that version, which I happened to go look at this time -- but it's not called out in the release notes for `react-native-plaid-link-sdk`. This requirement also isn't called out in the README for `react-native-plaid-link-sdk` -- it only mentions the `minSdkVersion` must be >= 21.

At a minimum, it would be great if the `react-native-plaid-link-sdk` would directly link to the release notes for the underlying native SDKs so it's easier to go inspect the changes ourselves. That said, it would be ideal to have any key changes/requirements from the native SDK updates called out explicitly in `react-native-plaid-link-sdk` release notes, so that we know exactly what actions we may need to take (since part of the benefit of this library is not having to overly worry about the workings of the underlying native SDKs).

It would also be great to update the main README with this new requirement.

Thank you!

**Comment by jarredt** [comment]
Bumping this feedback @amytang0 -- it's a lot of work for us to have to go find the underlying native repos and check their changelogs, whenever this wrapper updates to include those new versions. It would be really helpful if the changelog for this wrapper lib could call out any important/breaking changes, or at minimum, please link to the iOS/Android lib changelogs so it's easier for us to find them.

**Comment by dtroupe-plaid** [comment]
@jarredt thanks for flagging this issue. #537 addresses this.
