### ISSUE TITLE
Instead of pubik-token, we are getting "no result returned" in response.

### ISSUE THREAD

**Issue by ssasite** [plaid/react-native-plaid-link-sdk#483]
# The problem

At last step after the success screen when we get back to the app, where we expect public_token from the API response, it is returning error object with message as "No result returned."

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.2.1                |
| ReactNative Version     | 0.66.0                |
| Occurs on Android             |  yes                |
| Android OS Version                    | Android 11                |

# Steps to Reproduce

Simply try to connect to bank on sandbox with a link token generated.

# Expected Result
The API should return public_token after success screen.

# Logs
error:
displayMessage: "No result returned."
errorCode: "No result returned."
errorDisplayMessage: "No result returned."
errorMessage: "No result returned."
[[Prototype]]: Object
metadata: {}

I can share the request_id if required to check.

**Comment by dtroupe-plaid** [comment]
Closing because Plaid Link React Native 7.x.x is no longer supported. If the issue persists in the latest SDK please open a new issue.
