### ISSUE TITLE
Android app showing white screen after doing OAuth in bank and app callback

### ISSUE THREAD

**Issue by congkhanh197** [plaid/react-native-plaid-link-sdk#492]
# The problem

Android app showing white screen after doing OAuth in bank and app callback. I try to update `android:launchMode="singleInstance"`, it show error screen.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 8.0.0                |
| ReactNative Version     | 0.66.3                |
| Occurs on Android             | yes                |
| Android OS Version                    | 9.0.0 (28)                |
| Android Devices/Emulators    | Pixel 4 Emulator                |
| Occurs on iOS     | no               |

# Steps to Reproduce

- Get plaid link_token.
- Click on plaid link. Choose Chase bank
- Navigate to bank OAuth
- Done OAuth, choose the app to callback to the app.
```
{
  "client_id": "xxx",
  "secret": "xxx",
  "user": .....,
  "client_name": "xxx",
  "country_code": [
    "US",
    "CA",
    "GB",
    "FR",
    "ES",
    "IE",
    "NL"
  ],
  "language": "en",
  "webhook": "/api/webhooks/plaid",
  "update": false,
  "link_customization_name": "default",
  "product": ["transactions"],
  "android_package_name": "com.test.abc"
}
```

# Expected Result
Should return the Plaid Link screen with public-token

# Screenshots
<img width="435" alt="Screen Shot 2022-08-05 at 19 16 20" src="https://user-images.githubusercontent.com/15651028/183336853-931b7c0d-5f91-47c4-8f1d-eeaaa2086258.png">

# Code To Reproduce Issue 
```
<PlaidLink
          tokenConfig={{
            token: linkToken,
            noLoadingState: false,
          }}
          onSuccess={onSuccess}
          onExit={(data) => {
            toaster.show({ message: JSON.stringify(data, null, 2), type: 'error', duration: 10000, position: 'top' });
          }}>
          <View>
            <Text>Button</Text>
          </View>
</PlaidLink>

**Comment by congkhanh197** [comment]
I think the error related to [this issue](https://github.com/plaid/react-native-plaid-link-sdk/issues/483) I try to revert the plaid link react native to 7.4.0, it resolve the white screen issue. But the error message still show.

**Comment by dtroupe-plaid** [comment]
Closing because Plaid Link React Native 8.x.x is no longer supported. If the issue persists in the latest SDK please open a new issue.
