### ISSUE TITLE
Android cannot redirect to application after selecting a bank account

### ISSUE THREAD

**Issue by cphongsa** [plaid/react-native-plaid-link-sdk#499]
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to the Plaid Link 
React Native SDK). Tell us what you were trying to do and what happened instead. 

We are attempting to ensure that both our iOS and Android applications can handle the new Plaid Oauth requirements. We have been able to find that iOS works as expected. However, we are running into issues with Android. According to the [Plaid docs](https://plaid.com/docs/link/oauth/#android-sdk-react-native-android), we will only need to add the `android_package_name`. Please view **Steps to Reproduce** to see our issue and how to reproduce it.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 7.1.1               |
| ReactNative Version     | 0.62.3                |
| Occurs on Android             | yes                |
| Android OS Version                    | 11                |
| Android Devices/Emulators    | Pixel XL emulator                |
| Occurs on iOS     | no               |
| iOS Version           | 11                |
| iOS Devices/Emulators               | iPhone X                |

# Steps to Reproduce
- Create plaid link token
- Open plaid link
- Search for `Platypus OAuth Bank`
- Expect to be navigated to `WebView Browser Tester` within the application
- Enter necessary credentials
- Select either the Checking or Savings account
- Reach this error when attempting to navigate back to the application after pressing `Connect account information`

<img width="398" alt="image (1)" src="https://user-images.githubusercontent.com/85261067/184759661-104762b0-a542-45db-ac34-271474bd9b43.png">

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

For example:
```
{
   "client_id":"OMITTED",
   "secret":"OMITTED",
   "user":{
      "client_user_id":"OMITTED",
      "legal_name":"OMITTED"
   },
   "client_name":"My application",
   "products":[
      "auth"
   ],
   "country_codes":[
      "US"
   ],
   "language":"en",
   "android_package_name":"com.mycompany.myapp"
}
```

# Expected Result
What did you expect to happen?
We expected the WebView Browser Tester to be closed and to continue with our in-app plaid flow

**Comment by dtroupe-plaid** [comment]
Closing because Plaid Link React Native 7.x.x is no longer supported. If the issue persists in the latest SDK please open a new issue.
