### ISSUE TITLE
Support for EU 

### ISSUE THREAD

**Issue by AdamAwan** [plaid/react-native-plaid-link-sdk#51]
Hello,

It seems the current version of this sdk does not support EU OAuth integrations as it's missing an option to set the `oauthNonce` and `oauthRedirectUri` values as specified here; https://plaid.com/docs/#oauth-requirements-for-webview-integrations-in-europe

Is this something that is planned to be supported?

**Comment by VasiliSolodar** [comment]
have you tried `webviewRedirectUri ` to pass callback url?

**Comment by AdamAwan** [comment]
Sorry for the delay in response.

Yes I have tried that, it's currently set as a url for a deep link back into the app. My current configuration is like so;

```
<PlaidLink
      publicKey="______"
      clientName="______"
      env="sandbox" 
      product={['transactions']}
      webviewRedirectUri="com.myapp://plaid/redirect"
      onSuccess={data => console.log('success: ', data)}
      onExit={data => console.log('exit: ', data)}
      countryCodes={['GB']}
      language="en"
      <Text>Add Account</Text>
    </PlaidLink>
```

After authorisation I'm being redirected to `https://cdn.plaid.com/link/v2/stable/oauth.html#code=authorization_code_good&state=_SOME_STATE_VALUE` which never loads. Going to the same url in a web browser on my desktop shows the following error in the console;

`Error: oauthRedirectUri is required. See https://plaid.com/docs/#oauth-requirements-for-webview-integrations-in-europe for more information`

I have noticed there's been an update recently that includes oauthNonce so I'll try again when I have some time :)

**Comment by eduardborges** [comment]
I think the version 3.0.0 adds support for it. The README needs to be updated, but if you check the commit of the release you can see that they added the props.

**Comment by maitham** [comment]
How do you reinitialise the Plaid Link component? Right now I have it redirecting to my website which opens up a universal link which takes me back to my app with the oauth_state_id. I need to then reinitialise the plaid component with the oauth_state_id, but how do you go about doing that?

**Comment by eduardborges** [comment]
I would also appreciate some documentation on how to integrate the library with oauth

**Comment by wkiefer** [comment]
> Am I meant to dismiss the existing plaid link and reopen with an oauthstateid?

Yes — for flows that jump to other apps and use deep links you should dismiss the existing plaid link and reopen.

Some documentation links:
https://plaid.com/docs/faq/#what-do-i-need-for-different-oauth-integrations-
https://plaid.com/docs/quickstart/#run-quickstart-oauth
https://plaid.com/docs/#oauth

We don't have RN specific documentation on this yet, sorry!

Closing this as v3.0.0 added support for EU and oauth flows. thanks!

**Comment by maitham** [comment]
What's the recommended way to dismiss the modal? The sdk doesn't expose the method available in RNLinkSDK.m to dismiss the modal.

**Comment by AdamAwan** [comment]
@wkiefer 
Sorry it's taken me so long to get back to this.

Was support added for Android?

There's [no corresponding values in the kotlin file](https://github.com/plaid/react-native-plaid-link-sdk/blob/393b885d94f7d23dce9a0cabdceaf3e50a269bef/android/src/main/java/com/plaid/PlaidModule.kt#L39).  I appreciate I may have missed something but I still can't get it working.

**Comment by wkiefer** [comment]
> What's the recommended way to dismiss the modal? The sdk doesn't expose the method available in RNLinkSDK.m to dismiss the modal.

I've added a dismiss method in https://github.com/plaid/react-native-plaid-link-sdk/commit/91e2581e3feeb1caa6ebd9339202074d515686f5

It will be out in our release next week — thanks!

**Comment by wkiefer** [comment]
v3.1.0 is now released with this method:
https://www.npmjs.com/package/react-native-plaid-link-sdk

**Comment by k11kirky** [comment]
Can somebody please provide an example of this working with deep linking, dismissing the modal and using the stateID

**Comment by maitham** [comment]
I can quickly provide some snippets, let me know if you want a more complete example I can perhaps help more over the weekend. My dismissLink may look a bit different as I forked the repo at the time and haven't updated since. 

Flow is 

1. openPlaid gets called when user clicks Add Account. 
2. Goes through link to eu institution
3. Gets redirected to <app_name>://plaid/<screen_path> oauthstateid attached as route params
4. useEffect waiting on changes to oauthstateid which then gets dismissed before opening a plaid link again with the given oauthstateid 
5. User finishes and onSuccess returns data

In my react navigation config, 
```
const { getInitialState } = useLinking(containerRef, {
    prefixes: ['<app_name>://plaid'],
    config: {
      Callback: { path: 'callback' },
      Modals: {
        screens: {
          'add account':  { path: 'accounts' },
        },
      },
      Root: {
        path: 'root',
        screens: {
          Home: { path: 'home' },
          Profile: { path: 'profile' },
        },
      },
    },
  });
```


I have the following in the component that is deep linked. 
```
 // To catch Plaid redirect from EU Oauth2 institutions
  useEffect(() => {
    if (route.params?.oauth_state_id) {
      const oauth_state_id = route.params.oauth_state_id;
      dismissLink({ onExit: () => onExitPlaid() });
      openPlaid(
        oauth_state_id,
        ['transactions'],
        body => handleCallback(body, 'plaid'),
        onExitPlaid,
        onExitPlaid,
      );
    }
  }, [route.params?.oauth_state_id]);
```

```
import { openLink } from 'react-native-plaid-link-sdk';
export const openPlaid = (oauthStateId, products, onSuccess, onExit, onCancelled) => {
  const props = {
    publicKey: PLAID_PUBLIC_KEY,
    clientName: <CLIENT_NAME>,
    env: PLAID_ENV,
    product: products,
    onSuccess: data => {
      parseData(data).then(data => onSuccess(data));
    },
    onExit: onExit,
    onCancelled: onCancelled,
    language: 'en',
    oauthNonce: <Nonce>,
    countryCodes: ['US', 'GB'],
    oauthRedirectUri: '<app_name>://plaid/accounts',
    oauthStateId: oauthStateId,
  };
  return openLink({ ...props });
};

```

**Comment by k11kirky** [comment]
Thanks a lot maitham - I would love to see a more complete example because in my deep linked component the useEffect doesnt fire, however when I try to deep link through the terminal 
(" xcrun simctl openurl booted "myApp://Accounts?oauth_state_id=1234"")
 it does fire useEffect

**Comment by maitham** [comment]
@k11kirky Can you share some of your code?

**Comment by k11kirky** [comment]
@maitham Here is a slightly simplified example of my app: I've tested this and it still wont work:

Nav.js
`
const Tab = createBottomTabNavigator();

const StackNav = () => {
  const ref = React.useRef();

  const { getInitialState } = useLinking(ref, {
    prefixes: ["myApp://"]
  });

  console.log("here");

  const [isReady, setIsReady] = React.useState(false);
  const [initialState, setInitialState] = React.useState();

  React.useEffect(() => {
    Promise.race([
      getInitialState(),
      new Promise(resolve =>
        setTimeout(resolve, 150)
      )
    ])
      .catch(e => {
        console.error(e);
      })
      .then(state => {
        console.log("state", state);
        if (state !== undefined) {
          setInitialState(state);
        }

        setIsReady(true);
      });
  }, [getInitialState]);

  if (!isReady) {
    return null;
  }
  return (
    <NavigationContainer initialState={initialState} ref={ref}>
      <Tab.Navigator
        initialRouteName="Dashboard"
        screenOptions={({ route }) => ({
          tabBarIcon: ({ focused, color, size }) => {
            let iconName;
            if (route.name === "Dashboard") {
              iconName = "md-home";
            } else if (route.name === "Accounts") {
              iconName = "md-wallet";
            } else if (route.name === "Settings") {
              iconName = "md-cog";
            }
            return; // TODO ICON
          }
        })}
        tabBarOptions={{
          activeTintColor: colors.primary,
          inactiveTintColor: colors.secondary
        }}
      >
        <Tab.Screen name="Dashboard" component={Dashboard} />
        <Tab.Screen name="Accounts" component={Accounts} />
        <Tab.Screen name="Settings" component={Settings} />
      </Tab.Navigator>
    </NavigationContainer>
  );
};

export default StackNav;
`

Accounts.js
`
import React, { useEffect } from "react";
import { View, Text, StyleSheet } from "react-native";
import PlaidLink, { openLink, dismissLink } from "react-native-plaid-link-sdk";
import { connect } from "react-redux";
import { fonts } from "../theme";

const PLAID_PUBLIC_KEY = "MY KEY";
const PLAID_ENV = "sandbox"

const onExitPlaid = e => console.log(e);
const handleCallback = e => console.log(e);

const Accounts = props => {
  useEffect(() => {
    console.log("use fired");
    if (props.route.params?.oauth_state_id) {
      const oauth_state_id = props.route.params.oauth_state_id;
      dismissLink({ onExit: () => onExitPlaid() });
      openPlaid(
        oauth_state_id,
        ["transactions"],
        body => handleCallback(body, "plaid"),
        onExitPlaid,
        onExitPlaid
      );
    }
  }, [props.route.params?.oauth_state_id]);
  return (
    <View style={styles.container}>
      <View style={styles.homeContainer}>
        <Text style={styles.welcome}>Accounts</Text>
        <PlaidLink
          publicKey={PLAID_PUBLIC_KEY}
          clientName="CLIENT NAME"
          env={PLAID_ENV} // 'sandbox' or 'development' or 'production'
          product={["auth", "transactions"]}
          onSuccess={data => {
            console.log("success: ", data);
          }}
          onExit={data => console.log("exit: ", data)}
          onCancelled={result => {
            console.log("Cancelled: ", result);
          }}
          countryCodes={["GB", "US"]}
          oauthRedirectUri={"myApp://Accounts"}
          oauthNonce={"longNonce-Nonce-anasdlkjnkljn"}
        >
          <Text>Add Account</Text>
        </PlaidLink>
      </View>
    </View>
  );
};

export const openPlaid = (
  oauthStateId,
  products,
  onSuccess,
  onExit,
  onCancelled
) => {
  const props = {
    publicKey: PLAID_PUBLIC_KEY,
    clientName: "app",
    env: PLAID_ENV,
    product: products,
    onSuccess: data => {
      parseData(data).then(data => onSuccess(data));
    },
    onExit: onExit,
    onCancelled: onCancelled,
    language: "en",
    oauthNonce: "longNonce-Nonce-anasdlkjnkljn",
    countryCodes: ["GB", "US"],
    oauthRedirectUri: "myApp://Accounts",
    oauthStateId: oauthStateId
  };
  return openLink({ ...props });
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    flex: 1
  },
  homeContainer: {
    alignItems: "center"
  },
  welcome: {
    fontFamily: fonts.light,
    color: "rgba(0, 0, 0, .85)",
    marginBottom: 26,
    fontSize: 22,
    textAlign: "center"
  },
  registration: {
    fontFamily: fonts.base,
    color: "rgba(0, 0, 0, .5)",
    marginTop: 20,
    fontSize: 16,
    paddingHorizontal: 20,
    textAlign: "center"
  }
});

const mapStateToProps = state => ({
  auth: state.auth
});

const mapDispatchToProps = {};

export default connect(mapStateToProps, mapDispatchToProps)(Accounts);
`

This set up doesnt seem to refire useEffect and {"error": {"message": "The provided credentials were not correct. Please try again."}

**Comment by maitham** [comment]
Is this in dev or sandbox? Also I think you need to set the same oauthnonce for when you reopen the plaid link.

**Comment by wkiefer** [comment]
@maitham do you have a `requestId` from one of your failed sandbox requests? We'd like to take a look at logs. (it's returned with the error metadata)

Same question for you @k11kirky — do you have `requestId` we could look at from a sandbox request? Are things working for you in dev mode?

**Comment by k11kirky** [comment]
I am doing it in sandbox - here is the request id "request_id": "e5J3xm0aAuX7b9y"

**Comment by k11kirky** [comment]
@maitham @wkiefer
I have tried in development as well:

{"error": {"message": "an unexpected error occurred"}, "institution": {"institution_id": "ins_63", "name": "Revolut - Open Banking"}, "link_session_id": "cfd163eb-3c52-45f2-a5e6-8efa38e6de99", "request_id": "O580yxBIynOA7uI", "status": "requires_credentials"}

However, When I test my deeplink in the browser it triggers my useEffects
