### ISSUE TITLE
paymentToken is not defined

### ISSUE THREAD

**Issue by vafada** [plaid/react-native-plaid-link-sdk#54]
this should be paymentTokenInput

https://github.com/plaid/react-native-plaid-link-sdk/blob/fa70ef993c7d4c9e92e27db4d57083025dada599/ios/RNLinksdk.m#L200

**Comment by eltoob** [comment]
+1

**Comment by maitham** [comment]
same any solutions?

**Comment by wkiefer** [comment]
Apologies — this was a merge error. Shouldn't happen again — I'll push a 3.0.1 shortly
