### ISSUE TITLE
Inconsistent API for Link update

### ISSUE THREAD

**Issue by vafada** [plaid/react-native-plaid-link-sdk#55]
When opening Link in update mode:

in iOS, the property is `token`:

https://github.com/plaid/react-native-plaid-link-sdk/blob/fa70ef993c7d4c9e92e27db4d57083025dada599/ios/RNLinksdk.m#L14

in Android, the property is `publicToken`:

https://github.com/plaid/react-native-plaid-link-sdk/blob/fa70ef993c7d4c9e92e27db4d57083025dada599/android/src/main/java/com/plaid/PlaidModule.kt#L47

Please make property consistent,  i suggest using `publicToken` since its clearer and make sure not to make any breaking changes (maybe keep `token` for iOS to not break code which uses `token` already)

**Comment by zsweigart** [comment]
@vafada thanks for the input, we will look into this for the next release

**Comment by zsweigart** [comment]
Hi @vafada this has been updated with version 4.0.0
