### ISSUE TITLE
Android signed SDK triggers onExit with oAuth institutions

### ISSUE THREAD

**Issue by gastondisacco** [plaid/react-native-plaid-link-sdk#552]
# The problem

We have integrated our app with react-native-plaid-link-sdk and it has worked great so far, for quiet a good time.

Last week we started getting reports from users unable to complete the flow using Plaid Link SDK on Android.
We have been troubleshooting this since then and unable to get a solution.

Our findings: working locally with development builds it works well, working with an SDK (not signed) it works well.
But it fails when we try the flow with a Google signed APK. It triggers the onExit prop on the PlaidLink component and no data is present on the error (LinkExit) data.
Appreciate any guidance or thoughts on this. We haven't changed our code about this implementation.

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | 10.3.0                                                                        |
| ReactNative Version               | e.g. 0.71.8                                                                 |
| Occurs on Android                  | yes.                                                                           |
| Android OS Version                 | 11.RP1A.200720.011                                                |
| Android Devices/Emulators    | Redmi Note 9                                                           |
| Occurs on iOS                          | no                                                                              |

**Comment by dtroupe-plaid** [comment]
Hi @gastondisacco thanks for reporting this issue. 

Since this only impacts OAuth traffic I am wondering if this could be related to [this issue](https://github.com/facebook/react-native/issues/30277) mentioned in a [contributing docs](https://github.com/plaid/react-native-plaid-link-sdk/blob/master/CONTRIBUTING.md?plain=1#L23)

**Comment by gastondisacco** [comment]
Thank you @dtroupe-plaid . I don't think it's the same issue. We are not killing the app in background. Also, please note that it works perfectly fine when testing with a not signed APK. It only fails when using a Play Store build / signed APK.

Thanks

**Comment by gastondisacco** [comment]
@dtroupe-plaid thanks for asking! Unfortunately we couldn't fix it yet. I was able to validate that the same flow on an empty app works well. My theory is that there is some config blocking the incoming data from the redirect from being captured but so far no luck on all of the tests we did. Any thoughts? Thanks so much.

**Comment by zohaibahmed-22** [comment]
any update on this issue ?

**Comment by dtroupe-plaid** [comment]
Hi @zohaibahmed-22,

We haven't heard of this issue from any of our Android customers. Additionally, this doesn't appear to be a widespread issue with our React Native SDK. Happy to help debug further but we have very limited information to go on and no minimum reproducible example. 

If you are able to provide more information that might help resolve this issue. 

Thanks 😄

**Comment by Mndiong15** [comment]
Hi @dtroupe-plaid

I am also having this issue. I am using the sandbox environment to test the OAuth flow with Platypus OAuth Bank and the entire app crashes. This is happening for me on an Android emulator. The other banks that don't require a redirect to the institution's page are working as expected.

Thank you

**Comment by melissaosullivan** [comment]
Hi @Mndiong15,

I'm also not able to reproduce this bug. Could you please provide a an example app where this occurs? 

Thanks,
Melissa
