### ISSUE TITLE
Default iOS to fullscreen mode

### ISSUE THREAD

**Issue by vafada** [plaid/react-native-plaid-link-sdk#57]
Plaid Link in iOS opens in popover mode

can this be changed to open in fullscreen mode?

https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/uimodalpresentationfullscreen?language=objc

```
//self.linkViewController.modalPresentationStyle = UIModalPresentationStyle.UIModalPresentationFullScreen;
// UIModalPresentationFullScreen = 0. I don't know what to import to get UIModalPresentationStyle enum
self.linkViewController.modalPresentationStyle = 0;
```

**Comment by kinigitbyday** [comment]
Somewhat related, but it also doesn't currently respect the safe area, so parts get drawn underneath the home indicator
![Simulator Screen Shot - iPhone 11 - 2020-02-21 at 12 59 54](https://user-images.githubusercontent.com/2687212/75071516-61310f00-54aa-11ea-9caf-712cc90ecfcb.png)

**Comment by wkiefer** [comment]
> Somewhat related, but it also doesn't currently respect the safe area, so parts get drawn underneath the home indicator

We have an internal ticket for that and hopefully the fix will be out in the March release. thanks!

**Comment by wkiefer** [comment]
re: this bug. Yes, we can make the default for RN full screen for now.

We'll also provide a property to customize to a different value. I've filed an internal ticket to add that feature.
