### ISSUE TITLE
verificationStatus type on android is wrong

### ISSUE THREAD

**Issue by pabloearg** [plaid/react-native-plaid-link-sdk#589]
# The problem

In the success callback the response doesn't match the LinkAccount interface, you are changing the  verificationStatus to verification-status

# Environment

|Type                                                  |                     Version                                                             |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | e.g. 10.4.0                                                                 |
| ReactNative Version               | e.g. 0.71.0                                                                 |
| Occurs on Android                  | e.g. yes

# Steps to Reproduce

see types file:

```
export interface LinkAccount {
    id: string;
    name?: string;
    mask?: string;
    type: LinkAccountType;
    subtype: LinkAccountSubtype;
    verificationStatus?: LinkAccountVerificationStatus;
}
```

this is the android kotlin file where you are changing the attribute name from verificationStatus to verification-status

<img width="704" alt="image" src="https://github.com/plaid/react-native-plaid-link-sdk/assets/29818262/f0c641a8-5248-41de-8fa4-c5a6704056a8">

# Expected Result
the attribute should be verificationStatus

**Comment by dtroupe-plaid** [comment]
@pabloearg thanks for reporting. To avoid a breaking change we will add `"verificationStatus" as another key. I will put this in the next release. Also feel free to submit a PR.

**Comment by dtroupe-plaid** [comment]
Closing because [10.7.0](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v10.7.0) resolves this.
