### ISSUE TITLE
PlaidLink is closed right away after the loading circle appears in Expo

### ISSUE THREAD

**Issue by ChanukaSandeepa** [plaid/react-native-plaid-link-sdk#621]
# The problem

I'm trying to open link using React Native Expo EAS and I did the native config for Expo. Now whenever I try to open link_token using PlaidLink, the popup/page is closed right away after the loading circle appears. Still I'm using SandBox version and no idea about the ongoing problem.

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | e.g. 11.2.0                                                                |
| ReactNative Version               | e.g. 0.71.8                                                                 |
| Occurs on Android                  | e.g. yes                                                                     |
| Android OS Version                 | e.g. 11.0.0 (30)                                                         |
| Android Devices/Emulators    | e.g. Redmi Note 8 Pro                                               |
| Occurs on iOS                          | e.g. no                                                                     |
| iOS Version                               | e.g. 16                                                                       |
| iOS Devices/Emulators            | e.g. iPhone 14 Pro                                                    |
| Link Session ID                         | e.g. c23ac879-ac1a-44c2-8c9c-6043ca9b0209(Not sure about this) |

# Steps to Reproduce

LinkToken creation:
```
{
   "user":{
      "client_user_id":"OMITTED",
      "legal_name":"OMITTED"
   },
   "client_name":"My application",
   "products":[
      "identity"
   ],
   "country_codes":[
      "US"
   ],
   "language":"en",
required_if_supported_products : ['liabilities'],
   "android_package_name":"com.mycompany.myapp"
}
```
Opening link
```
<PlaidLink
                tokenConfig={{
                        token: "link-sandbox-c23ac879-ac1a-44c2-8c9c-6043ca9b0209",
                        logLevel: LinkLogLevel.ERROR,
                        noLoadingState: false
                }}
                onSuccess={(success) => { console.log(success, 'success') }}
                onExit={(linkExit) => { console.log(linkExit, 'exits') }}
          >
              <Text>Add Account</Text>
          </PlaidLink>
```

# Expected Result
The list of bank to be proceeded

PlaidLink closes with this result in onExit event : {"metadata": {}}

**Comment by dhruvdatharva** [comment]
This is happening with CLI also!

**Comment by dhruvdatharva** [comment]
This is happening with CLI also!
