### ISSUE TITLE
Expose DismissLinkViewController Method

### ISSUE THREAD

**Issue by maitham** [plaid/react-native-plaid-link-sdk#63]
EU oauth flow requires us to dismiss the Link view controller, and reinitialise with the oauthStateId. I could be missing something, but if you're using react navigation there doesn't seem to be a way to dismiss the plaid link view controller programatically.

**Comment by wkiefer** [comment]
This is now released in v3.1.0
https://www.npmjs.com/package/react-native-plaid-link-sdk
