### ISSUE TITLE
Redirect Issue For Ireland Bank's

### ISSUE THREAD

**Issue by nihalgadhavi9** [plaid/react-native-plaid-link-sdk#64]
I'm trying to implement plaid for Ireland bank which is redirecting to browser but after successfully providing grant permission it's not redirecting back in-app [sandbox environment]

**Comment by zsweigart** [comment]
Hi @nihalgadhavi9 can you provide information on which version of the SDK you are using and which OS you are running this on?

**Comment by zsweigart** [comment]
This issue will be fixed in the next release.  
Android PR -> https://github.com/plaid/react-native-plaid-link-sdk/pull/73
@wkiefer is working on the iOS one

**Comment by nihalgadhavi9** [comment]
thank you @zsweigart will try after few days
