### ISSUE TITLE
"PLKEmbeddedView" Component Initialization Error

### ISSUE THREAD

**Issue by alkeshraj1** [plaid/react-native-plaid-link-sdk#648]
Encountering the error "ERROR Invariant Violation: requireNativeComponent: 'PLKEmbeddedView' was not found in the UIManager" during application initialization. Despite troubleshooting dependencies and configurations, the component fails to be recognized. To resolve, ensure correct linkage and registration of the component within the UIManager, verify import statements, and check dependencies. Further assistance from project maintainers or community forums may be necessary for resolution.

(https://github.com/plaid/react-native-plaid-link-sdk/assets/105789280/20a98bbc-c68c-4992-a71a-1f5546b47833)

**Comment by dtroupe-plaid** [comment]
Hi @alkeshraj1, 

Please fill out the template provided when creating an issue. Currently there is not enough information to effectively debug your issue. 

You need to provide the following information:

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | e.g. 10.3.0                                                                 |
| ReactNative Version               | e.g. 0.67.0                                                                 |
| Occurs on Android                  | e.g. yes                                                                     |
| Android OS Version                 | e.g. 11.0.0 (30)                                                         |
| Android Devices/Emulators    | e.g. Pixel 7a physical                                                |
| Occurs on iOS                          | e.g. yes                                                                     |
| iOS Version                               | e.g. 16                                                                       |
| iOS Devices/Emulators            | e.g. iPhone 14 Pro                                                    |
| Link Session ID                         | e.g. 0de00328-44f8-4c2e-9eaf-726b2f70169c |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

# Logs
Any relevant logs from Android Logcat or the iOS console including stacktraces.

# Code To Reproduce Issue 
With sample code it's easier to reproduce the bug and it's much faster to fix it. 
Don't forget to omit any keys or personally identifiable information.
Please provide one of the following:

1. (Best) A link to a minimal demo app showing the faulty behavior.
1. (Better) A concise code sample which can be dropped into fresh application
1. A snippet of code for your configuration for opening Link


Also please note I tried to debug your issue by testing embedded Link in the example app in this repo on the latest SDK and embedded Link is working on both iOS and Android (see screenshots below).

![Simulator Screenshot - iPhone 14 - 2024-03-28 at 07 23 12](https://github.com/plaid/react-native-plaid-link-sdk/assets/122908338/bb6ce798-ddaf-4959-bdcb-2a58df3eb080)
![Screenshot_1711636205](https://github.com/plaid/react-native-plaid-link-sdk/assets/122908338/d9492fac-e582-4731-a457-a3edc56116c3)


Please provide the necessary information requested above so we can help debug your issue 😄
