### ISSUE TITLE
work-runtime-ktx-2.7.1-runtime causing build error with latest Datadog sdk on android

### ISSUE THREAD

**Issue by jesse-one-app** [plaid/react-native-plaid-link-sdk#660]
**Is your feature request related to a problem? Please describe.**
The plaid android is using an old version of the android work runtime which has a class collision with other dependencies that have upgraded to the 2.8+ version of android work.

**Describe the solution you'd like**
Would appreciate if plaid makes the upgrades internally to the work sdk version they use and adopt the non ktx version

**Describe alternatives you've considered**
I dont think there is any alternative. I am blocked from upgrading datadog until Plaid makes these changes

**Comment by AlexLFundbox** [comment]
Any updates in this one?

**Comment by melissaosullivan** [comment]
Hi @jesse-one-app, we can make an upgrade to this library. Upgrading to `androidx.work:work-runtime-ktx:2.9.0` would resolve this issue, right?

**Comment by jesse-one-app** [comment]
I believe it would yes

I was actually able to work around this by overriding the version used in my own gradle file but I dont know if there are any adverse side effects from doing that

**Comment by melissaosullivan** [comment]
Great! Thanks, we will put this in the next release.

**Comment by AlexLFundbox** [comment]
@jesse-one-app 
Is it possible also to share your work around ?

**Comment by jesse-one-app** [comment]
@AlexLFundbox sure

i added this line to my app/build.gradle to force the work runtime version 

implementation "androidx.work:work-runtime-ktx:2.8.1"

**Comment by AlexLFundbox** [comment]
@jesse-one-app 
I added it to my "app/build.gradle"

but now, I'm receiving this error

`> Task :datadog_mobile-react-native:runKtlintCheckOverMainSourceSet FAILED

> Task :app:minifyReleaseWithR8
WARNING: R8: Class com.facebook.imagepipeline.image.CloseableAnimatedImage extends com.facebook.imagepipeline.image.CloseableImage which is an interface

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':datadog_mobile-react-native:runKtlintCheckOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > KtLint failed to parse file: /Users/alex.lvovsky/fundbox/mobileNative/node_modules/@datadog/mobile-react-native/android/src/oldarch/kotlin/com/datadog/reactnative/DdLogs.kt`

Any suggestions?

**Comment by jesse-one-app** [comment]
I'm not sure sorry, didn't run into this with my setup

**Comment by dtroupe-plaid** [comment]
[11.12.0](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v11.12.0) resolves this.
