### ISSUE TITLE
Plaid link not loading on Android 9 and below

### ISSUE THREAD

**Issue by jwoodmansey** [plaid/react-native-plaid-link-sdk#663]
# The problem
Hi, we have noticed that the plaid link SDK seems to be no longer working on Android <= 9. I notice the docs say Android 5 and above is still supported so believe this is a bug. 

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | 11.8.2                                                                 |
| ReactNative Version               | 0.71.15                                                                 |
| Occurs on Android                  | yes                                                                     |
| Android OS Version                 | 9.0 (28)                                                         |
| Android Devices/Emulators    | Pixel 2 API 28 (Emulator)                                                |
| Occurs on iOS                          | no                                                                     |
| Link Session ID                         |  26e5fd66-bbd5-4088-ba25-686bcead7b4a |

# Steps to Reproduce

1. Call create/open flow
2. Screen gets stuck on loading the plaid activity.

# Expected Result
Plaid activity to open correctly

# Screenshots
![Screenshot_20240515_175956](https://github.com/plaid/react-native-plaid-link-sdk/assets/3459309/aa3f4aaf-9cd5-44b1-b387-12317a97e346)

# Logs

I see this error in the logs only on Android 9 and below, could be related?
`2024-05-15 17:48:07.943  9044-9044  chromium               ----                         I  [INFO:CONSOLE(2)] "Uncaught ReferenceError: globalThis is not defined", source: https://secure.plaid.com/link/2.0.1929/vendors~flink.js (2)`

**Comment by melissaosullivan** [comment]
Hi @jwoodmansey, this issue is limited to Android 9 emulators. It would not occur on a real Android 9 device as a physical device would have an upgraded Android System WebView package. Apologies for the inconvenience that this causes in automated testing, but we do not intend to fix this as the benefit of using newer web libraries is greater than the cost of not supporting Android 9 emulators for us. Thanks for reporting!

**Comment by jwoodmansey** [comment]
> Hi @jwoodmansey, this issue is limited to Android 9 emulators. It would not occur on a real Android 9 device as a physical device would have an upgraded Android System WebView package. Apologies for the inconvenience that this causes in automated testing, but we do not intend to fix this as the benefit of using newer web libraries is greater than the cost of not supporting Android 9 emulators for us. Thanks for reporting!

Ah okay. That makes sense, thanks for clarifying!
