### ISSUE TITLE
declaration of 'RCTEventEmitter' must be imported from module 'React.RCTEventEmitter' before it is required

### ISSUE THREAD

**Issue by beqramo** [plaid/react-native-plaid-link-sdk#675]
# The problem

I found almost similar issue already but I don't know exactly the solution from there:
https://github.com/plaid/react-native-plaid-link-sdk/issues/436

screenshot:
<img width="1387" alt="image" src="https://github.com/plaid/react-native-plaid-link-sdk/assets/40486471/a5c3e4c7-50e6-44a7-995f-eb0b330026e9">

error
```log
❌  /Users/builder/clone/ios/Pods/Headers/Private/react-native-plaid-link-sdk/react_native_plaid_link_sdk/RNLinksdk.h:9:24: declaration of 'RCTEventEmitter' must be imported from module 'React.RCTEventEmitter' before it is required
```

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | 11.10.2                                                              |
| ReactNative Version               | 0.71.14                                                                 |
| Xcode               |15.3                                             |
| Pod               | 1.14.2                                                              |
| Occurs on iOS                          | yes                                                                     |

# Steps to Reproduce
install and try to run archive on ios for the release, it will throw this error

**Comment by dtroupe-plaid** [comment]
Hi @beqramo,

I just tested archiving for iOS in our example app and I did not receive this error. 

Additionally, the linked issue is related to Expo which is not supported. Are you using a detached Expo setup or Expo at all?

**Comment by beqramo** [comment]
I'm not using expo. 
you tried with the above versions?

thanks

**Comment by dtroupe-plaid** [comment]
I updated the example app to `11.11.0` the import in the file has not changed so I don't believe the minor version difference is  relevant. You could try changing it to `#import <React/RCTEventEmitter.h>` to see if that resolves the issue, but I didn't need to do that to archive.

**Comment by beqramo** [comment]
Okay I will try it again

**Comment by beqramo** [comment]
Hi, 
I tried many things, but without any success, it is always throws a similar error:
```
error: could not build Objective-C module 'react_native_plaid_link_sdk'
```

Are you sure you have installed this package on react native 0.71.18?

**Comment by beqramo** [comment]
@dtroupe-plaid ^

**Comment by dtroupe-plaid** [comment]
Hi @beqramo 

I created a blank RN project using the following:

1. `npx @react-native-community/cli@latest init Issue675 --version 0.71.18`
2. `npm install --save react-native-plaid-link-sdk`
3. Change min supported iOS version to 14.0 (required for V11)
4. Add Plaid views from example app.

The project builds and archives without issue on Xcode 15.3. I've attached a copy here, you'll need to run `npm install` and `pod install` in the `ios` directory before testing. 

Please let me know what you experience in your testing 🙏 

[Issue675.zip](https://github.com/user-attachments/files/16383509/Issue675.zip)

**Comment by dtroupe-plaid** [comment]
@beqramo another tip that might be helpful is to point out that you can modify the file in question in Xcode:

<img width="1176" alt="Screenshot 2024-07-25 at 13 39 01" src="https://github.com/user-attachments/assets/d53c0d31-fca0-4190-849e-46b81fce552d">

Perhaps changing something with the imports might help? Let me know if you find anything.

**Comment by dtroupe-plaid** [comment]
@beqramo Can you provide an update? If not I am going to close the issue 🙏

**Comment by beqramo** [comment]
Hi, sorry.

I will provide update for tomorrow. Thanks

**Comment by beqramo** [comment]
I have just updated the 10th version to its up-to-date version which I think has the fix for our issue in prod.
For now we will stick to that version. we don't have enough resources to spend time on this issue again. 

Just to know when you will support the 10th version of the SDK?


thanks

**Comment by dtroupe-plaid** [comment]
>I have just updated the 10th version to its up-to-date version

Sorry, it's unclear to me what version you're now using can you be specific so I can see if there are relevant changes with regards to this issue?

>Just to know when you will support the 10th version of the SDK?

Sorry, again I am not sure what version you're talking about? V10.x.x?

**Comment by beqramo** [comment]
Oh, my bad, I just read my message again.

We are using the 10th version of the SDK in general. Now, I have updated it to the latest version: [10.13.2](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v10.13.2). From the release notes, I see that you fixed the OAuth bug, which I believe we were also experiencing in production.

Since we don't have enough resources to spend more time on this issue for now, I think this update will be sufficient for us.

Another question was about: Till when are you going to support the 10th version of the SDK?

Thanks and sorry for misunderstanding

**Comment by dtroupe-plaid** [comment]
V10.x.x will likely no longer receive updates once V12 is officially released (EOY target) this doesn't mean you can't keep using it, but it means it will no longer receive updates. 

Looking at the diff between 10.13.2 and 11.11.2 the changes to `RNLinksdk.h` do include this import but it looks like `#import <React/RCTEventEmitter.h>` was changed to `#import "RCTEventEmitter.h"` I suggested making this change in a previous comment and I am assuming it didn't work?

However, that appears to be the only explanation here. 

<img width="481" alt="Screenshot 2024-08-07 at 10 35 54" src="https://github.com/user-attachments/assets/98362337-e92d-4ff6-b7ec-75e6e62b6a52">

I am going to close this issue. Feel free to post if anything changes.

**Comment by beqramo** [comment]
Hi @dtroupe-plaid,

Inserting the old code into RNLinksdk.h resolved the issue. Thank you for your help!

I’m not entirely sure what caused the problem, but I think it would be worth investigating on your end.

Just to confirm: this solution will work with the  new v11 right, correct? I’m not using the new architecture.

Thanks again!

**Comment by envisean** [comment]
@beqramo @dtroupe-plaid I was able to get an iOS binary built with your suggestion, but then when I actually try to open up a plaid link, it doesn't show up. Has anyone gotten further or understood why? I'm wondering if I have something off in my Podfile that might be screwing this up at this point
