### ISSUE TITLE
Visual issues after selecting a broker

### ISSUE THREAD

**Issue by carlaTatiana** [plaid/react-native-plaid-link-sdk#679]
# Visual issues after selecting a broker

After selecting the broker, the Plaid modal hides and another modal corresponding to the broker opens. On iOS, the following happens:t he new modal has a transparent background.

It happens in iOS devices and simulators.

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          |      11.10.3                                                                 |
| ReactNative Version               |       0.74.1                                                                 |
| Occurs on Android                  | NO                                                                           |
| Android OS Version                 | -----                                                                        |
| Android Devices/Emulators    | -----                                                                        |
| Occurs on iOS                          | YES.                                                                        |
| iOS Version                               | 17.2.                                                                        |
| iOS Devices/Emulators            |.    iPhone 15 Pro                                                    |
| Link Session ID                         | |

# Expected Result
The new modal with the same background color as the plaid modal.

# Screenshots

Selecting Charles Schwab:

https://github.com/plaid/react-native-plaid-link-sdk/assets/72270207/6d59fee3-5721-4d13-a426-d1a5aa10c60e

Selecting Robinhood:

https://github.com/plaid/react-native-plaid-link-sdk/assets/72270207/08281b2c-c720-4281-b2af-c917fcb44151

# Code To Reproduce Issue 

```
  useEffect(() => {
    if (linkToken) {
      console.log("link token")
      const tokenConfig = {
        token: linkToken,
        noLoadingState: false,
      };
      create(tokenConfig);
    }
  }, [linkToken]);
  
  
   const openLink = () => {
    open({
        onSuccess: (success: LinkSuccess) => {
          console.log('On success ', success);
          
          exchangeLinkToken(success) 

        },
        onExit: (exit: LinkExit) => {
          console.log("On exit", exit)
        
        },
      iOSPresentationStyle: LinkIOSPresentationStyle.MODAL,
      logLevel: LinkLogLevel.ERROR,
    });
  }
  
  
  
  <Button title={"Press"} onPress={openLink}/>
  
```

**Comment by dtroupe-plaid** [comment]
@carlaTatiana thanks for reporting. This issue should have been resolved remotely. Please let me know if you're still seeing this bug.

**Comment by carlaTatiana** [comment]
it's working! Thank you!!
