### ISSUE TITLE
Open link with predefined institution

### ISSUE THREAD

**Issue by AlexLFundbox** [plaid/react-native-plaid-link-sdk#691]
Hey!
In our app, we call backend service to receive "generated_token".
What I want, that I show to the user only specific number of institutions (supported by Plaid) and when user clicks on it, Plaid modal will be opened with this specific institution.
Is there a way to do it, without opening each time link with specific institution. But to have generic token, and institution will be sent in `openLink` or something?

We have such behavior in web, when we call `open(INSTITUTION_ID)`

**Comment by phoenixy1** [comment]
Hi, configuring this behavior is not supported client-side. If you are using a configuration where opening Link with a predefined institution is supported (such as Payment Initiation), you can set the institution in the link token using https://plaid.com/docs/api/tokens/#link-token-create-request-institution-id, but not when making the open request on the client.

Some similar functionality you might be interested in:
- Embedded Institution Search https://plaid.com/docs/link/embedded-institution-search/
- The institution select shortcut: https://plaid.com/docs/link/customization/#institution-select-shortcut
- Custom institutions lists: https://plaid.com/docs/link/customization/#financial-institutions

**Comment by dtroupe-plaid** [comment]
>specific number of institutions

If this is a small number you could just generate a token specific to each institution. 

I am going to close this since it's more of a product request than an issue. Please reach out to support if you need additional assistance.
