### ISSUE TITLE
Plaid Sandbox working for chase bank in IOS react Native not for other banks

### ISSUE THREAD

**Issue by thamizhbharathi** [plaid/react-native-plaid-link-sdk#712]
Plaid sandbox is working fine only for chase bank in IOS,(opens browser for authentication and then redirecting to app) but not for other banks
Am I doing anything wrong, Can someone  please help me to sort this out?(not openting browser , credentials input form showing inside app)

![chase bank](https://github.com/user-attachments/assets/2cdeb7cd-7a13-4ae3-a23e-65244e57ba62)
![other bank](https://github.com/user-attachments/assets/4daff44c-1531-4eda-b3d8-1f541dc304e4)

Note: I am using react native , and in android other banks like bank of america, citi bank, capital one all are working fine

**Comment by dtroupe-plaid** [comment]
Please provide all of the information that was request when opening an issue. There is not enough information here to debug. 

I recommend the following:

- Provide all the missing information what was requested when you opened this issue.

```
# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | e.g. 10.3.0                                                                 |
| ReactNative Version               | e.g. 0.67.0                                                                 |
| Occurs on Android                  | e.g. yes                                                                     |
| Android OS Version                 | e.g. 11.0.0 (30)                                                         |
| Android Devices/Emulators    | e.g. Pixel 7a physical                                                |
| Occurs on iOS                          | e.g. yes                                                                     |
| iOS Version                               | e.g. 16                                                                       |
| iOS Devices/Emulators            | e.g. iPhone 14 Pro                                                    |
| Link Session ID                         | e.g. 0de00328-44f8-4c2e-9eaf-726b2f70169c |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)
```

- Test in production to see if this issue also occurs there.

**Comment by thamizhbharathi** [comment]
# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | ^11.12.1                                                               |
| ReactNative Version               | 0.72.4                                                               |
| Occurs on Android                  | No                                                                    |
| Android OS Version                 | 12.00 (min)                                                         |
| Android Devices/Emulators    | Poco X3 pro Physical                                               |
| Occurs on iOS                          | yes                                                                     |
| iOS Version                               | 17.6.1                                                                       |
| iOS Devices/Emulators            | iPhone 14                                                    |


Plaid sandbox is working fine only for chase bank in IOS,(opens browser for authentication and then redirecting to app) but not for other banks 

that username and password details page should open on browser but it is opening in broswer only for chase bank in IOS not working for other banks.

But In android it is working fine.

Note : We still do not have the production roll out done. We need to validate in the sandbox before getting the production done. Any recommendation how to test it with this constraint

**Comment by dtroupe-plaid** [comment]
>Plaid sandbox is working fine only for chase bank in IOS,(opens browser for authentication and then redirecting to app) but not for other banks

Not all banks open in the browser only ones that support [OAuth](https://plaid.com/docs/link/oauth/).

>that username and password details page should open on browser

that is not correct for all banks.

I am going to close this issue because there doesn't appear to be a specific SDK issue here. Feel free to reach out to support for further clarifications.
