### ISSUE TITLE
Plaid Sandbox only works with Chase bank on iOS. 

### ISSUE THREAD

**Issue by kev0960** [plaid/react-native-plaid-link-sdk#714]
# The problem

In iOS, when linking a bank through the Plaid sandbox environment, only linking to the Chase bank works. 

When linking other institutions, the redirection is not happening properly. So after `OPEN_OAUTH` event and selecting the bank account, neither of onSuccess or onExit gets called.

This does not happen with the iOS prod env or on Android.

One thing I found out is that when linking Chase bank, the redirection to the provided redirect_url does not happen. When the linking is done, instead of the webview redirecting to the provided redirect_url, it just completes the flow (I added a log on GET calls on the redirect_url). On the other hand, when other institution is chosen, it always goes to the redirect_url and comes back to the app.

Note that I properly set up the universal link. Navigating to the redirect_url will always ask to open the app.

I believe something is wrong with the redirecting back to the app logic :(

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | 11.13.0                                                                 |
| ReactNative Version               | 0.74.4                                                                 |
| Occurs on Android                  | No                                                                     |
| Occurs on iOS                          | Yes                                                                     |
| iOS Version                               | 17, 18                                                                      |
| iOS Devices/Emulators            | All iOS devices.               |
| Link Session ID                         | 526c8af0-80b7-4b3f-be0e-99a00290e394 |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (excluding your keys
and personally identifiable information)

For example:
```
{
   "client_id":"OMITTED",
   "secret":"OMITTED",
   "user":{
      "client_user_id":"OMITTED",
      "legal_name":"OMITTED"
   },
   "client_name":"My application",
   "products":[
      "auth"
   ],
   "country_codes":[
      "US"
   ],
    redirect_uri: "http://localhost/api/finance/plaid/token_redirect"
   "language":"en",
}
```

# Expected Result

After the user signs into the bank and selects the accounts, either onSuccess or onExit callback should be called.

# Screenshots
It just stucks on that page.

https://github.com/user-attachments/assets/d2a6218c-abf3-4d74-955e-a01aa85ce4d4

# Logs
The last event emitted by the PlaidEmitter:

```
{"eventName": "OPEN_OAUTH", "metadata": {"accountNumberMask": "", "errorCode": "", "errorMessage": "", "errorType": "", "exitStatus": "", "institutionId": "ins_127990", "institutionName": "U.S. Bank", "institutionSearchQuery": "", "isUpdateMode": "", "linkSessionId": "be2b65b7-60f4-404b-9b1e-02776643bf23", "matchReason": "", "metadata_json": "{\"account_number_mask\":\"\",\"error_code\":\"\",\"error_message\":\"\",\"error_type\":\"\",\"exit_status\":\"\",\"institution_id\":\"ins_127990\",\"institution_name\":\"U.S. Bank\",\"institution_search_query\":\"\",\"is_update_mode\":\"\",\"link_session_id\":\"be2b65b7-60f4-404b-9b1e-02776643bf23\",\"match_reason\":\"\",\"mfa_type\":\"\",\"request_id\":\"nMIQPM3DXyCFb4y\",\"routing_number\":\"\",\"timestamp\":\"\",\"view_name\":\"\"}", "mfaType": "", "requestId": "nMIQPM3DXyCFb4y", "routingNumber": "", "selection": "", "timestamp": "2024-10-01T21:23:54.000Z", "viewName": ""}}
```

**Comment by phoenixy1** [comment]
@kev0960 Can you reproduce this issue on a physical iOS device? Under the troubleshooting tips for "OAuth redirects not working" at https://plaid.com/docs/link/troubleshooting/#oauth-redirects-not-working (which I recommend going through) there is a note indicating that redirects don't always work correctly on the iOS simulator.

**Comment by kev0960** [comment]
@phoenixy1 It does not work on the phone neither. The symptom is similar. After the log in, it successfully comes back to the app, but it gets stuck in the following page.

![IMG_0036 2](https://github.com/user-attachments/assets/0d6486b1-73f9-4724-b80f-e04dc0a994e5)

After I hit "Continue", it stuck at the "Redirecting..." loop forever.

![IMG_0037](https://github.com/user-attachments/assets/04319d90-b93a-4661-9913-25de6abdb05c)

**Comment by kev0960** [comment]
@phoenixy1 Yes I am sure about that.

**Comment by phoenixy1** [comment]
@kev0960 I got a chance to talk to the mobile team and they confirmed that this is a bug on our end; we should have a fix out soon.

**Comment by phoenixy1** [comment]
@kev0960 thanks for your patience on this! Just to close the loop: This was due to an inconsistency around handling of non-https redirect URIs on iOS between Sandbox and Production. The backstory behind why is the inconsistency existed is quite long and complicated, but anyway the tl;dr is that we fixed it and I believe this should be working for you now. Let me know if you're still having issues.

**Comment by kev0960** [comment]
@phoenixy1 Hi Alex, we changed our logic to use the hosted link so we cannot verify whether the fix is applied or not, but thanks for looking into this regardless!
