### ISSUE TITLE
Android - Always Opening external web-browser when selecting any bank

### ISSUE THREAD

**Issue by dhairyasenjaliya** [plaid/react-native-plaid-link-sdk#731]
# The problem

- iOS works well once it calls the `open()` method it initializes the plaid modal and selects any bank that can operate without opening in any external browser 

- Android just opens the plaid modal but once we select any banks it opens in an external browser (not sure what we are missing)

**Comment by Simon-Fabric** [comment]
@dhairyasenjaliya How did you resolve this?

**Comment by dhairyasenjaliya** [comment]
@Simon-Fabric need to add parameters on api for android
