### ISSUE TITLE
React Native New Architecture, bad header import statement

### ISSUE THREAD

**Issue by gavinnewcomer** [plaid/react-native-plaid-link-sdk#732]
# The problem
I upgraded our application to React Native 0.76.3 and am getting a build error due to a bad import of the react_native_plaid_link_sdk-Swift.h in the conditional block for the new architecture.

# Environment

|                                                  |                                                                                  |
| -----------------------------| ----------------------------------------------- |
| Plaid Link React Native          | e.g. 11.13.2                                                               |
| ReactNative Version               | e.g. 0.76.3                                                                 |
| Occurs on iOS                          | e.g. yes                                                                     |
| iOS Version                               | e.g. 16                                                                       |
| iOS Devices/Emulators            | e.g. iPhone 14 Pro (Simulator) & iPhone 15 Pro                                                 |
| Link Session ID                         | n/a

# Steps to Reproduce
Try and build a react native iOS app running 0.76.3 and 11.13.2 using Xcode and you will get the build error. 

# Screenshots
![Screenshot 2024-12-01 at 4 49 12 PM](https://github.com/user-attachments/assets/302bb44d-b383-44bf-983c-ba85db6b028a)

# Code
Removing the conditional and import around the line in question resolves the issue. 

```#import <React/RCTConversions.h>
#import <folly/dynamic.h>
#import <objc/runtime.h>

#if __has_include(<rnplaidlink/react_native_plaid_link_sdk-Swift.h>)
#import <rnplaidlink/react_native_plaid_link_sdk-Swift.h>
#else
#ifdef USE_FRAMEWORKS
#import <react_native_plaid_link_sdk/react_native_plaid_link_sdk-Swift.h>
#else
#import <react_native_plaid_link_sdk-Swift.h>
#endif
#endif
```

**Comment by jessethouin** [comment]
I also ran into this issue. Downgrading to 11.13.1 solved the problem, but yeah this should be addressed.

**Comment by dtroupe-plaid** [comment]
Hey @gavinnewcomer & @jessethouin just want to confirm you're saying that removing 

```
#ifdef RCT_NEW_ARCH_ENABLED
#import <react_native_plaid_link_sdk/react_native_plaid_link_sdk-Swift.h>
#else
```

from `ios/PLKFabricHelpers.h` resolves the issue?

The reason I am asking this is because [this issue](https://github.com/plaid/react-native-plaid-link-sdk/issues/713) was reporting that without that line the SDK didn't compile on `0.76.1` so these lines was [explicitly added](https://github.com/plaid/react-native-plaid-link-sdk/pull/717/files#diff-4a9a9ff5407be37810728eac9230d23972d777e1f36053099f04d1e61c2fc14bR11) to resolve that. It now appears that this lines are causing this issue 🤔 

I am going to test on `0.76.3` and `0.76.1` hopefully this is something we can resolve across all versions of React Native

**Comment by jessethouin** [comment]
My mistake, I'm actually using `11.13.0` with RN `0.76.3`, which works well. I haven't tried `11.13.1`.

**Comment by gavinnewcomer** [comment]
> Hey @gavinnewcomer & @jessethouin just want to confirm you're saying that removing 
> 
> 
> 
> ```
> 
> #ifdef RCT_NEW_ARCH_ENABLED
> 
> #import <react_native_plaid_link_sdk/react_native_plaid_link_sdk-Swift.h>
> 
> #else
> 
> ```
> 
> 
> 
> from `ios/PLKFabricHelpers.h` resolves the issue?
> 
> 
> 
> The reason I am asking this is because [this issue](https://github.com/plaid/react-native-plaid-link-sdk/issues/713) was reporting that without that line the SDK didn't compile on `0.76.1` so these lines was [explicitly added](https://github.com/plaid/react-native-plaid-link-sdk/pull/717/files#diff-4a9a9ff5407be37810728eac9230d23972d777e1f36053099f04d1e61c2fc14bR11) to resolve that. It now appears that this lines are causing this issue 🤔 
> 
> 
> 
> I am going to test on `0.76.3` and `0.76.1` hopefully this is something we can resolve across all versions of React Native 

Hey! Yes removing those lines allowed the app to compile on 0.76.3 but if those lines are present and you have the new architecture enabled the compilation fails.

**Comment by dtroupe-plaid** [comment]
I am going to push a release to fix this momentarily. For future reference please follow up in #713 I provided additional context there so I will close this issue.
