### ISSUE TITLE
PlaidModule.onActivityResult is getting called for Intents not related to Plaid

### ISSUE THREAD

**Issue by vafada** [plaid/react-native-plaid-link-sdk#75]
same issue with #37 

I'm on version 3.0.1, using Facebook login. Upon login via Facebook, the app crashes:

`03-09 08:04:42.006  4519  4519 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {com.truebill/com.truebill.MainActivity}: java.lang.IllegalArgumentException: Could not convert class com.facebook.login.LoginClient$Result`

This is the same error reported to #37 

It seems that `PlaidModule.onActivityResult` is getting called for Intents not related to Plaid. In our case, google and facebook login, so the code path goes to the else case:

https://github.com/plaid/react-native-plaid-link-sdk/blob/a62029b179ee1f45a629354341ff3bcf77008940/android/src/main/java/com/plaid/PlaidModule.kt#L233-L235

the `Intent.extra` has a value that is a Java Object:

`com.facebook.login.LoginClient$Result`
`com.google.android.gms.auth.api.signin.GoogleSignInAccount`

And react-native crashes because it cannot convert an Java-object to javascript:

https://github.com/facebook/react-native/blob/95a510180a7f67176666978168f19c1c0f92f3cd/ReactAndroid/src/main/java/com/facebook/react/bridge/Arguments.java#L69

So the main issue is, why is `PlaidModule.onActivityResult` getting invoked for Google and Facebook login?

For the workaround is to try/catch the else block:

```
   else {
      try {
        if (data.extras != null) {
          result.putMap(DATA, Arguments.makeNativeMap(data.extras))
        }
        this.callback?.invoke(result)
      } catch(t: Throwable) { 
            // log error
      }
    }
```

**Comment by ShaharyarMaroof** [comment]
Same issue here.

**Comment by ShaharyarMaroof** [comment]
Sharing the stacktrace here as well.
```
java.lang.RuntimeException Failure delivering result ResultInfo{who=null, request=1001, result=0, data=null} to activity {my.app/my.app.MainActivity}: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    ActivityThread.java:4622 android.app.ActivityThread.deliverResults
    ActivityThread.java:4664 android.app.ActivityThread.handleSendResult
    ActivityResultItem.java:49 android.app.servertransaction.ActivityResultItem.execute
    TransactionExecutor.java:108 android.app.servertransaction.TransactionExecutor.executeCallbacks
    TransactionExecutor.java:68 android.app.servertransaction.TransactionExecutor.execute
    ActivityThread.java:1960 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:214 android.os.Looper.loop
    ActivityThread.java:7094 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:494 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:975 com.android.internal.os.ZygoteInit.main

Caused by: java.lang.RuntimeException Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    CallbackImpl.java:28 com.facebook.react.bridge.CallbackImpl.invoke
    PlaidModule.kt:209 com.plaid.PlaidModule.onActivityResult
    ReactContext.java:277 com.facebook.react.bridge.ReactContext.onActivityResult
    ReactInstanceManager.java:704 com.facebook.react.ReactInstanceManager.onActivityResult
    ReactActivityDelegate.java:129 com.facebook.react.ReactActivityDelegate.onActivityResult
    ReactActivity.java:75 com.facebook.react.ReactActivity.onActivityResult
    Activity.java:7815 android.app.Activity.dispatchActivityResult
    ActivityThread.java:4615 android.app.ActivityThread.deliverResults
    ActivityThread.java:4664 android.app.ActivityThread.handleSendResult
    ActivityResultItem.java:49 android.app.servertransaction.ActivityResultItem.execute
    TransactionExecutor.java:108 android.app.servertransaction.TransactionExecutor.executeCallbacks
    TransactionExecutor.java:68 android.app.servertransaction.TransactionExecutor.execute
    ActivityThread.java:1960 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:214 android.os.Looper.loop
    ActivityThread.java:7094 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:494 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:975 com.android.internal.os.ZygoteInit.main
```

**Comment by vafada** [comment]
@ShaharyarMaroof 
yes, the try/catch block fixes my Google/Facebook login issue.

Looking at your stacktrace.... looks like the `this.callback?.invoke` is getting called... which is a different issue..

In my case, the flow goes to the `catch` block so `this.callback.invoke` doesn't get called.

**Comment by ShaharyarMaroof** [comment]
Any idea how I can fix this? I am getting this issue whenever I try to open braintree or google fit from my app. As soon as I press the back button from any of these popups the app crashes.

**Comment by vafada** [comment]
@ShaharyarMaroof 

yeah i dont think you can catch runtime exception... 

In your case you can inspect the `Intent` before calling the callback and make sure its from plaid...

or worse case... dont even invoke the callback in the else block or invoke the callback with your own data instead of the Intent extra data

**Comment by ShaharyarMaroof** [comment]
@vafada yes that's what I did and it seems to work now. Submitted a PR as well #77 .

**Comment by zsweigart** [comment]
Thanks for the contribution, I've reviewed the changes
