### ISSUE TITLE
RNLinkSDK fails to build for ios 3.1.0

### ISSUE THREAD

**Issue by maitham** [plaid/react-native-plaid-link-sdk#87]
I get the following error with v3.1.0 ios,  latest react native version . 

<img width="1023" alt="Screenshot 2020-03-20 at 19 05 21" src="https://user-images.githubusercontent.com/15156137/77217203-d578c580-6add-11ea-892b-e5f44b76d58c.png">

**Comment by nchase** [comment]
@zsweigart this appears to be broken for us as well. We cannot build on iOS with version 3.1.0.

**Comment by wkiefer** [comment]
we'll get a fix out for this today, thanks

**Comment by wkiefer** [comment]
Fixed in https://www.npmjs.com/package/react-native-plaid-link-sdk/v/3.1.1 — apologies for the break.
