### ISSUE TITLE
No visible @interface for 'NSObject' declares the selector 'count' on iOS Build

### ISSUE THREAD

**Issue by ziedjebali** [plaid/react-native-plaid-link-sdk#88]
Getting the error:

No visible @interface for 'NSObject' declares the selector 'count'

for this code:  

`    if ([accountSubtypes count] > 0) {
       linkConfiguration.accountSubtypes = accountSubtypes;
    }
`

<img width="1376" alt="Screen Shot 2020-03-21 at 12 42 37 PM" src="https://user-images.githubusercontent.com/9031738/77231460-75336380-6b71-11ea-9370-5e06416d5ce3.png">

**Comment by miguel-martinez-0** [comment]
Same Error for me...

**Comment by miguel-martinez-0** [comment]
> Getting the error:
> 
> No visible @interface for 'NSObject' declares the selector 'count'
> 
> for this code:
> 
> ` if ([accountSubtypes count] > 0) { linkConfiguration.accountSubtypes = accountSubtypes; }`
> 
> <img alt="Screen Shot 2020-03-21 at 12 42 37 PM" width="1376" src="https://user-images.githubusercontent.com/9031738/77231460-75336380-6b71-11ea-9370-5e06416d5ce3.png">

@ziedjebali , do you found a solution for this?...

**Comment by wkiefer** [comment]
This is fixed with https://github.com/plaid/react-native-plaid-link-sdk/pull/90 and is released in v3.1.1 — please let me know if you still have issues after upgrading. thanks!
