### ISSUE TITLE
Do you have SDK changelog?

### ISSUE THREAD

**Issue by alexmbp** [plaid/react-native-plaid-link-sdk#89]
Hello Plaid!

Do you have public changelog? I found update helpers, but I don't see some general changelog.
I also found that you have react-native 0.61.3 as a peer dependency. Does it mean that you library requires react-native 0.61+ ?

**Comment by JeroenMols** [comment]
Hi @alexmbp,

We've started to keep track of our changelog on our release page:
https://github.com/plaid/react-native-plaid-link-sdk/releases

We've slightly relaxed our `react-native` version requirements and now require anything higher than `0.61`. Should you be using an older version of `react-native`, that could work, but we don't provide any official support for that at this time.

Hope that (belatedly) answers your questions?

Jeroen
