### ISSUE TITLE
Export `openLink` method

### ISSUE THREAD

**Issue by 7patricia** [plaid/react-native-plaid-link-sdk#9]
It would be nice if we could use the `openLink` method directly, instead of having to show the user a screen with a button to click on in order to actually open the link.

**Comment by dustinhorton** [comment]
@7patricia A PR exporting this was merged today: https://github.com/plaid/react-native-plaid-link-sdk/pull/7

**Comment by wkiefer** [comment]
Yes! Updated npm version coming early next week, thanks!
