### ISSUE TITLE
Plog doesn't exist as a dependency, Android cannot compile

### ISSUE THREAD

**Issue by nchase** [plaid/react-native-plaid-link-sdk#92]
The Android code references  `Plog` in a few places, but `Plog` isn't included as a dependency

**Comment by pilotocheg** [comment]
The same

**Comment by miguel-martinez-0** [comment]
Same. Still no solution?

**Comment by nchase** [comment]
@pilotocheg @miguel-martinez-0 see this patch/fork: https://github.com/plaid/react-native-plaid-link-sdk/pull/94/

**Comment by amytang0** [comment]
Hi this was indeed resolved with https://github.com/plaid/react-native-plaid-link-sdk/pull/96.
Sorry about that, and thank you for the feedback! Please update to latest.
