### ISSUE TITLE
EU AUTH - INVALID_CREDENTIALS when using grant access

### ISSUE THREAD

**Issue by k11kirky** [plaid/react-native-plaid-link-sdk#98]
ENV: sandbox
Device: IOS simulator iphone10

I get onSuccess with any US bank however with any UK bank It never calls goes to my oauth redirect and throws this {"event": "ERROR", "metadata": {"error_code": "INVALID_CREDENTIALS", "error_message": "the provided credentials were not correct", "error_type": "ITEM_ERROR", "exit_status": "requires_credentials"} regardless if I click simulate error or grant access

**Comment by k11kirky** [comment]
When I change my redirect URL to something like "https://google.com" it redirects in the browser. However when i set it to the deep link back in my app, It doesnt seem to rerender the plaid link with additional params. Any help would be appreciated

**Comment by eduardborges** [comment]
Could you copy your code?

**Comment by eduardborges** [comment]
I'm getting the same error

**Comment by afh** [comment]
@k11kirky , @eduardborges We just released [LinkKit version 1.1.31](https://github.com/plaid/plaid-link-ios/releases/tag/ios%2F1.1.31) which contains improvements for EU accounting linking flows, can you update LinkKit and retry?

**Comment by JeroenMols** [comment]
Hi @k11kirky and @eduardborges,

It has been a while since we heard from you and our SDK has improved quite a bit over the last few months.
Are you still seeing this issue on the latest version of our SDK?

Thank you and have a great end of the year,
Jeroen
